# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
# All modifications must be shared under the same license.
# No commercial use without explicit permission.
"""
strategies/dynamic_registry.py
===============================
Dynamic Strategy Registry — enables zero-downtime strategy deployment.

Allows strategies (including those generated by the No-Code builder) to be
loaded, validated, and swapped at runtime without requiring a service restart.

Architecture
------------
- Strategies are stored in the database as Python source code with metadata.
- The registry compiles and instantiates strategies in isolated namespaces.
- AST-based safety validation prevents dangerous operations (os.system, eval, etc.).
- Event-driven updates via Redis pub/sub ensure all pods stay in sync.
- Atomic swap ensures the active strategy set is always consistent.

Usage
-----
    from strategies.dynamic_registry import get_dynamic_registry

    registry = get_dynamic_registry()

    # Register a new strategy from source code
    version_id = await registry.register_strategy(
        name="MyCustomStrategy",
        source_code=code_string,
        symbol="XAU_USD",
        timeframe="M15",
        author_id="user_123",
    )

    # Activate the strategy (makes it available for signal generation)
    await registry.activate_strategy(version_id)

    # Get all active dynamic strategies
    active = registry.get_active_strategies()
"""
from __future__ import annotations

import ast
import asyncio
import hashlib
import importlib
import logging
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

UTC = timezone.utc
logger = logging.getLogger(__name__)

# ── Safety: forbidden AST nodes and names ─────────────────────────────────────

_FORBIDDEN_IMPORTS = frozenset({
    "os", "sys", "subprocess", "shutil", "pathlib",
    "socket", "http", "urllib", "requests", "aiohttp",
    "ctypes", "multiprocessing", "threading",
    "signal", "pty", "fcntl", "resource",
    "importlib", "builtins", "__builtin__",
})

_FORBIDDEN_CALLS = frozenset({
    "eval", "exec", "compile", "open", "input",
    "__import__", "getattr", "setattr", "delattr",
    "globals", "locals", "vars", "dir",
    "breakpoint", "exit", "quit",
})

_FORBIDDEN_ATTRIBUTES = frozenset({
    "__subclasses__", "__bases__", "__mro__",
    "__code__", "__globals__", "__builtins__",
})


class StrategyState(Enum):
    """Lifecycle state of a dynamic strategy."""
    DRAFT = "draft"
    VALIDATING = "validating"
    VALIDATED = "validated"
    ACTIVE = "active"
    PAUSED = "paused"
    FAILED = "failed"
    RETIRED = "retired"


@dataclass
class StrategyVersion:
    """A single version of a dynamically loaded strategy."""
    version_id: str
    name: str
    source_code: str
    source_hash: str
    symbol: str
    timeframe: str
    author_id: str
    state: StrategyState = StrategyState.DRAFT
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    activated_at: datetime | None = None
    validation_errors: list[str] = field(default_factory=list)
    performance_metrics: dict[str, float] = field(default_factory=dict)
    instance: Any = None  # The compiled strategy instance

    def to_dict(self) -> dict[str, Any]:
        return {
            "version_id": self.version_id,
            "name": self.name,
            "source_hash": self.source_hash,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "author_id": self.author_id,
            "state": self.state.value,
            "created_at": self.created_at.isoformat(),
            "activated_at": self.activated_at.isoformat() if self.activated_at else None,
            "validation_errors": self.validation_errors,
            "performance_metrics": self.performance_metrics,
        }


class ASTSafetyValidator(ast.NodeVisitor):
    """
    Validates Python AST for safety — prevents dangerous operations.

    Checks for:
    - Forbidden imports (os, sys, subprocess, etc.)
    - Forbidden function calls (eval, exec, open, etc.)
    - Forbidden attribute access (__subclasses__, __globals__, etc.)
    """

    def __init__(self) -> None:
        self.errors: list[str] = []

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            module_root = alias.name.split(".")[0]
            if module_root in _FORBIDDEN_IMPORTS:
                self.errors.append(
                    f"Line {node.lineno}: forbidden import '{alias.name}'"
                )
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        if node.module:
            module_root = node.module.split(".")[0]
            if module_root in _FORBIDDEN_IMPORTS:
                self.errors.append(
                    f"Line {node.lineno}: forbidden import from '{node.module}'"
                )
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name):
            if node.func.id in _FORBIDDEN_CALLS:
                self.errors.append(
                    f"Line {node.lineno}: forbidden call to '{node.func.id}()'"
                )
        elif isinstance(node.func, ast.Attribute):
            if node.func.attr in _FORBIDDEN_CALLS:
                self.errors.append(
                    f"Line {node.lineno}: forbidden call to '.{node.func.attr}()'"
                )
        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if node.attr in _FORBIDDEN_ATTRIBUTES:
            self.errors.append(
                f"Line {node.lineno}: forbidden attribute access '.{node.attr}'"
            )
        self.generic_visit(node)


class DynamicStrategyRegistry:
    """
    Central registry for dynamically loaded trading strategies.

    Provides:
    - AST-based safety validation before compilation
    - Isolated namespace compilation
    - Atomic swap of active strategy instances
    - Event-driven synchronization across pods via Redis pub/sub
    - Performance tracking per strategy version
    """

    _CH_STRATEGY_UPDATE = "hopefx:strategy:updated"

    def __init__(self) -> None:
        self._versions: dict[str, StrategyVersion] = {}
        self._active: dict[str, StrategyVersion] = {}  # name -> active version
        self._lock = asyncio.Lock()
        self._redis: Any = None
        self._db_session_factory: Any = None
        self._running = False
        self._subscriber_task: asyncio.Task | None = None

    async def start(self, redis_client: Any = None, db_session_factory: Any = None) -> None:
        """Initialize the registry with Redis and DB connections."""
        self._redis = redis_client
        self._db_session_factory = db_session_factory
        self._running = True

        # Load persisted strategies from database
        await self._load_from_database()

        # Start listening for cross-pod update events
        if self._redis:
            self._subscriber_task = asyncio.create_task(self._listen_for_updates())

        logger.info(
            "DynamicStrategyRegistry started: %d versions loaded, %d active",
            len(self._versions),
            len(self._active),
        )

    async def stop(self) -> None:
        """Graceful shutdown."""
        self._running = False
        if self._subscriber_task:
            self._subscriber_task.cancel()
            try:
                await self._subscriber_task
            except asyncio.CancelledError:
                pass
        logger.info("DynamicStrategyRegistry stopped")

    # ── Public API ────────────────────────────────────────────────────────────

    async def register_strategy(
        self,
        name: str,
        source_code: str,
        symbol: str,
        timeframe: str,
        author_id: str,
    ) -> str:
        """
        Register a new strategy version.

        Validates the source code for safety, compiles it, and stores
        the version. Does NOT activate it — call activate_strategy() separately.

        Returns the version_id on success.
        Raises ValueError if validation fails.
        """
        source_hash = hashlib.sha256(source_code.encode()).hexdigest()
        version_id = f"{name}_{uuid.uuid4().hex[:8]}"

        version = StrategyVersion(
            version_id=version_id,
            name=name,
            source_code=source_code,
            source_hash=source_hash,
            symbol=symbol,
            timeframe=timeframe,
            author_id=author_id,
            state=StrategyState.VALIDATING,
        )

        # Phase 1: AST safety validation
        errors = self._validate_safety(source_code)
        if errors:
            version.state = StrategyState.FAILED
            version.validation_errors = errors
            self._versions[version_id] = version
            raise ValueError(f"Strategy validation failed: {'; '.join(errors)}")

        # Phase 2: Compilation in isolated namespace
        try:
            instance = self._compile_strategy(name, source_code)
            version.instance = instance
            version.state = StrategyState.VALIDATED
        except Exception as exc:
            version.state = StrategyState.FAILED
            version.validation_errors = [f"Compilation error: {exc}"]
            self._versions[version_id] = version
            raise ValueError(f"Strategy compilation failed: {exc}") from exc

        # Phase 3: Structural validation — must have required methods
        structural_errors = self._validate_structure(instance)
        if structural_errors:
            version.state = StrategyState.FAILED
            version.validation_errors = structural_errors
            self._versions[version_id] = version
            raise ValueError(f"Structural validation failed: {'; '.join(structural_errors)}")

        self._versions[version_id] = version

        # Persist to database
        await self._persist_version(version)

        logger.info(
            "Strategy registered: name=%s version_id=%s hash=%s",
            name, version_id, source_hash[:12],
        )
        return version_id

    async def activate_strategy(self, version_id: str) -> None:
        """
        Activate a validated strategy version.

        Atomically swaps the previous active version (if any) for this name.
        Publishes an update event to Redis so other pods sync.
        """
        async with self._lock:
            version = self._versions.get(version_id)
            if not version:
                raise ValueError(f"Version not found: {version_id}")
            if version.state not in (StrategyState.VALIDATED, StrategyState.PAUSED):
                raise ValueError(
                    f"Cannot activate strategy in state '{version.state.value}'. "
                    f"Must be 'validated' or 'paused'."
                )

            # Deactivate previous version for this strategy name
            prev = self._active.get(version.name)
            if prev and prev.version_id != version_id:
                prev.state = StrategyState.RETIRED
                prev.instance = None  # Free memory
                await self._persist_version(prev)

            # Activate new version
            version.state = StrategyState.ACTIVE
            version.activated_at = datetime.now(UTC)
            self._active[version.name] = version

            await self._persist_version(version)

        # Notify other pods
        await self._publish_update(version_id, "activated")

        logger.info("Strategy activated: %s (version %s)", version.name, version_id)

    async def deactivate_strategy(self, name: str) -> None:
        """Pause an active strategy without retiring it."""
        async with self._lock:
            version = self._active.pop(name, None)
            if not version:
                raise ValueError(f"No active strategy with name '{name}'")
            version.state = StrategyState.PAUSED
            await self._persist_version(version)

        await self._publish_update(version.version_id, "deactivated")
        logger.info("Strategy deactivated: %s", name)

    def get_active_strategies(self) -> dict[str, StrategyVersion]:
        """Return all currently active strategy versions."""
        return dict(self._active)

    def get_strategy_instance(self, name: str) -> Any | None:
        """Return the compiled instance of an active strategy by name."""
        version = self._active.get(name)
        return version.instance if version else None

    def get_all_versions(self, name: str | None = None) -> list[StrategyVersion]:
        """Return all registered versions, optionally filtered by name."""
        if name:
            return [v for v in self._versions.values() if v.name == name]
        return list(self._versions.values())

    def health(self) -> dict[str, Any]:
        """Return registry health metrics."""
        return {
            "running": self._running,
            "total_versions": len(self._versions),
            "active_strategies": len(self._active),
            "active_names": list(self._active.keys()),
            "states": {
                state.value: sum(1 for v in self._versions.values() if v.state == state)
                for state in StrategyState
            },
        }

    # ── Validation ────────────────────────────────────────────────────────────

    def _validate_safety(self, source_code: str) -> list[str]:
        """Run AST-based safety checks on the source code."""
        try:
            tree = ast.parse(source_code)
        except SyntaxError as exc:
            return [f"Syntax error at line {exc.lineno}: {exc.msg}"]

        validator = ASTSafetyValidator()
        validator.visit(tree)
        return validator.errors

    def _compile_strategy(self, name: str, source_code: str) -> Any:
        """
        Compile strategy source code in an isolated namespace.

        Returns the strategy class instance (not the class itself).
        The namespace provides access to allowed imports only.
        """
        # Provide a restricted set of allowed modules
        import numpy as np

        allowed_globals: dict[str, Any] = {
            "__builtins__": {
                "range": range,
                "len": len,
                "max": max,
                "min": min,
                "abs": abs,
                "round": round,
                "sum": sum,
                "sorted": sorted,
                "enumerate": enumerate,
                "zip": zip,
                "map": map,
                "filter": filter,
                "list": list,
                "dict": dict,
                "set": set,
                "tuple": tuple,
                "int": int,
                "float": float,
                "str": str,
                "bool": bool,
                "None": None,
                "True": True,
                "False": False,
                "isinstance": isinstance,
                "issubclass": issubclass,
                "hasattr": hasattr,
                "type": type,
                "print": lambda *a, **kw: None,  # Silenced
                "ValueError": ValueError,
                "TypeError": TypeError,
                "KeyError": KeyError,
                "IndexError": IndexError,
                "RuntimeError": RuntimeError,
                "Exception": Exception,
                "property": property,
                "staticmethod": staticmethod,
                "classmethod": classmethod,
                "super": super,
                "object": object,
            },
            "np": np,
            "numpy": np,
        }

        # Inject base strategy classes so user code can inherit from them
        try:
            from strategies.base import BaseStrategy, Signal, SignalType, StrategyConfig
            allowed_globals["BaseStrategy"] = BaseStrategy
            allowed_globals["Signal"] = Signal
            allowed_globals["SignalType"] = SignalType
            allowed_globals["StrategyConfig"] = StrategyConfig
        except ImportError:
            logger.warning("strategies.base not available for dynamic compilation")

        # Compile and execute in isolated namespace
        code_obj = compile(source_code, f"<dynamic:{name}>", "exec")
        exec(code_obj, allowed_globals)  # noqa: S102 — intentional, sandboxed exec

        # Find the strategy class (must subclass BaseStrategy or have generate_signal)
        strategy_class = None
        for obj_name, obj in allowed_globals.items():
            if (
                isinstance(obj, type)
                and obj_name != "BaseStrategy"
                and hasattr(obj, "generate_signal")
            ):
                strategy_class = obj
                break

        if strategy_class is None:
            raise ValueError(
                "No valid strategy class found. "
                "The code must define a class with a 'generate_signal' method."
            )

        # Instantiate with default config
        try:
            from strategies.base import StrategyConfig as _SC
            instance = strategy_class(config=_SC(name=name, symbol="XAU_USD"))
        except Exception:
            instance = strategy_class(config={"name": name, "symbol": "XAU_USD"})

        return instance

    def _validate_structure(self, instance: Any) -> list[str]:
        """Verify the compiled strategy has the required interface."""
        errors = []
        required_methods = ["generate_signal"]
        for method in required_methods:
            if not hasattr(instance, method) or not callable(getattr(instance, method)):
                errors.append(f"Missing required method: {method}()")

        # Check that generate_signal accepts the right signature
        import inspect
        try:
            sig = inspect.signature(instance.generate_signal)
            params = list(sig.parameters.keys())
            if len(params) < 1:
                errors.append(
                    "generate_signal() must accept at least one parameter (market data)"
                )
        except (ValueError, TypeError):
            pass  # Cannot inspect — skip

        return errors

    # ── Persistence ───────────────────────────────────────────────────────────

    async def _load_from_database(self) -> None:
        """Load all strategy versions from the database on startup."""
        if not self._db_session_factory:
            logger.debug("DynamicStrategyRegistry: no DB session factory — skipping load")
            return

        try:
            from database.models import DynamicStrategy
            session = self._db_session_factory()
            try:
                records = session.query(DynamicStrategy).all()
                for record in records:
                    version = StrategyVersion(
                        version_id=record.version_id,
                        name=record.name,
                        source_code=record.source_code,
                        source_hash=record.source_hash,
                        symbol=record.symbol,
                        timeframe=record.timeframe,
                        author_id=record.author_id,
                        state=StrategyState(record.state),
                        created_at=record.created_at,
                        activated_at=record.activated_at,
                    )
                    # Re-compile active strategies
                    if version.state == StrategyState.ACTIVE:
                        try:
                            version.instance = self._compile_strategy(
                                version.name, version.source_code
                            )
                            self._active[version.name] = version
                        except Exception as exc:
                            logger.error(
                                "Failed to recompile active strategy %s: %s",
                                version.name, exc,
                            )
                            version.state = StrategyState.FAILED
                            version.validation_errors = [f"Recompilation failed: {exc}"]

                    self._versions[version.version_id] = version

                logger.info(
                    "DynamicStrategyRegistry: loaded %d versions from DB", len(records)
                )
            finally:
                session.close()
        except ImportError:
            logger.debug("DynamicStrategy model not available — skipping DB load")
        except Exception as exc:
            logger.warning("DynamicStrategyRegistry: DB load failed: %s", exc)

    async def _persist_version(self, version: StrategyVersion) -> None:
        """Persist a strategy version to the database."""
        if not self._db_session_factory:
            return

        try:
            from database.models import DynamicStrategy
            session = self._db_session_factory()
            try:
                record = (
                    session.query(DynamicStrategy)
                    .filter(DynamicStrategy.version_id == version.version_id)
                    .first()
                )
                if record:
                    record.state = version.state.value
                    record.activated_at = version.activated_at
                    record.source_hash = version.source_hash
                else:
                    record = DynamicStrategy(
                        version_id=version.version_id,
                        name=version.name,
                        source_code=version.source_code,
                        source_hash=version.source_hash,
                        symbol=version.symbol,
                        timeframe=version.timeframe,
                        author_id=version.author_id,
                        state=version.state.value,
                        created_at=version.created_at,
                        activated_at=version.activated_at,
                    )
                    session.add(record)
                session.commit()
            finally:
                session.close()
        except ImportError:
            logger.debug("DynamicStrategy model not available — skipping persist")
        except Exception as exc:
            logger.warning("DynamicStrategyRegistry: persist failed: %s", exc)

    # ── Cross-pod synchronization ─────────────────────────────────────────────

    async def _publish_update(self, version_id: str, action: str) -> None:
        """Publish a strategy update event to Redis for cross-pod sync."""
        if not self._redis:
            return
        try:
            import json
            payload = json.dumps({
                "version_id": version_id,
                "action": action,
                "timestamp": datetime.now(UTC).isoformat(),
            })
            loop = asyncio.get_running_loop()
            await loop.run_in_executor(
                None,
                lambda: self._redis.publish(self._CH_STRATEGY_UPDATE, payload),
            )
        except Exception as exc:
            logger.warning("DynamicStrategyRegistry: publish update failed: %s", exc)

    async def _listen_for_updates(self) -> None:
        """Subscribe to strategy update events from other pods."""
        if not self._redis:
            return

        try:
            import json
            pubsub = self._redis.pubsub()
            pubsub.subscribe(self._CH_STRATEGY_UPDATE)

            while self._running:
                message = pubsub.get_message(ignore_subscribe_messages=True, timeout=1.0)
                if message and message["type"] == "message":
                    try:
                        data = json.loads(message["data"])
                        version_id = data.get("version_id")
                        action = data.get("action")

                        if action == "activated":
                            await self._sync_activation(version_id)
                        elif action == "deactivated":
                            await self._sync_deactivation(version_id)

                    except Exception as exc:
                        logger.warning(
                            "DynamicStrategyRegistry: failed to process update: %s", exc
                        )

                await asyncio.sleep(0.1)
        except asyncio.CancelledError:
            pass
        except Exception as exc:
            logger.error("DynamicStrategyRegistry: subscriber crashed: %s", exc)

    async def _sync_activation(self, version_id: str) -> None:
        """Sync an activation event from another pod."""
        version = self._versions.get(version_id)
        if version and version.state == StrategyState.ACTIVE:
            return  # Already active locally

        # Reload from database
        await self._load_from_database()

    async def _sync_deactivation(self, version_id: str) -> None:
        """Sync a deactivation event from another pod."""
        version = self._versions.get(version_id)
        if version and version.name in self._active:
            async with self._lock:
                self._active.pop(version.name, None)
                version.state = StrategyState.PAUSED
                version.instance = None


# ── Module-level singleton ────────────────────────────────────────────────────

_registry: DynamicStrategyRegistry | None = None


def get_dynamic_registry() -> DynamicStrategyRegistry:
    """Return the module-level DynamicStrategyRegistry singleton."""
    global _registry
    if _registry is None:
        _registry = DynamicStrategyRegistry()
    return _registry
