# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
# All modifications must be shared under the same license.
# No commercial use without explicit permission.
"""
strategies/dynamic_registry.py
===============================
Dynamic Strategy Registry — enables zero-downtime strategy deployment.

Allows strategies (including those generated by the No-Code builder) to be
loaded, validated, and swapped at runtime without requiring a service restart.

Architecture
------------
- Strategies are stored in the database as Python source code with metadata.
- The registry compiles and instantiates strategies in isolated namespaces.
- AST-based safety validation prevents dangerous operations (os.system, eval, etc.).
- Event-driven updates via Redis pub/sub ensure all pods stay in sync.
- Atomic swap ensures the active strategy set is always consistent.

Usage
-----
    from strategies.dynamic_registry import get_dynamic_registry

    registry = get_dynamic_registry()

    # Register a new strategy from source code
    version_id = await registry.register_strategy(
        name="MyCustomStrategy",
        source_code=code_string,
        symbol="XAU_USD",
        timeframe="M15",
        author_id="user_123",
    )

    # Activate the strategy (makes it available for signal generation)
    await registry.activate_strategy(version_id)

    # Get all active dynamic strategies
    active = registry.get_active_strategies()
"""

from __future__ import annotations

import ast
import asyncio
import contextlib
import hashlib
import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from core.ai_contracts import HumanApproval, ResearchCandidate
from strategies.strategy_execution_boundary import ExecutionScope, StrategyExecutionBoundary

UTC = timezone.utc
logger = logging.getLogger(__name__)

# ── Safety: forbidden AST nodes and names ─────────────────────────────────────

_FORBIDDEN_IMPORTS = frozenset(
    {
        "os",
        "sys",
        "subprocess",
        "shutil",
        "pathlib",
        "socket",
        "http",
        "urllib",
        "requests",
        "aiohttp",
        "ctypes",
        "multiprocessing",
        "threading",
        "signal",
        "pty",
        "fcntl",
        "resource",
        "importlib",
        "builtins",
        "__builtin__",
    }
)

_FORBIDDEN_CALLS = frozenset(
    {
        "eval",
        "exec",
        "compile",
        "open",
        "input",
        "__import__",
        "getattr",
        "setattr",
        "delattr",
        "globals",
        "locals",
        "vars",
        "dir",
        "breakpoint",
        "exit",
        "quit",
    }
)

_FORBIDDEN_ATTRIBUTES = frozenset(
    {
        "__subclasses__",
        "__bases__",
        "__mro__",
        "__code__",
        "__globals__",
        "__builtins__",
    }
)


class StrategyState(Enum):
    """Lifecycle state of a dynamic strategy."""

    DRAFT = "draft"
    VALIDATING = "validating"
    VALIDATED = "validated"
    ACTIVE = "active"
    PAUSED = "paused"
    FAILED = "failed"
    RETIRED = "retired"


@dataclass
class StrategyVersion:
    """A single version of a dynamically loaded strategy."""

    version_id: str
    name: str
    source_code: str
    source_hash: str
    symbol: str
    timeframe: str
    author_id: str
    state: StrategyState = StrategyState.DRAFT
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    activated_at: datetime | None = None
    validation_errors: list[str] = field(default_factory=list)
    performance_metrics: dict[str, float] = field(default_factory=dict)
    candidate: ResearchCandidate | None = None
    instance: Any = None  # The compiled strategy instance

    def to_dict(self) -> dict[str, Any]:
        return {
            "version_id": self.version_id,
            "name": self.name,
            "source_hash": self.source_hash,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "author_id": self.author_id,
            "state": self.state.value,
            "created_at": self.created_at.isoformat(),
            "activated_at": self.activated_at.isoformat() if self.activated_at else None,
            "validation_errors": self.validation_errors,
            "performance_metrics": self.performance_metrics,
        }


class ASTSafetyValidator(ast.NodeVisitor):
    """
    Validates Python AST for safety — prevents dangerous operations.

    Checks for:
    - Forbidden imports (os, sys, subprocess, etc.)
    - Forbidden function calls (eval, exec, open, etc.)
    - Forbidden attribute access (__subclasses__, __globals__, etc.)
    """

    def __init__(self) -> None:
        self.errors: list[str] = []

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            module_root = alias.name.split(".")[0]
            if module_root in _FORBIDDEN_IMPORTS:
                self.errors.append(f"Line {node.lineno}: forbidden import '{alias.name}'")
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        if node.module:
            module_root = node.module.split(".")[0]
            if module_root in _FORBIDDEN_IMPORTS:
                self.errors.append(f"Line {node.lineno}: forbidden import from '{node.module}'")
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name):
            if node.func.id in _FORBIDDEN_CALLS:
                self.errors.append(f"Line {node.lineno}: forbidden call to '{node.func.id}()'")
        elif isinstance(node.func, ast.Attribute) and node.func.attr in _FORBIDDEN_CALLS:
            self.errors.append(f"Line {node.lineno}: forbidden call to '.{node.func.attr}()'")
        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if node.attr in _FORBIDDEN_ATTRIBUTES:
            self.errors.append(f"Line {node.lineno}: forbidden attribute access '.{node.attr}'")
        self.generic_visit(node)

    def visit_Subscript(self, node: ast.Subscript) -> None:
        """Catch the same names reached by subscript instead of attribute.

        `visit_Attribute` only sees `ast.Attribute` nodes, so it caught
        `x.__subclasses__` but not `x.__dict__['__subclasses__']` — a subscript
        whose key is a plain string constant. That gap was a working bypass:

            type.__dict__['__subclasses__'](object)

        passed validation and reached the entire loaded type hierarchy, 715
        classes, from inside the restricted namespace.

        `__dict__` itself is deliberately not on the forbidden list — strategies
        legitimately introspect their own config — so the check belongs on the
        key rather than on the attribute that produced the mapping.
        """
        key = node.slice
        if isinstance(key, ast.Constant) and isinstance(key.value, str) and key.value in _FORBIDDEN_ATTRIBUTES:
            self.errors.append(f"Line {node.lineno}: forbidden attribute access via subscript '[{key.value!r}]'")
        self.generic_visit(node)


class DynamicStrategyRegistry:
    """
    Central registry for dynamically loaded trading strategies.

    Provides:
    - AST-based safety validation before compilation
    - Isolated namespace compilation
    - Atomic swap of active strategy instances
    - Event-driven synchronization across pods via Redis pub/sub
    - Performance tracking per strategy version
    """

    _CH_STRATEGY_UPDATE = "hopefx:strategy:updated"

    def __init__(self) -> None:
        self._versions: dict[str, StrategyVersion] = {}
        self._active: dict[str, StrategyVersion] = {}  # name -> active version
        self._lock = asyncio.Lock()
        self._redis: Any = None
        self._db_session_factory: Any = None
        self._running = False
        self._subscriber_task: asyncio.Task | None = None
        self._execution_boundary = StrategyExecutionBoundary()

    async def start(self, redis_client: Any = None, db_session_factory: Any = None) -> None:
        """Initialize the registry with Redis and DB connections."""
        self._redis = redis_client
        self._db_session_factory = db_session_factory
        self._running = True

        # Load persisted strategies from database
        await self._load_from_database()

        # Start listening for cross-pod update events
        if self._redis:
            self._subscriber_task = asyncio.create_task(self._listen_for_updates())

        logger.info(
            "DynamicStrategyRegistry started: %d versions loaded, %d active",
            len(self._versions),
            len(self._active),
        )

    async def stop(self) -> None:
        """Graceful shutdown."""
        self._running = False
        if self._subscriber_task:
            self._subscriber_task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await self._subscriber_task
        logger.info("DynamicStrategyRegistry stopped")

    # ── Public API ────────────────────────────────────────────────────────────

    async def register_strategy(
        self,
        name: str,
        source_code: str,
        symbol: str,
        timeframe: str,
        author_id: str,
        candidate: ResearchCandidate | None = None,
    ) -> str:
        """
        Register a new strategy version.

        Validates the source code for safety, compiles it, and stores
        the version. Does NOT activate it — call activate_strategy() separately.

        Returns the version_id on success.
        Raises ValueError if validation fails.
        """
        source_hash = hashlib.sha256(source_code.encode()).hexdigest()
        version_id = f"{name}_{uuid.uuid4().hex[:8]}"

        version = StrategyVersion(
            version_id=version_id,
            name=name,
            source_code=source_code,
            source_hash=source_hash,
            symbol=symbol,
            timeframe=timeframe,
            author_id=author_id,
            state=StrategyState.VALIDATING,
            candidate=candidate,
        )

        # Phase 1: AST safety validation
        errors = self._validate_safety(source_code)
        if errors:
            version.state = StrategyState.FAILED
            version.validation_errors = errors
            self._versions[version_id] = version
            raise ValueError(f"Strategy validation failed: {'; '.join(errors)}")

        # Phase 2: Compilation in isolated namespace
        try:
            instance = self._compile_strategy(name, source_code)
            version.instance = instance
            version.state = StrategyState.VALIDATED
        except Exception as exc:
            version.state = StrategyState.FAILED
            version.validation_errors = [f"Compilation error: {exc}"]
            self._versions[version_id] = version
            raise ValueError(f"Strategy compilation failed: {exc}") from exc

        # Phase 3: Structural validation — must have required methods
        structural_errors = self._validate_structure(instance)
        if structural_errors:
            version.state = StrategyState.FAILED
            version.validation_errors = structural_errors
            self._versions[version_id] = version
            raise ValueError(f"Structural validation failed: {'; '.join(structural_errors)}")

        self._versions[version_id] = version

        # Persist to database
        await self._persist_version(version)

        logger.info(
            "Strategy registered: name=%s version_id=%s hash=%s",
            name,
            version_id,
            source_hash[:12],
        )
        return version_id

    async def activate_strategy(
        self,
        version_id: str,
        scope: ExecutionScope = ExecutionScope.RESEARCH,
        approval: HumanApproval | None = None,
    ) -> None:
        """
        Activate a validated strategy version.

        Existing callers retain the legacy activation path. AI candidates carry
        an explicit lifecycle contract and must pass the additive boundary
        before activation at paper or live scope.
        """
        async with self._lock:
            version = self._versions.get(version_id)
            if version and version.candidate is not None:
                decision = self._execution_boundary.evaluate(version.candidate, scope, approval)
                if not decision.allowed:
                    raise ValueError(
                        f"Strategy activation denied ({decision.reason_code}): {decision.reason}"
                    )
            version = self._versions.get(version_id)
            if not version:
                raise ValueError(f"Version not found: {version_id}")
            if version.state not in (StrategyState.VALIDATED, StrategyState.PAUSED):
                raise ValueError(
                    f"Cannot activate strategy in state '{version.state.value}'. Must be 'validated' or 'paused'."
                )

            # Deactivate previous version for this strategy name
            prev = self._active.get(version.name)
            if prev and prev.version_id != version_id:
                prev.state = StrategyState.RETIRED
                prev.instance = None  # Free memory
                await self._persist_version(prev)

            # Activate new version
            version.state = StrategyState.ACTIVE
            version.activated_at = datetime.now(UTC)
            self._active[version.name] = version

            await self._persist_version(version)

        # Notify other pods
        await self._publish_update(version_id, "activated")

        logger.info("Strategy activated: %s (version %s)", version.name, version_id)

    async def deactivate_strategy(self, name: str) -> None:
        """Pause an active strategy without retiring it."""
        async with self._lock:
            version = self._active.pop(name, None)
            if not version:
                raise ValueError(f"No active strategy with name '{name}'")
            version.state = StrategyState.PAUSED
            await self._persist_version(version)

        await self._publish_update(version.version_id, "deactivated")
        logger.info("Strategy deactivated: %s", name)

    def get_active_strategies(self) -> dict[str, StrategyVersion]:
        """Return all currently active strategy versions."""
        return dict(self._active)

    def get_strategy_instance(self, name: str) -> Any | None:
        """Return the compiled instance of an active strategy by name."""
        version = self._active.get(name)
        return version.instance if version else None

    def get_all_versions(self, name: str | None = None) -> list[StrategyVersion]:
        """Return all registered versions, optionally filtered by name."""
        if name:
            return [v for v in self._versions.values() if v.name == name]
        return list(self._versions.values())

    def health(self) -> dict[str, Any]:
        """Return registry health metrics."""
        return {
            "running": self._running,
            "total_versions": len(self._versions),
            "active_strategies": len(self._active),
            "active_names": list(self._active.keys()),
            "states": {
                state.value: sum(1 for v in self._versions.values() if v.state == state) for state in StrategyState
            },
        }

    # ── Validation ────────────────────────────────────────────────────────────

    def _validate_safety(self, source_code: str) -> list[str]:
        """Run AST-based safety checks on the source code."""
        try:
            tree = ast.parse(source_code)
        except SyntaxError as exc:
            return [f"Syntax error at line {exc.lineno}: {exc.msg}"]

        validator = ASTSafetyValidator()
        validator.visit(tree)
        return validator.errors

    def _compile_strategy(self, name: str, source_code: str) -> Any:
        """
        Compile strategy source code in an isolated namespace.

        Returns the strategy class instance (not the class itself).
        The namespace provides access to allowed imports only.

        Trust boundary — read before changing anything here
        ---------------------------------------------------
        This executes caller-supplied Python. `ASTSafetyValidator` above is a
        genuine denylist — it blocks the textbook escapes, including
        `().__class__.__bases__[0].__subclasses__()`, `object.__subclasses__()`
        and `__globals__` — and `allowed_globals` below withholds the dangerous
        builtins. Together they raise the cost considerably. **But it is a
        denylist on a Turing-complete language, so it is defence in depth, not
        a boundary, and must not be described as a sandbox.**

        The concrete reason to believe that: `type.__dict__['__subclasses__']`
        reached the entire loaded type hierarchy — 715 classes — and passed
        validation, because `visit_Attribute` never sees a subscript.
        `visit_Subscript` now closes that specific hole. The point is not that
        one hole existed; it is that finding it took ten minutes, and nobody
        can prove the next one is not there.

        So the actual control is **who can reach this**, not what the namespace
        contains:

        - `api/dynamic_strategies.py::register_strategy` — `_require_admin()`
        - `api/nocode.py::deploy_template` — `require_plan("professional")`,
          and it compiles from a vetted template rather than raw source

        An admin can already stop the engine, move funds through the broker
        adapters, and rewrite risk limits. Code execution adds nothing to an
        account that holds those. That is the boundary this feature sits on,
        and it is deliberate: custom strategies are the product.

        What this means in practice:

        - Do **not** relax `_require_admin()` on the register endpoint, or
          expose `_compile_strategy` on any route reachable by a lower tier.
          The gate is the security control; the namespace is not.
        - Do **not** add convenience entries to `allowed_globals` — anything
          holding a reference to a module, a file, or a class hierarchy widens
          the escape surface with no compensating benefit.
        - Real isolation would mean executing in a separate process with
          dropped privileges, a seccomp profile and no network, communicating
          over a pipe. That is a design change, not a patch here, and it is the
          only thing that would let this endpoint be opened to non-admins.

        CodeQL flags this line as code injection (alert #24744). The finding is
        accurate as far as it goes — this *is* `exec` on caller input. It is
        accepted on the strength of the admin gate above, not on the strength
        of the namespace restriction.
        """
        # Provide a restricted set of allowed modules
        import numpy as np

        allowed_globals: dict[str, Any] = {
            "__builtins__": {
                "range": range,
                "len": len,
                "max": max,
                "min": min,
                "abs": abs,
                "round": round,
                "sum": sum,
                "sorted": sorted,
                "enumerate": enumerate,
                "zip": zip,
                "map": map,
                "filter": filter,
                "list": list,
                "dict": dict,
                "set": set,
                "tuple": tuple,
                "int": int,
                "float": float,
                "str": str,
                "bool": bool,
                "None": None,
                "True": True,
                "False": False,
                "isinstance": isinstance,
                "issubclass": issubclass,
                "hasattr": hasattr,
                "type": type,
                "print": lambda *a, **kw: None,  # Silenced
                "ValueError": ValueError,
                "TypeError": TypeError,
                "KeyError": KeyError,
                "IndexError": IndexError,
                "RuntimeError": RuntimeError,
                "Exception": Exception,
                "property": property,
                "staticmethod": staticmethod,
                "classmethod": classmethod,
                "super": super,
                "object": object,
            },
            "np": np,
            "numpy": np,
        }

        # Inject base strategy classes so user code can inherit from them
        try:
            from strategies.base import BaseStrategy, Signal, SignalType, StrategyConfig

            allowed_globals["BaseStrategy"] = BaseStrategy
            allowed_globals["Signal"] = Signal
            allowed_globals["SignalType"] = SignalType
            allowed_globals["StrategyConfig"] = StrategyConfig
        except ImportError:
            logger.warning("strategies.base not available for dynamic compilation")

        # Compile and execute in isolated namespace
        code_obj = compile(source_code, f"<dynamic:{name}>", "exec")
        exec(code_obj, allowed_globals)

        # Find the strategy class (must subclass BaseStrategy or have generate_signal)
        strategy_class = None
        for obj_name, obj in allowed_globals.items():
            if isinstance(obj, type) and obj_name != "BaseStrategy" and hasattr(obj, "generate_signal"):
                strategy_class = obj
                break

        if strategy_class is None:
            raise ValueError(
                "No valid strategy class found. The code must define a class with a 'generate_signal' method."
            )

        # Instantiate with default config
        try:
            from strategies.base import StrategyConfig as _SC

            instance = strategy_class(config=_SC(name=name, symbol="XAU_USD"))
        except Exception:
            instance = strategy_class(config={"name": name, "symbol": "XAU_USD"})

        return instance

    def _validate_structure(self, instance: Any) -> list[str]:
        """Verify the compiled strategy has the required interface."""
        errors = []
        required_methods = ["generate_signal"]
        for method in required_methods:
            if not hasattr(instance, method) or not callable(getattr(instance, method)):
                errors.append(f"Missing required method: {method}()")

        # Check that generate_signal accepts the right signature
        import inspect

        try:
            sig = inspect.signature(instance.generate_signal)
            params = list(sig.parameters.keys())
            if len(params) < 1:
                errors.append("generate_signal() must accept at least one parameter (market data)")
        except (ValueError, TypeError) as _sig_err:
            # Cannot introspect generate_signal() — skip the arity check. Benign;
            # log at debug so it's visible when validating a custom strategy.
            logger.debug("Cannot inspect generate_signal signature: %s", _sig_err)

        return errors

    # ── Persistence ───────────────────────────────────────────────────────────

    async def _load_from_database(self) -> None:
        """No-op: the registry is memory-only. Persistence is not implemented.

        This used to query ``database.models.DynamicStrategy``, which does not
        exist — `database/models.py` defines nineteen models and not that one,
        and no migration creates a table for it. The method never reached that
        import anyway: ``_db_session_factory`` is assigned only by ``start()``,
        and ``start()`` is called from nowhere, so the guard returned first.

        Re-enabling this is a product decision, not a repair. The body that was
        here re-compiled every ACTIVE record's ``source_code`` at startup via
        ``_compile_strategy``. Since ``/register`` accepts Python source from a
        caller, persisting it would mean user-supplied code stored in the
        database and executed on every boot — turning any future gap in
        ``_validate_safety`` into a problem that survives restarts.

        Kept as a method with its two call sites intact so wiring persistence
        later is filling this in, not rediscovering where it belongs.
        See S-51 in docs/HARDENING_BACKLOG.md.
        """
        if self._db_session_factory is not None:
            logger.warning(
                "DynamicStrategyRegistry: a DB session factory was supplied but "
                "persistence is not implemented — strategies remain in memory only. "
                "See S-51 in docs/HARDENING_BACKLOG.md."
            )

    async def _persist_version(self, version: StrategyVersion) -> None:
        """No-op: the registry is memory-only. See ``_load_from_database``.

        Called from register, activate and deactivate. It used to write to
        ``database.models.DynamicStrategy``, which does not exist.
        """
        return

    # ── Cross-pod synchronization ─────────────────────────────────────────────

    async def _publish_update(self, version_id: str, action: str) -> None:
        """Publish a strategy update event to Redis for cross-pod sync."""
        if not self._redis:
            return
        try:
            import json

            payload = json.dumps(
                {
                    "version_id": version_id,
                    "action": action,
                    "timestamp": datetime.now(UTC).isoformat(),
                }
            )
            loop = asyncio.get_running_loop()
            await loop.run_in_executor(
                None,
                lambda: self._redis.publish(self._CH_STRATEGY_UPDATE, payload),
            )
        except Exception as exc:
            logger.warning("DynamicStrategyRegistry: publish update failed: %s", exc)

    async def _listen_for_updates(self) -> None:
        """Subscribe to strategy update events from other pods."""
        if not self._redis:
            return

        try:
            import json

            pubsub = self._redis.pubsub()
            pubsub.subscribe(self._CH_STRATEGY_UPDATE)

            while self._running:
                message = pubsub.get_message(ignore_subscribe_messages=True, timeout=1.0)
                if message and message["type"] == "message":
                    try:
                        data = json.loads(message["data"])
                        version_id = data.get("version_id")
                        action = data.get("action")

                        if action == "activated":
                            await self._sync_activation(version_id)
                        elif action == "deactivated":
                            await self._sync_deactivation(version_id)

                    except Exception as exc:
                        logger.warning("DynamicStrategyRegistry: failed to process update: %s", exc)

                await asyncio.sleep(0.1)
        except asyncio.CancelledError:  # nosec B110 - graceful task cancellation; nothing to clean up
            pass
        except Exception as exc:
            logger.error("DynamicStrategyRegistry: subscriber crashed: %s", exc)

    async def _sync_activation(self, version_id: str) -> None:
        """Sync an activation event from another pod."""
        version = self._versions.get(version_id)
        if version and version.state == StrategyState.ACTIVE:
            return  # Already active locally

        # Reload from database
        await self._load_from_database()

    async def _sync_deactivation(self, version_id: str) -> None:
        """Sync a deactivation event from another pod."""
        version = self._versions.get(version_id)
        if version and version.name in self._active:
            async with self._lock:
                self._active.pop(version.name, None)
                version.state = StrategyState.PAUSED
                version.instance = None


# ── Module-level singleton ────────────────────────────────────────────────────

_registry: DynamicStrategyRegistry | None = None


def get_dynamic_registry() -> DynamicStrategyRegistry:
    """Return the module-level DynamicStrategyRegistry singleton."""
    global _registry
    if _registry is None:
        _registry = DynamicStrategyRegistry()
    return _registry
