# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# AGPL-3.0 — Share all modifications
"""
execution/algo_orders.py
========================
Execution algorithm layer: TWAP, VWAP, and Iceberg order types.

Sits between the signal layer and the broker — receives a large order and
slices it into child orders to minimise market impact and slippage.

Algorithms
----------
TWAP (Time-Weighted Average Price)
    Splits the order into N equal slices executed at fixed time intervals
    over a specified duration. Minimises timing risk; ignores volume.

VWAP (Volume-Weighted Average Price)
    Sizes each slice proportionally to the expected volume profile for that
    time-of-day. Tracks the VWAP benchmark; reduces impact in thin markets.

Iceberg
    Displays only a small visible quantity (peak_size) to the market.
    Refills automatically when the visible portion is filled.
    Hides true order size from other participants.

Architecture
------------
- AlgoOrder: base class with common state and lifecycle management.
- TWAPOrder, VWAPOrder, IcebergOrder: concrete implementations.
- AlgoOrderManager: manages active algo orders, routes child fills back.
- get_algo_manager(): module-level singleton.

Usage
-----
    from execution.algo_orders import AlgoOrderManager, get_algo_manager

    manager = get_algo_manager()
    asyncio.create_task(manager.run())

    # Submit a TWAP order (100 lots over 10 minutes, 10 slices)
    algo_id = await manager.submit_twap(
        symbol="XAU_USD",
        side="BUY",
        total_quantity=100.0,
        duration_seconds=600,
        num_slices=10,
        strategy_id="signal_v4",
    )

    # Submit a VWAP order
    algo_id = await manager.submit_vwap(
        symbol="XAU_USD",
        side="SELL",
        total_quantity=50.0,
        duration_seconds=1800,
        strategy_id="signal_v4",
    )

    # Submit an iceberg order
    algo_id = await manager.submit_iceberg(
        symbol="XAU_USD",
        side="BUY",
        total_quantity=200.0,
        peak_size=10.0,
        strategy_id="signal_v4",
    )

Configuration (env vars)
------------------------
ALGO_MIN_CHILD_SIZE     — minimum child order size (default: 0.01)
ALGO_MAX_PARTICIPATION  — max fraction of ADV per child (default: 0.05)
ALGO_TWAP_JITTER        — random timing jitter fraction for TWAP (default: 0.1)
ALGO_VWAP_PROFILE       — "flat" | "u_shaped" | "custom" (default: "u_shaped")
ALGO_ICEBERG_REFILL_PCT — refill when visible qty drops below this % (default: 0.1)
"""

from __future__ import annotations

import asyncio
import logging
import os
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone

UTC = timezone.utc
from enum import Enum
from typing import Any
from collections.abc import Callable

import numpy as np

logger = logging.getLogger(__name__)

# ── Configuration ─────────────────────────────────────────────────────────────
ALGO_MIN_CHILD_SIZE: float = float(os.getenv("ALGO_MIN_CHILD_SIZE", "0.01"))
ALGO_MAX_PARTICIPATION: float = float(os.getenv("ALGO_MAX_PARTICIPATION", "0.05"))
ALGO_TWAP_JITTER: float = float(os.getenv("ALGO_TWAP_JITTER", "0.1"))
ALGO_VWAP_PROFILE: str = os.getenv("ALGO_VWAP_PROFILE", "u_shaped")
ALGO_ICEBERG_REFILL_PCT: float = float(os.getenv("ALGO_ICEBERG_REFILL_PCT", "0.1"))


class AlgoStatus(Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    ERROR = "error"


@dataclass
class ChildOrder:
    """A single child order generated by an algo."""

    algo_id: str
    child_id: str = field(default_factory=lambda: str(uuid.uuid4())[:12])
    symbol: str = ""
    side: str = "BUY"
    quantity: float = 0.0
    scheduled_at: float = 0.0  # monotonic time
    submitted_at: float | None = None
    fill_price: float | None = None
    filled_quantity: float = 0.0
    status: str = "pending"


@dataclass
class AlgoFillReport:
    """Aggregated fill report for a completed algo order."""

    algo_id: str
    symbol: str
    side: str
    total_quantity: float
    filled_quantity: float
    avg_fill_price: float
    total_slippage_bps: float
    num_child_orders: int
    duration_seconds: float
    status: AlgoStatus
    child_orders: list[ChildOrder] = field(default_factory=list)


class AlgoOrder(ABC):
    """Base class for all execution algorithms."""

    def __init__(
        self,
        symbol: str,
        side: str,
        total_quantity: float,
        strategy_id: str = "unknown",
        broker_submit_fn: Callable | None = None,
    ) -> None:
        self.algo_id = str(uuid.uuid4())[:16]
        self.symbol = symbol
        self.side = side
        self.total_quantity = total_quantity
        self.strategy_id = strategy_id
        self._broker_submit = broker_submit_fn

        self.status = AlgoStatus.PENDING
        self.filled_quantity: float = 0.0
        self.child_orders: list[ChildOrder] = []
        self._fill_prices: list[tuple[float, float]] = []  # (qty, price)
        self._started_at: float | None = None
        self._completed_at: float | None = None
        self._task: asyncio.Task | None = None

    @property
    def remaining_quantity(self) -> float:
        return max(0.0, self.total_quantity - self.filled_quantity)

    @property
    def avg_fill_price(self) -> float:
        if not self._fill_prices:
            return 0.0
        total_qty = sum(q for q, _ in self._fill_prices)
        if total_qty == 0:
            return 0.0
        return sum(q * p for q, p in self._fill_prices) / total_qty

    def record_fill(self, quantity: float, price: float) -> None:
        """Record a child order fill."""
        self.filled_quantity += quantity
        self._fill_prices.append((quantity, price))

    def cancel(self) -> None:
        """Cancel the algo order."""
        self.status = AlgoStatus.CANCELLED
        if self._task and not self._task.done():
            self._task.cancel()
        logger.info(
            "AlgoOrder %s cancelled (filled %.2f/%.2f)",
            self.algo_id,
            self.filled_quantity,
            self.total_quantity,
        )

    def get_report(self) -> AlgoFillReport:
        duration = (self._completed_at or time.monotonic()) - (self._started_at or time.monotonic())
        return AlgoFillReport(
            algo_id=self.algo_id,
            symbol=self.symbol,
            side=self.side,
            total_quantity=self.total_quantity,
            filled_quantity=self.filled_quantity,
            avg_fill_price=self.avg_fill_price,
            total_slippage_bps=0.0,  # populated by TCA
            num_child_orders=len(self.child_orders),
            duration_seconds=duration,
            status=self.status,
            child_orders=self.child_orders,
        )

    @abstractmethod
    async def run(self) -> AlgoFillReport:
        """Execute the algorithm. Returns when complete or cancelled."""
        ...  # pylint: disable=unnecessary-ellipsis

    async def _submit_child(self, quantity: float) -> ChildOrder | None:
        """Submit a single child order to the broker."""
        if quantity < ALGO_MIN_CHILD_SIZE:
            logger.debug(
                "AlgoOrder %s: child size %.4f below minimum — skipping",
                self.algo_id,
                quantity,
            )
            return None

        child = ChildOrder(
            algo_id=self.algo_id,
            symbol=self.symbol,
            side=self.side,
            quantity=quantity,
            scheduled_at=time.monotonic(),
        )
        self.child_orders.append(child)

        if self._broker_submit is None:
            logger.warning("AlgoOrder %s: no broker_submit_fn — child order not sent", self.algo_id)
            return child

        try:
            child.submitted_at = time.monotonic()
            result = await self._broker_submit(
                symbol=self.symbol,
                side=self.side,
                quantity=quantity,
                order_type="MARKET",
                metadata={
                    "algo_id": self.algo_id,
                    "algo_type": type(self).__name__,
                    "strategy_id": self.strategy_id,
                },
            )
            if result and result.get("success"):
                fill_price = result.get("fill_price", 0.0)
                filled_qty = result.get("filled_quantity", quantity)
                child.fill_price = fill_price
                child.filled_quantity = filled_qty
                child.status = "filled"
                self.record_fill(filled_qty, fill_price)
                logger.debug(
                    "AlgoOrder %s: child filled %.4f @ %.4f",
                    self.algo_id,
                    filled_qty,
                    fill_price,
                )
            else:
                child.status = "rejected"
                logger.warning("AlgoOrder %s: child order rejected: %s", self.algo_id, result)
        except Exception as exc:
            child.status = "error"
            logger.error("AlgoOrder %s: child submit error: %s", self.algo_id, exc)

        return child


class TWAPOrder(AlgoOrder):
    """
    Time-Weighted Average Price execution.

    Splits total_quantity into num_slices equal parts, executed at
    fixed intervals over duration_seconds. Optional random jitter
    (ALGO_TWAP_JITTER) prevents predictable timing patterns.
    """

    def __init__(
        self,
        symbol: str,
        side: str,
        total_quantity: float,
        duration_seconds: float,
        num_slices: int = 10,
        strategy_id: str = "unknown",
        broker_submit_fn: Callable | None = None,
    ) -> None:
        super().__init__(symbol, side, total_quantity, strategy_id, broker_submit_fn)
        self.duration_seconds = duration_seconds
        self.num_slices = max(1, num_slices)
        self._interval = duration_seconds / self.num_slices

    async def run(self) -> AlgoFillReport:
        self.status = AlgoStatus.RUNNING
        self._started_at = time.monotonic()
        slice_qty = self.total_quantity / self.num_slices

        logger.info(
            "TWAP %s: %s %s %.4f over %.0fs in %d slices (%.4f each, interval=%.1fs)",
            self.algo_id,
            self.side,
            self.symbol,
            self.total_quantity,
            self.duration_seconds,
            self.num_slices,
            slice_qty,
            self._interval,
        )

        try:
            for i in range(self.num_slices):
                if self.status == AlgoStatus.CANCELLED:
                    break

                # Last slice: fill any rounding remainder
                qty = slice_qty if i < self.num_slices - 1 else self.remaining_quantity
                qty = max(0.0, qty)

                if qty >= ALGO_MIN_CHILD_SIZE:
                    await self._submit_child(qty)

                if i < self.num_slices - 1:
                    # Add jitter to avoid predictable timing
                    jitter = self._interval * ALGO_TWAP_JITTER * (np.random.random() - 0.5)
                    sleep_time = max(0.1, self._interval + jitter)
                    await asyncio.sleep(sleep_time)

            self.status = AlgoStatus.COMPLETED
        except asyncio.CancelledError:
            self.status = AlgoStatus.CANCELLED
        except Exception as exc:
            self.status = AlgoStatus.ERROR
            logger.error("TWAP %s error: %s", self.algo_id, exc)
        finally:
            self._completed_at = time.monotonic()

        report = self.get_report()
        logger.info(
            "TWAP %s complete: filled %.4f/%.4f @ avg %.4f in %.1fs",
            self.algo_id,
            report.filled_quantity,
            report.total_quantity,
            report.avg_fill_price,
            report.duration_seconds,
        )
        return report


class VWAPOrder(AlgoOrder):
    """
    Volume-Weighted Average Price execution.

    Sizes each slice proportionally to the expected intraday volume profile.
    Uses a U-shaped profile by default (high volume at open/close, low at midday)
    which is typical for FX and gold markets.

    The algo tracks the VWAP benchmark and adjusts slice timing to stay
    within a configurable deviation band.
    """

    # Intraday volume profiles (24 hourly buckets, normalised to sum=1)
    _PROFILES: dict[str, list[float]] = {
        "flat": [1 / 24] * 24,
        "u_shaped": [
            # Higher volume at London open (7-9 UTC), NY open (13-15 UTC),
            # and London/NY overlap (13-17 UTC). Lower at Asian session.
            0.025,
            0.020,
            0.018,
            0.018,
            0.020,
            0.025,  # 00-05 UTC (Asia)
            0.030,
            0.045,
            0.055,
            0.050,
            0.045,
            0.040,  # 06-11 UTC (London open)
            0.040,
            0.060,
            0.065,
            0.060,
            0.055,
            0.050,  # 12-17 UTC (NY open/overlap)
            0.045,
            0.040,
            0.035,
            0.030,
            0.028,
            0.027,  # 18-23 UTC (NY close)
        ],
    }

    def __init__(
        self,
        symbol: str,
        side: str,
        total_quantity: float,
        duration_seconds: float,
        num_slices: int = 20,
        strategy_id: str = "unknown",
        broker_submit_fn: Callable | None = None,
    ) -> None:
        super().__init__(symbol, side, total_quantity, strategy_id, broker_submit_fn)
        self.duration_seconds = duration_seconds
        self.num_slices = max(1, num_slices)
        self._interval = duration_seconds / self.num_slices

    def _get_volume_weights(self, start_hour_utc: int) -> list[float]:
        """Get volume weights for the execution window starting at start_hour_utc."""
        profile = self._PROFILES.get(ALGO_VWAP_PROFILE, self._PROFILES["u_shaped"])
        # Extract the relevant hours for this execution window
        hours_needed = max(1, int(self.duration_seconds / 3600))
        weights = []
        for i in range(hours_needed):
            hour = (start_hour_utc + i) % 24
            weights.append(profile[hour])
        # Normalise
        total = sum(weights) or 1.0
        return [w / total for w in weights]

    def _compute_slice_quantities(self) -> list[float]:
        """Compute per-slice quantities based on volume profile."""
        now_utc = datetime.now(UTC)
        weights = self._get_volume_weights(now_utc.hour)

        # Distribute slices across volume buckets
        slices_per_bucket = max(1, self.num_slices // len(weights))
        quantities = []
        for w in weights:
            bucket_qty = self.total_quantity * w
            slice_qty = bucket_qty / slices_per_bucket
            quantities.extend([slice_qty] * slices_per_bucket)

        # Trim or pad to exactly num_slices
        quantities = quantities[: self.num_slices]
        while len(quantities) < self.num_slices:
            quantities.append(0.0)

        # Ensure total matches (fix rounding)
        diff = self.total_quantity - sum(quantities)
        if quantities:
            quantities[-1] += diff

        return quantities

    async def run(self) -> AlgoFillReport:
        self.status = AlgoStatus.RUNNING
        self._started_at = time.monotonic()
        slice_quantities = self._compute_slice_quantities()

        logger.info(
            "VWAP %s: %s %s %.4f over %.0fs in %d slices (profile=%s)",
            self.algo_id,
            self.side,
            self.symbol,
            self.total_quantity,
            self.duration_seconds,
            self.num_slices,
            ALGO_VWAP_PROFILE,
        )

        try:
            for i, qty in enumerate(slice_quantities):
                if self.status == AlgoStatus.CANCELLED:
                    break

                # Last slice: fill remainder
                child_qty = self.remaining_quantity if i == len(slice_quantities) - 1 else qty

                if child_qty >= ALGO_MIN_CHILD_SIZE:
                    await self._submit_child(child_qty)

                if i < len(slice_quantities) - 1:
                    jitter = self._interval * ALGO_TWAP_JITTER * (np.random.random() - 0.5)
                    await asyncio.sleep(max(0.1, self._interval + jitter))

            self.status = AlgoStatus.COMPLETED
        except asyncio.CancelledError:
            self.status = AlgoStatus.CANCELLED
        except Exception as exc:
            self.status = AlgoStatus.ERROR
            logger.error("VWAP %s error: %s", self.algo_id, exc)
        finally:
            self._completed_at = time.monotonic()

        report = self.get_report()
        logger.info(
            "VWAP %s complete: filled %.4f/%.4f @ avg %.4f in %.1fs",
            self.algo_id,
            report.filled_quantity,
            report.total_quantity,
            report.avg_fill_price,
            report.duration_seconds,
        )
        return report


class IcebergOrder(AlgoOrder):
    """
    Iceberg (reserve) order execution.

    Displays only peak_size to the market at any time. When the visible
    portion is filled, a new slice of peak_size is automatically submitted.
    Hides the true order size from other market participants.

    The refill loop runs until total_quantity is filled or the order is cancelled.
    """

    def __init__(
        self,
        symbol: str,
        side: str,
        total_quantity: float,
        peak_size: float,
        refill_delay_seconds: float = 0.5,
        strategy_id: str = "unknown",
        broker_submit_fn: Callable | None = None,
    ) -> None:
        super().__init__(symbol, side, total_quantity, strategy_id, broker_submit_fn)
        self.peak_size = max(ALGO_MIN_CHILD_SIZE, peak_size)
        self.refill_delay = refill_delay_seconds
        self._visible_qty: float = 0.0

    async def run(self) -> AlgoFillReport:
        self.status = AlgoStatus.RUNNING
        self._started_at = time.monotonic()

        logger.info(
            "Iceberg %s: %s %s %.4f total, peak=%.4f",
            self.algo_id,
            self.side,
            self.symbol,
            self.total_quantity,
            self.peak_size,
        )

        try:
            while self.remaining_quantity >= ALGO_MIN_CHILD_SIZE:
                if self.status == AlgoStatus.CANCELLED:
                    break

                # Submit next visible slice
                slice_qty = min(self.peak_size, self.remaining_quantity)
                self._visible_qty = slice_qty
                await self._submit_child(slice_qty)
                self._visible_qty = 0.0

                if self.remaining_quantity >= ALGO_MIN_CHILD_SIZE:
                    await asyncio.sleep(self.refill_delay)

            self.status = AlgoStatus.COMPLETED
        except asyncio.CancelledError:
            self.status = AlgoStatus.CANCELLED
        except Exception as exc:
            self.status = AlgoStatus.ERROR
            logger.error("Iceberg %s error: %s", self.algo_id, exc)
        finally:
            self._completed_at = time.monotonic()

        report = self.get_report()
        logger.info(
            "Iceberg %s complete: filled %.4f/%.4f @ avg %.4f, %d child orders",
            self.algo_id,
            report.filled_quantity,
            report.total_quantity,
            report.avg_fill_price,
            report.num_child_orders,
        )
        return report


# ── AlgoOrderManager ──────────────────────────────────────────────────────────


class AlgoOrderManager:
    """
    Manages active algo orders and routes child fills.

    Provides a unified interface for submitting TWAP, VWAP, and Iceberg
    orders. Each algo runs in its own asyncio task.

    The manager also decides WHEN to use an algo vs a plain market order:
    - Orders > ALGO_LARGE_ORDER_THRESHOLD lots → use TWAP/VWAP
    - Orders > ALGO_ICEBERG_THRESHOLD lots → use Iceberg
    - Smaller orders → plain market order (no algo overhead)
    """

    # Thresholds for automatic algo selection (env-overridable)
    LARGE_ORDER_THRESHOLD: float = float(os.getenv("ALGO_LARGE_ORDER_THRESHOLD", "10.0"))
    ICEBERG_THRESHOLD: float = float(os.getenv("ALGO_ICEBERG_THRESHOLD", "50.0"))
    DEFAULT_TWAP_DURATION: float = float(os.getenv("ALGO_DEFAULT_TWAP_DURATION", "300"))
    DEFAULT_TWAP_SLICES: int = int(os.getenv("ALGO_DEFAULT_TWAP_SLICES", "10"))
    DEFAULT_ICEBERG_PEAK: float = float(os.getenv("ALGO_DEFAULT_ICEBERG_PEAK", "5.0"))

    def __init__(self, broker_submit_fn: Callable | None = None) -> None:
        self._broker_submit = broker_submit_fn
        self._active: dict[str, AlgoOrder] = {}
        self._completed: dict[str, AlgoFillReport] = {}
        self._tasks: dict[str, asyncio.Task] = {}

    def set_broker_submit_fn(self, fn: Callable) -> None:
        """Wire in the broker submission function after construction."""
        self._broker_submit = fn

    async def submit_twap(
        self,
        symbol: str,
        side: str,
        total_quantity: float,
        duration_seconds: float,
        num_slices: int = 10,
        strategy_id: str = "unknown",
    ) -> str:
        """Submit a TWAP order. Returns algo_id."""
        order = TWAPOrder(
            symbol=symbol,
            side=side,
            total_quantity=total_quantity,
            duration_seconds=duration_seconds,
            num_slices=num_slices,
            strategy_id=strategy_id,
            broker_submit_fn=self._broker_submit,
        )
        return await self._launch(order)

    async def submit_vwap(
        self,
        symbol: str,
        side: str,
        total_quantity: float,
        duration_seconds: float,
        num_slices: int = 20,
        strategy_id: str = "unknown",
    ) -> str:
        """Submit a VWAP order. Returns algo_id."""
        order = VWAPOrder(
            symbol=symbol,
            side=side,
            total_quantity=total_quantity,
            duration_seconds=duration_seconds,
            num_slices=num_slices,
            strategy_id=strategy_id,
            broker_submit_fn=self._broker_submit,
        )
        return await self._launch(order)

    async def submit_iceberg(
        self,
        symbol: str,
        side: str,
        total_quantity: float,
        peak_size: float,
        refill_delay_seconds: float = 0.5,
        strategy_id: str = "unknown",
    ) -> str:
        """Submit an Iceberg order. Returns algo_id."""
        order = IcebergOrder(
            symbol=symbol,
            side=side,
            total_quantity=total_quantity,
            peak_size=peak_size,
            refill_delay_seconds=refill_delay_seconds,
            strategy_id=strategy_id,
            broker_submit_fn=self._broker_submit,
        )
        return await self._launch(order)

    async def submit_auto(
        self,
        symbol: str,
        side: str,
        total_quantity: float,
        strategy_id: str = "unknown",
    ) -> str | None:
        """
        Automatically select and submit the appropriate algo based on order size.

        Returns algo_id if an algo was used, None if the order should be
        submitted as a plain market order.
        """
        if total_quantity >= self.ICEBERG_THRESHOLD:
            logger.info(
                "AlgoOrderManager: auto-selecting Iceberg for %.2f lots (%s %s)",
                total_quantity,
                side,
                symbol,
            )
            return await self.submit_iceberg(
                symbol=symbol,
                side=side,
                total_quantity=total_quantity,
                peak_size=self.DEFAULT_ICEBERG_PEAK,
                strategy_id=strategy_id,
            )
        elif total_quantity >= self.LARGE_ORDER_THRESHOLD:
            logger.info(
                "AlgoOrderManager: auto-selecting TWAP for %.2f lots (%s %s)",
                total_quantity,
                side,
                symbol,
            )
            return await self.submit_twap(
                symbol=symbol,
                side=side,
                total_quantity=total_quantity,
                duration_seconds=self.DEFAULT_TWAP_DURATION,
                num_slices=self.DEFAULT_TWAP_SLICES,
                strategy_id=strategy_id,
            )
        return None  # use plain market order

    def cancel(self, algo_id: str) -> bool:
        """Cancel an active algo order. Returns True if found and cancelled."""
        order = self._active.get(algo_id)
        if order:
            order.cancel()
            return True
        return False

    def get_status(self, algo_id: str) -> dict[str, Any] | None:
        """Return status dict for an active or completed algo order."""
        order = self._active.get(algo_id)
        if order:
            return {
                "algo_id": algo_id,
                "status": order.status.value,
                "filled": order.filled_quantity,
                "total": order.total_quantity,
                "remaining": order.remaining_quantity,
                "avg_price": order.avg_fill_price,
                "child_orders": len(order.child_orders),
            }
        report = self._completed.get(algo_id)
        if report:
            return {
                "algo_id": algo_id,
                "status": report.status.value,
                "filled": report.filled_quantity,
                "total": report.total_quantity,
                "avg_price": report.avg_fill_price,
                "duration_s": report.duration_seconds,
                "child_orders": report.num_child_orders,
            }
        return None

    def get_all_active(self) -> dict[str, dict[str, Any]]:
        """Return status for all active algo orders."""
        return {aid: self.get_status(aid) for aid in self._active}

    async def _launch(self, order: AlgoOrder) -> str:
        """Launch an algo order in a background task."""
        self._active[order.algo_id] = order
        task = asyncio.create_task(
            self._run_order(order),
            name=f"algo_{type(order).__name__}_{order.algo_id}",
        )
        self._tasks[order.algo_id] = task
        logger.info(
            "AlgoOrderManager: launched %s %s (id=%s)",
            type(order).__name__,
            order.symbol,
            order.algo_id,
        )
        return order.algo_id

    async def _run_order(self, order: AlgoOrder) -> None:
        """Run an algo order and move it to completed on finish."""
        try:
            report = await order.run()
            self._completed[order.algo_id] = report
        except Exception as exc:
            logger.error("AlgoOrderManager: order %s failed: %s", order.algo_id, exc)
        finally:
            self._active.pop(order.algo_id, None)
            self._tasks.pop(order.algo_id, None)


# ── Module-level singleton ────────────────────────────────────────────────────

_algo_manager: AlgoOrderManager | None = None


def get_algo_manager() -> AlgoOrderManager:
    """Return the module-level AlgoOrderManager singleton."""
    global _algo_manager
    if _algo_manager is None:
        _algo_manager = AlgoOrderManager()
    return _algo_manager
