"""initial_schema

Revision ID: 1b0666c43575
Revises: 
Create Date: 2026-03-21 18:02:56.975403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0666c43575'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('margin_used', sa.Float(), nullable=True),
    sa.Column('free_margin', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=True),
    sa.Column('total_exposure', sa.Float(), nullable=True),
    sa.Column('current_drawdown', sa.Float(), nullable=True),
    sa.Column('margin_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_account_snapshots_timestamp', 'account_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_account_snapshots_timestamp'), 'account_snapshots', ['timestamp'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('margin_used', sa.Float(), nullable=True),
    sa.Column('margin_free', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_snapshot_at'), 'accounts', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('ai_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_signals_generated_at'), 'ai_signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_ai_signals_symbol'), 'ai_signals', ['symbol'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('hash_chain', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_sequence_number'), 'audit_log', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kyc_user', 'kyc_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_kyc_records_user_id'), 'kyc_records', ['user_id'], unique=True)
    op.create_table('market_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('tick_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_timeframe_timestamp', 'market_data', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_timeframe'), 'market_data', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('news_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('symbols', sa.String(length=200), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_data_published_at'), 'news_data', ['published_at'], unique=False)
    op.create_table('order_book_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('bids_json', sa.Text(), nullable=True),
    sa.Column('asks_json', sa.Text(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('mid_price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_book_snapshots_symbol'), 'order_book_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_order_book_snapshots_timestamp'), 'order_book_snapshots', ['timestamp'], unique=False)
    op.create_table('performance_metric_samples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('labels_json', sa.Text(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metric_samples_metric_type'), 'performance_metric_samples', ['metric_type'], unique=False)
    op.create_index(op.f('ix_performance_metric_samples_strategy'), 'performance_metric_samples', ['strategy'], unique=False)
    op.create_index(op.f('ix_performance_metric_samples_symbol'), 'performance_metric_samples', ['symbol'], unique=False)
    op.create_index(op.f('ix_performance_metric_samples_timestamp'), 'performance_metric_samples', ['timestamp'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('avg_trade_duration_minutes', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_recorded_at'), 'performance_metrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_performance_metrics_strategy_name'), 'performance_metrics', ['strategy_name'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.Column('predicted_direction', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('horizon_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('error_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_symbol'), 'predictions', ['symbol'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_component'), 'system_events', ['component'], unique=False)
    op.create_index(op.f('ix_system_events_timestamp'), 'system_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_events_trace_id'), 'system_events', ['trace_id'], unique=False)
    op.create_table('tick_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tick_data_symbol'), 'tick_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_tick_data_timestamp'), 'tick_data', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_quantity', sa.Float(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_quantity', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('signal_source', sa.Enum('TREND_FOLLOWING', 'MEAN_REVERSION', 'BREAKOUT', 'MANUAL', 'STOP_LOSS', 'TAKE_PROFIT', name='signalsource'), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'CLOSED', 'CANCELLED', 'ERROR', name='tradestatus'), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_entry_time', 'trades', ['entry_time'], unique=False)
    op.create_index('idx_trades_symbol_status', 'trades', ['symbol', 'status'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verify_token', sa.String(length=255), nullable=True),
    sa.Column('email_verify_expires', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_user_created', 'wallet_transactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_transaction_id'), 'wallet_transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_email_time', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('idx_login_ip_time', 'login_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('average_fill_price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('is_filled', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.trade_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_symbol_created', 'orders', ['symbol', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('source', sa.Enum('TREND_FOLLOWING', 'MEAN_REVERSION', 'BREAKOUT', 'MANUAL', 'STOP_LOSS', 'TAKE_PROFIT', name='signalsource'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('execution_time', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.trade_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    op.create_index('idx_signals_generated_executed', 'signals', ['generated_at', 'executed'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('idx_sessions_token_hash', 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index('idx_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('idx_sessions_user', table_name='user_sessions')
    op.drop_index('idx_sessions_token_hash', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index('idx_signals_generated_executed', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index('idx_orders_symbol_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_index('idx_login_ip_time', table_name='login_attempts')
    op.drop_index('idx_login_email_time', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_transaction_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.drop_index('idx_wallet_user_created', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index('idx_trades_symbol_status', table_name='trades')
    op.drop_index('idx_trades_entry_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_tick_data_timestamp'), table_name='tick_data')
    op.drop_index(op.f('ix_tick_data_symbol'), table_name='tick_data')
    op.drop_table('tick_data')
    op.drop_index(op.f('ix_system_events_trace_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_timestamp'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_component'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_predictions_symbol'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_performance_metrics_strategy_name'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_recorded_at'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_performance_metric_samples_timestamp'), table_name='performance_metric_samples')
    op.drop_index(op.f('ix_performance_metric_samples_symbol'), table_name='performance_metric_samples')
    op.drop_index(op.f('ix_performance_metric_samples_strategy'), table_name='performance_metric_samples')
    op.drop_index(op.f('ix_performance_metric_samples_metric_type'), table_name='performance_metric_samples')
    op.drop_table('performance_metric_samples')
    op.drop_index(op.f('ix_order_book_snapshots_timestamp'), table_name='order_book_snapshots')
    op.drop_index(op.f('ix_order_book_snapshots_symbol'), table_name='order_book_snapshots')
    op.drop_table('order_book_snapshots')
    op.drop_index(op.f('ix_news_data_published_at'), table_name='news_data')
    op.drop_table('news_data')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_timeframe'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index('idx_symbol_timeframe_timestamp', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_kyc_records_user_id'), table_name='kyc_records')
    op.drop_index('idx_kyc_user', table_name='kyc_records')
    op.drop_table('kyc_records')
    op.drop_table('configurations')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_sequence_number'), table_name='audit_log')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ai_signals_symbol'), table_name='ai_signals')
    op.drop_index(op.f('ix_ai_signals_generated_at'), table_name='ai_signals')
    op.drop_table('ai_signals')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_snapshot_at'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_account_snapshots_timestamp'), table_name='account_snapshots')
    op.drop_index('idx_account_snapshots_timestamp', table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
