# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
# All modifications must be shared under the same license.
# No commercial use without explicit permission.
"""remove_duplicate_users_email_index

Revision ID: 746b2609eac5
Revises: 1b0666c43575
Create Date: 2026-03-21 18:54:19.012380

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "746b2609eac5"
down_revision: str | Sequence[str] | None = "1b0666c43575"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = [idx["name"] for idx in insp.get_indexes("users")]
    if "idx_users_email" in existing:
        op.drop_index("idx_users_email", table_name="users")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    # ### end Alembic commands ###
