"""remove_duplicate_users_email_index

Revision ID: 746b2609eac5
Revises: 1b0666c43575
Create Date: 2026-03-21 18:54:19.012380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746b2609eac5'
down_revision: Union[str, Sequence[str], None] = '1b0666c43575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###
