# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
# All modifications must be shared under the same license.
# No commercial use without explicit permission.
"""idempotency_and_new_tables

Revision ID: b2c3d4e5f6a7
Revises: f1a2b3c4d5e6
Create Date: 2026-06-01 00:00:00.000000

Changes
-------
1. Add UNIQUE(client_order_id) to trades and orders tables.
   Prevents duplicate order submission on broker retry (network timeout
   between API and broker).  client_order_id is the idempotency key
   generated by the trading engine before submission.

2. Create crypto_payments table — replaces in-memory _pending dict in
   api/payments.py.  Survives pod restarts; safe across replicas.

3. Create outbox_events table — transactional outbox for at-least-once
   delivery of critical compliance events (kill switch, AML block, fills).

4. Create config_store table — shared key-value config store used by
   risk settings, auto-pause config, and FOMC regime overrides.
"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f6a7"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "f1a2b3c4d5e6"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""

    # ── Idempotency helpers ───────────────────────────────────────────────────
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    _existing_tables = set(inspector.get_table_names())

    def _tbl(name, *args, **kwargs):
        """Create table only if it does not already exist."""
        if name not in _existing_tables:
            op.create_table(name, *args, **kwargs)

    def _idx(index_name, table_name, *args, **kwargs):
        """Create index only if it does not already exist.

        Re-inspects the live schema so indexes on tables created earlier in
        this same upgrade() call are handled correctly.
        """
        try:
            existing = {i["name"] for i in inspector.get_indexes(table_name)}
        except Exception:
            existing = set()
        if index_name not in existing:
            op.create_index(index_name, table_name, *args, **kwargs)

    def _col_exists(table_name, col_name):
        try:
            return col_name in {c["name"] for c in inspector.get_columns(table_name)}
        except Exception:
            return False

    # ── End idempotency helpers ───────────────────────────────────────────────

    # ── 1. client_order_id on trades ─────────────────────────────────────────
    # Use batch_alter_table for SQLite compatibility (ALTER COLUMN not supported).
    # Only run if the column doesn't already exist (idempotent).
    if not _col_exists("trades", "client_order_id"):
        with op.batch_alter_table("trades", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "client_order_id",
                    sa.String(length=100),
                    nullable=True,
                )
            )
            batch_op.create_unique_constraint("uq_trades_client_order_id", ["client_order_id"])
            batch_op.create_index("ix_trades_client_order_id", ["client_order_id"], unique=True)

    # ── 2. client_order_id on orders ─────────────────────────────────────────
    if "orders" in _existing_tables and not _col_exists("orders", "client_order_id"):
        with op.batch_alter_table("orders", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "client_order_id",
                    sa.String(length=100),
                    nullable=True,
                )
            )
            batch_op.create_unique_constraint("uq_orders_client_order_id", ["client_order_id"])
            batch_op.create_index("ix_orders_client_order_id", ["client_order_id"], unique=True)

    # ── 3. crypto_payments table ──────────────────────────────────────────────
    _tbl(
        "crypto_payments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("payment_id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("plan_id", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("network", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column("amount_crypto", sa.Float(), nullable=False),
        sa.Column("rate_usd", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column("confirmations", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("confirmations_required", sa.Integer(), nullable=False),
        sa.Column("tx_hash", sa.String(length=200), nullable=True),
        sa.Column("webhook_payload", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id", name="uq_crypto_payments_payment_id"),
    )
    _idx("ix_crypto_payments_payment_id", "crypto_payments", ["payment_id"], unique=True)
    _idx("ix_crypto_payments_user_id", "crypto_payments", ["user_id"], unique=False)
    _idx("ix_crypto_payments_status", "crypto_payments", ["status"], unique=False)
    _idx("ix_crypto_payments_created_at", "crypto_payments", ["created_at"], unique=False)

    # ── 4. outbox_events table ────────────────────────────────────────────────
    _tbl(
        "outbox_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("channel", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    _idx("ix_outbox_event_type", "outbox_events", ["event_type"], unique=False)
    _idx(
        "idx_outbox_unpublished",
        "outbox_events",
        ["published_at", "created_at"],
        unique=False,
    )

    # ── 5. config_store table ─────────────────────────────────────────────────
    _tbl(
        "config_store",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.String(length=128), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_config_store_key"),
    )
    _idx("ix_config_store_key", "config_store", ["key"], unique=True)


def downgrade() -> None:
    """Revert schema changes."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    _tables = set(inspector.get_table_names())

    def _drop_idx(name, table):
        if table not in _tables:
            return
        if name in {i["name"] for i in inspector.get_indexes(table)}:
            op.drop_index(name, table_name=table)

    def _drop_tbl(name):
        if name in _tables:
            op.drop_table(name)

    _drop_idx("ix_config_store_key", "config_store")
    _drop_tbl("config_store")

    _drop_idx("idx_outbox_unpublished", "outbox_events")
    _drop_idx("ix_outbox_event_type", "outbox_events")
    _drop_tbl("outbox_events")

    _drop_idx("ix_crypto_payments_created_at", "crypto_payments")
    _drop_idx("ix_crypto_payments_status", "crypto_payments")
    _drop_idx("ix_crypto_payments_user_id", "crypto_payments")
    _drop_idx("ix_crypto_payments_payment_id", "crypto_payments")
    _drop_tbl("crypto_payments")

    def _live_cols(table: str) -> set:
        """Return current column names, bypassing SQLAlchemy's inspector cache."""
        if bind.dialect.name == "sqlite":
            rows = bind.execute(sa.text(f"PRAGMA table_info({table})")).fetchall()
            return {row[1] for row in rows}
        rows = bind.execute(
            sa.text("SELECT column_name FROM information_schema.columns "
                    "WHERE table_name = :t"), {"t": table}
        ).fetchall()
        return {row[0] for row in rows}

    def _drop_col_sqlite(table: str, col: str) -> None:
        """Drop a column on SQLite via manual table rebuild, skipping indexes on the dropped col."""
        live = _live_cols(table)
        if col not in live:
            return
        keep_cols = [c for c in live if c != col]
        cols_sql = ", ".join(keep_cols)
        tmp = f"_tmp_{table}"
        # Reflect column types from PRAGMA
        pragma = bind.execute(sa.text(f"PRAGMA table_info({table})")).fetchall()
        col_defs = []
        pk_cols = []
        for row in pragma:
            cname, ctype, notnull, dflt, pk = row[1], row[2], row[3], row[4], row[5]
            if cname == col:
                continue
            defn = f'"{cname}" {ctype or "TEXT"}'
            if notnull:
                defn += " NOT NULL"
            if dflt is not None:
                defn += f" DEFAULT {dflt}"
            if pk:
                pk_cols.append(cname)
            col_defs.append(defn)
        if len(pk_cols) == 1:
            # Mark single PK inline
            col_defs = [
                d + " PRIMARY KEY" if d.startswith(f'"{pk_cols[0]}"') else d
                for d in col_defs
            ]
        create_sql = f'CREATE TABLE "{tmp}" ({", ".join(col_defs)})'
        bind.execute(sa.text(create_sql))
        bind.execute(sa.text(f'INSERT INTO "{tmp}" ({cols_sql}) SELECT {cols_sql} FROM "{table}"'))
        bind.execute(sa.text(f'DROP TABLE "{table}"'))
        bind.execute(sa.text(f'ALTER TABLE "{tmp}" RENAME TO "{table}"'))

    # Remove client_order_id from orders — only if the column exists.
    if "orders" in _tables and "client_order_id" in _live_cols("orders"):
        if bind.dialect.name == "sqlite":
            _drop_col_sqlite("orders", "client_order_id")
        else:
            with op.batch_alter_table("orders", schema=None) as batch_op:
                batch_op.drop_column("client_order_id")

    # Remove client_order_id from trades — only if the column exists.
    if "trades" in _tables and "client_order_id" in _live_cols("trades"):
        if bind.dialect.name == "sqlite":
            _drop_col_sqlite("trades", "client_order_id")
        else:
            with op.batch_alter_table("trades", schema=None) as batch_op:
                batch_op.drop_column("client_order_id")
