# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
# All modifications must be shared under the same license.
# No commercial use without explicit permission.
"""idempotency_and_new_tables

Revision ID: b2c3d4e5f6a7
Revises: f1a2b3c4d5e6
Create Date: 2026-06-01 00:00:00.000000

Changes
-------
1. Add UNIQUE(client_order_id) to trades and orders tables.
   Prevents duplicate order submission on broker retry (network timeout
   between API and broker).  client_order_id is the idempotency key
   generated by the trading engine before submission.

2. Create crypto_payments table — replaces in-memory _pending dict in
   api/payments.py.  Survives pod restarts; safe across replicas.

3. Create outbox_events table — transactional outbox for at-least-once
   delivery of critical compliance events (kill switch, AML block, fills).

4. Create config_store table — shared key-value config store used by
   risk settings, auto-pause config, and FOMC regime overrides.
"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f6a7"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "f1a2b3c4d5e6"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""

    # ── 1. client_order_id on trades ─────────────────────────────────────────
    # Use batch_alter_table for SQLite compatibility (ALTER COLUMN not supported).
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "client_order_id",
                sa.String(length=100),
                nullable=True,
            )
        )
        batch_op.create_unique_constraint("uq_trades_client_order_id", ["client_order_id"])
        batch_op.create_index("ix_trades_client_order_id", ["client_order_id"], unique=True)

    # ── 2. client_order_id on orders ─────────────────────────────────────────
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "client_order_id",
                sa.String(length=100),
                nullable=True,
            )
        )
        batch_op.create_unique_constraint("uq_orders_client_order_id", ["client_order_id"])
        batch_op.create_index("ix_orders_client_order_id", ["client_order_id"], unique=True)

    # ── 3. crypto_payments table ──────────────────────────────────────────────
    op.create_table(
        "crypto_payments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("payment_id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("plan_id", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("network", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column("amount_crypto", sa.Float(), nullable=False),
        sa.Column("rate_usd", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column("confirmations", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("confirmations_required", sa.Integer(), nullable=False),
        sa.Column("tx_hash", sa.String(length=200), nullable=True),
        sa.Column("webhook_payload", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id", name="uq_crypto_payments_payment_id"),
    )
    op.create_index("ix_crypto_payments_payment_id", "crypto_payments", ["payment_id"], unique=True)
    op.create_index("ix_crypto_payments_user_id", "crypto_payments", ["user_id"], unique=False)
    op.create_index("ix_crypto_payments_status", "crypto_payments", ["status"], unique=False)
    op.create_index("ix_crypto_payments_created_at", "crypto_payments", ["created_at"], unique=False)

    # ── 4. outbox_events table ────────────────────────────────────────────────
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("channel", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_outbox_event_type", "outbox_events", ["event_type"], unique=False)
    op.create_index(
        "idx_outbox_unpublished",
        "outbox_events",
        ["published_at", "created_at"],
        unique=False,
    )

    # ── 5. config_store table ─────────────────────────────────────────────────
    op.create_table(
        "config_store",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.String(length=128), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_config_store_key"),
    )
    op.create_index("ix_config_store_key", "config_store", ["key"], unique=True)


def downgrade() -> None:
    """Revert schema changes."""

    # Drop new tables
    op.drop_index("ix_config_store_key", table_name="config_store")
    op.drop_table("config_store")

    op.drop_index("idx_outbox_unpublished", table_name="outbox_events")
    op.drop_index("ix_outbox_event_type", table_name="outbox_events")
    op.drop_table("outbox_events")

    op.drop_index("ix_crypto_payments_created_at", table_name="crypto_payments")
    op.drop_index("ix_crypto_payments_status", table_name="crypto_payments")
    op.drop_index("ix_crypto_payments_user_id", table_name="crypto_payments")
    op.drop_index("ix_crypto_payments_payment_id", table_name="crypto_payments")
    op.drop_table("crypto_payments")

    # Remove client_order_id from orders
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_client_order_id")
        batch_op.drop_constraint("uq_orders_client_order_id", type_="unique")
        batch_op.drop_column("client_order_id")

    # Remove client_order_id from trades
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index("ix_trades_client_order_id")
        batch_op.drop_constraint("uq_trades_client_order_id", type_="unique")
        batch_op.drop_column("client_order_id")
