# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
# All modifications must be shared under the same license.
# No commercial use without explicit permission.
"""
core/idempotency.py
===================
Client-to-API request idempotency, so a retried order is not a second order.

The gap this closes
-------------------
Migration ``b2c3d4e5f6a7`` added ``UNIQUE(client_order_id)`` to trades and
orders, and says why in its own docstring: *"Prevents duplicate order submission
on broker retry (network timeout between API and broker). client_order_id is the
idempotency key generated by the trading engine before submission."*

That protects exactly one hop — **engine → broker**. It does nothing for the hop
in front of it. When a client POSTs an order and the response is lost (mobile
network drops, load balancer times out, user taps twice on a slow button), the
client retries; the request arrives as a brand-new order, the engine mints a
brand-new ``client_order_id``, the UNIQUE constraint sees nothing to collide
with, and a **second real position** is opened. The per-user rate limit does not
help: two distinct requests inside the window are both legitimate to it.

Retry logic and idempotency are a pair — a retrying client without an
idempotency key is a duplicate-order generator. ``security/llm_wrapper.py``
already retries upstream calls with exponential backoff, and any sane mobile
client does the same on a timeout.

Semantics
---------
Modelled on the widely-used payment-provider behaviour:

- **First request** with a key: reserved, executed, response stored.
- **Replay after completion**: the stored response is returned verbatim with
  ``Idempotency-Replayed: true``. The order is *not* placed again.
- **Replay while still in flight**: ``409 Conflict``. The first request has not
  finished, so there is no response to return and re-executing would duplicate.
- **Same key, different body**: ``422``. A key identifies one specific request;
  silently treating a different order as a replay of an earlier one would hide a
  real order from the caller. The body is fingerprinted, not stored.

Keys are namespaced per user, so one caller's key can neither collide with nor
probe another's.

Storage
-------
Redis when available, with an in-process fallback — the same pattern as
``rate_limiting/advanced.py``. The fallback is per-worker, so on a multi-worker
deployment without Redis two workers could each admit one copy; the
``UNIQUE(client_order_id)`` constraint from the migration remains the last line
of defence. A durable DB-backed store is the stronger option and is recorded as
a follow-up rather than assumed here, because it puts a write on the hot order
path.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import time
from typing import Any

logger = logging.getLogger(__name__)

_KEY_PREFIX = "hopefx:idem:"
_TTL_SECONDS = int(os.getenv("IDEMPOTENCY_TTL_SECONDS", str(24 * 3600)))

# Reserved marker for "started but not finished".
_IN_FLIGHT = "__in_flight__"

# In-process fallback: key -> (expires_at, payload)
_local: dict[str, tuple[float, str]] = {}


class IdempotencyConflict(Exception):
    """The same key is currently in flight."""


class IdempotencyKeyReused(Exception):
    """The same key was presented with a different request body."""


# Resolved once per process. This used to build a client and issue a blocking
# ping() on *every* store operation — two or three per order, none of them
# closed, all on the async order path — so each order opened several sockets the
# garbage collector had to clean up and blocked the loop on round-trips it did
# not need.
_CLIENT: Any = None
_CLIENT_RESOLVED = False


def _build_client() -> Any:
    """Construct and verify a sync Redis client, or raise."""
    from cache.redis_client import inject_redis_password

    import redis as _redis_lib

    url = os.getenv("REDIS_URL", "redis://localhost:6379/0")
    if not url.strip():
        raise RuntimeError("REDIS_URL is empty")
    url = inject_redis_password(url, os.getenv("REDIS_PASSWORD", "") or None)

    client = _redis_lib.from_url(url, decode_responses=True, socket_timeout=1.0)
    client.ping()
    return client


def _redis() -> Any:
    """The process-wide idempotency client, or None for the in-process store.

    Resolved once. A deployment without Redis falls back permanently rather
    than re-probing on every order, which is what the per-call construction
    amounted to.
    """
    global _CLIENT, _CLIENT_RESOLVED
    if _CLIENT_RESOLVED:
        return _CLIENT
    try:
        _CLIENT = _build_client()
    except Exception as exc:
        logger.debug("idempotency: Redis unavailable (%s) — using in-process store", exc)
        _CLIENT = None
    _CLIENT_RESOLVED = True
    return _CLIENT


def _fingerprint(body: Any) -> str:
    """Stable hash of the request body.

    ``sort_keys`` so an equivalent body serialised in a different field order is
    still recognised as the same request. Only the digest is kept — the order
    itself (symbol, size, prices) is never written to the idempotency store.
    """
    try:
        raw = json.dumps(body, sort_keys=True, default=str)
    except (TypeError, ValueError):
        raw = repr(body)
    return hashlib.sha256(raw.encode()).hexdigest()[:32]


def _full_key(user_id: str, key: str) -> str:
    # Hash the caller-supplied key rather than interpolating it: it reaches
    # Redis, and an attacker-chosen key should not be able to shape the keyspace.
    return f"{_KEY_PREFIX}{user_id}:{hashlib.sha256(key.encode()).hexdigest()[:32]}"


def _get(full: str) -> str | None:
    r = _redis()
    if r is not None:
        try:
            # One round trip. Calling r.get() twice to satisfy a type checker
            # would both double the latency on the order path and open a race
            # where the value changes between the two reads.
            raw = r.get(full)
            return None if raw is None else str(raw)
        except Exception as exc:
            logger.warning("idempotency: Redis read failed (%s) — falling back", exc)
    entry = _local.get(full)
    if entry is None:
        return None
    expires_at, payload = entry
    if expires_at < time.time():
        _local.pop(full, None)
        return None
    return payload


def _set_if_absent(full: str, payload: str) -> bool:
    """Reserve the key. Returns True when this caller won the race."""
    r = _redis()
    if r is not None:
        try:
            return bool(r.set(full, payload, nx=True, ex=_TTL_SECONDS))
        except Exception as exc:
            logger.warning("idempotency: Redis reserve failed (%s) — falling back", exc)
    existing = _get(full)
    if existing is not None:
        return False
    _local[full] = (time.time() + _TTL_SECONDS, payload)
    return True


def _overwrite(full: str, payload: str) -> None:
    r = _redis()
    if r is not None:
        try:
            r.set(full, payload, ex=_TTL_SECONDS)
            return
        except Exception as exc:
            logger.warning("idempotency: Redis write failed (%s) — falling back", exc)
    _local[full] = (time.time() + _TTL_SECONDS, payload)


def begin(user_id: str, key: str, body: Any) -> dict[str, Any] | None:
    """Claim *key* for this request.

    Returns:
        ``None`` when this is the first use and the caller should proceed, or the
        stored response dict when this is a replay of a completed request.

    Raises:
        IdempotencyConflict: the first request is still running.
        IdempotencyKeyReused: the key was used for a different body.
    """
    full = _full_key(user_id, key)
    fp = _fingerprint(body)
    reservation = json.dumps({"state": _IN_FLIGHT, "fp": fp})

    if _set_if_absent(full, reservation):
        return None  # first use — go ahead

    existing_raw = _get(full)
    if existing_raw is None:
        # Expired between the reserve attempt and this read. Treat as first use
        # rather than erroring: re-reserving is the safe interpretation.
        _overwrite(full, reservation)
        return None

    try:
        existing = json.loads(existing_raw)
    except (TypeError, ValueError):
        logger.warning("idempotency: corrupt entry for %s — treating as first use", full)
        _overwrite(full, reservation)
        return None

    if existing.get("fp") != fp:
        raise IdempotencyKeyReused(
            "This Idempotency-Key was already used for a different request. Use a new key for a new order."
        )

    if existing.get("state") == _IN_FLIGHT:
        raise IdempotencyConflict(
            "A request with this Idempotency-Key is still being processed. Retry shortly; do not submit a new order."
        )

    return existing.get("response")


def complete(user_id: str, key: str, body: Any, response: Any) -> None:
    """Store the finished response so a later replay returns it."""
    full = _full_key(user_id, key)
    payload = json.dumps(
        {"state": "done", "fp": _fingerprint(body), "response": response},
        default=str,
    )
    _overwrite(full, payload)


def release(user_id: str, key: str) -> None:
    """Drop the reservation after a failed request.

    A failure must not be cached as though it were a result: the caller is
    entitled to retry the same key and actually have the order attempted. Only
    successful responses are replayable.
    """
    full = _full_key(user_id, key)
    r = _redis()
    if r is not None:
        try:
            r.delete(full)
            return
        except Exception as exc:
            logger.warning("idempotency: Redis delete failed (%s) — falling back", exc)
    _local.pop(full, None)


def reset_for_testing() -> None:
    """Clear the store — both backends. Test-teardown helper.

    Clearing only ``_local`` made this a lie whenever Redis was reachable, and
    the tests that relied on it passed on a machine with no Redis and failed on
    one with it. Entries carry a 24 h TTL, so they also leaked across separate
    pytest runs. Purge the namespace wherever it actually lives.

    Scoped to ``_KEY_PREFIX`` — never ``FLUSHDB``, which would wipe rate-limit
    counters, the kill-switch latch and anything else sharing the instance.
    """
    _local.clear()
    r = _redis()
    if r is None:
        return
    try:
        # scan_iter rather than KEYS: KEYS blocks the server, and this helper may
        # run against a shared development instance.
        for key in r.scan_iter(match=f"{_KEY_PREFIX}*", count=500):
            r.delete(key)
    except Exception as exc:
        logger.warning("idempotency: could not clear Redis namespace (%s)", exc)
