/**
 * TermsAndRiskDisclosure.tsx
 * Terms of Service and Risk Disclosure — public, no auth required.
 * Routes: /terms  /risk-disclosure
 */

import React, { useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';

// ── Section data ──────────────────────────────────────────────────────────────

const TERMS_SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    body: `By accessing or using the HOPEFX AI Trading platform ("Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Platform.

These Terms constitute a legally binding agreement between you and HOPEFX ("Company", "we", "us"). We reserve the right to modify these Terms at any time. Continued use of the Platform after changes constitutes acceptance of the revised Terms.`,
  },
  {
    id: 'eligibility',
    title: '2. Eligibility',
    body: `You must be at least 18 years of age and legally permitted to trade financial instruments in your jurisdiction to use the Platform. By using the Platform you represent and warrant that you meet these requirements.

The Platform is not available to residents of jurisdictions where such services are prohibited by law. It is your responsibility to determine whether your use of the Platform is lawful in your jurisdiction.`,
  },
  {
    id: 'platform-use',
    title: '3. Platform Use',
    body: `The Platform provides AI-generated trading signals, analysis tools, and execution infrastructure for XAUUSD (Gold/USD) and related instruments. You acknowledge that:

• All signals and analysis are generated by automated systems and do not constitute personalised financial advice.
• You are solely responsible for all trading decisions made using the Platform.
• Automated trading features execute orders on your behalf based on parameters you configure. You remain responsible for monitoring and managing all automated activity.
• You must not use the Platform for any unlawful purpose, including market manipulation or insider trading.`,
  },
  {
    id: 'accounts',
    title: '4. Accounts and Security',
    body: `You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately of any unauthorised access to your account.

We implement industry-standard security measures including bcrypt password hashing, JWT authentication with refresh token rotation, two-factor authentication (TOTP), and brute-force lockout protection. However, no system is completely secure and we cannot guarantee absolute security.

You must not share your account credentials with any third party.`,
  },
  {
    id: 'subscriptions',
    title: '5. Subscriptions and Payments',
    body: `Access to certain Platform features requires a paid subscription. Subscription fees are charged in advance on a monthly or annual basis. All fees are non-refundable except as required by applicable law.

We use third-party payment processors (Stripe, Paystack, Flutterwave) to handle payments. By providing payment information you authorise us to charge the applicable fees. We do not store your full payment card details.

We reserve the right to modify subscription pricing with 30 days' notice. Continued use after a price change constitutes acceptance of the new pricing.`,
  },
  {
    id: 'intellectual-property',
    title: '6. Intellectual Property',
    body: `All Platform content, software, algorithms, models, and documentation are the exclusive property of HOPEFX and are protected by copyright, trade secret, and other intellectual property laws.

You are granted a limited, non-exclusive, non-transferable licence to use the Platform for your personal trading activities. You may not copy, modify, distribute, sell, or reverse-engineer any part of the Platform.`,
  },
  {
    id: 'limitation',
    title: '7. Limitation of Liability',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, HOPEFX SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, LOSS OF DATA, OR TRADING LOSSES, ARISING FROM YOUR USE OF THE PLATFORM.

OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM THESE TERMS OR YOUR USE OF THE PLATFORM SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.

Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of the above limitations may not apply to you.`,
  },
  {
    id: 'termination',
    title: '8. Termination',
    body: `We may suspend or terminate your account at any time for violation of these Terms, suspected fraudulent activity, or for any other reason at our sole discretion with reasonable notice where practicable.

You may terminate your account at any time by contacting support. Termination does not entitle you to a refund of any prepaid subscription fees.`,
  },
  {
    id: 'governing-law',
    title: '9. Governing Law',
    body: `These Terms are governed by and construed in accordance with applicable law. Any disputes arising from these Terms shall be resolved through binding arbitration, except where prohibited by law.

If any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.`,
  },
  {
    id: 'contact',
    title: '10. Contact',
    body: `For questions about these Terms, contact us at: legal@hopefx.ai

Last updated: April 2026`,
  },
];

const RISK_SECTIONS = [
  {
    id: 'general-risk',
    title: 'General Risk Warning',
    highlight: true,
    body: `TRADING FOREIGN EXCHANGE, COMMODITIES, AND DERIVATIVES ON MARGIN CARRIES A HIGH LEVEL OF RISK AND MAY NOT BE SUITABLE FOR ALL INVESTORS. THE HIGH DEGREE OF LEVERAGE CAN WORK AGAINST YOU AS WELL AS FOR YOU.

BEFORE DECIDING TO TRADE, YOU SHOULD CAREFULLY CONSIDER YOUR INVESTMENT OBJECTIVES, LEVEL OF EXPERIENCE, AND RISK APPETITE. THE POSSIBILITY EXISTS THAT YOU COULD SUSTAIN A LOSS OF SOME OR ALL OF YOUR INITIAL INVESTMENT AND THEREFORE YOU SHOULD NOT INVEST MONEY THAT YOU CANNOT AFFORD TO LOSE.`,
  },
  {
    id: 'ai-signals',
    title: 'AI Signal Risk',
    body: `The Platform uses machine learning models to generate trading signals. You acknowledge that:

• AI models are trained on historical data and past performance is not indicative of future results.
• Model accuracy is approximately 59.92% out-of-sample — this means approximately 40% of signals may be incorrect.
• Models can degrade over time as market conditions change (concept drift). The Platform monitors for drift but cannot guarantee detection of all regime changes.
• Signals are generated automatically without human review. You are responsible for applying your own judgement before acting on any signal.
• The Platform may experience technical failures, data feed interruptions, or model errors that affect signal quality.`,
  },
  {
    id: 'leverage-risk',
    title: 'Leverage and Margin Risk',
    body: `Trading on margin amplifies both gains and losses. A small adverse price movement can result in losses exceeding your initial deposit. You may be required to deposit additional funds at short notice to maintain your positions, or your positions may be closed automatically at a loss.

Gold (XAUUSD) can be highly volatile, particularly during geopolitical events, central bank announcements, and macroeconomic data releases. The Platform's nuclear supervisor and geopolitical risk modules attempt to detect high-risk periods, but cannot predict all market-moving events.`,
  },
  {
    id: 'execution-risk',
    title: 'Execution Risk',
    body: `Automated order execution is subject to:

• Slippage: orders may be filled at prices different from the signal price, particularly during volatile market conditions.
• Latency: network delays between signal generation and order execution can affect fill prices.
• Broker risk: the Platform connects to third-party brokers. Broker outages, margin calls, or insolvency can affect your positions.
• Technology risk: software bugs, server failures, or connectivity issues may prevent orders from being placed or cancelled.

The Platform operates in paper trading mode by default. Live trading requires explicit configuration and acceptance of additional risk.`,
  },
  {
    id: 'prop-firm-risk',
    title: 'Prop Firm Evaluation Risk',
    body: `If you use the Platform for prop firm evaluations (FTMO, Goat Funded, or similar):

• The Platform enforces drawdown limits and trading rules configured in prop_firm_mode.json, but you are solely responsible for compliance with your prop firm's rules.
• Automated trading may breach prop firm rules in unexpected market conditions. Monitor your account actively.
• Prop firm rules change periodically. Ensure your Platform configuration reflects current rules.
• The Platform's prop firm tracker provides monitoring but does not guarantee rule compliance.`,
  },
  {
    id: 'no-advice',
    title: 'No Financial Advice',
    body: `Nothing on the Platform constitutes financial advice, investment advice, trading advice, or any other form of advice. All content is provided for informational and educational purposes only.

HOPEFX is not a registered investment adviser, broker-dealer, or financial institution. We do not provide personalised investment recommendations. You should seek independent financial advice from a qualified professional before making any investment decisions.`,
  },
  {
    id: 'regulatory',
    title: 'Regulatory Considerations',
    body: `Trading financial instruments may be regulated in your jurisdiction. It is your responsibility to ensure that your trading activities comply with all applicable laws and regulations, including tax obligations on trading profits.

The Platform does not provide tax advice. Consult a qualified tax professional regarding the tax treatment of your trading activities.`,
  },
  {
    id: 'acknowledgement',
    title: 'Risk Acknowledgement',
    body: `By using the Platform you acknowledge that:

• You have read and understood this Risk Disclosure.
• You understand that trading involves substantial risk of loss.
• You are trading with funds you can afford to lose.
• You will not hold HOPEFX liable for trading losses incurred while using the Platform.
• You will monitor your automated trading activity and intervene when necessary.

If you do not understand or accept these risks, do not use the Platform.`,
  },
];

// ── Component ─────────────────────────────────────────────────────────────────

type Tab = 'terms' | 'risk';

const TermsAndRiskDisclosure: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const initialTab: Tab = location.pathname.includes('risk') ? 'risk' : 'terms';
  const [activeTab, setActiveTab] = React.useState<Tab>(initialTab);

  useEffect(() => {
    const tab: Tab = location.pathname.includes('risk') ? 'risk' : 'terms';
    setActiveTab(tab);
  }, [location.pathname]);

  const handleTabChange = (tab: Tab) => {
    setActiveTab(tab);
    navigate(tab === 'terms' ? '/terms' : '/risk-disclosure', { replace: true });
  };

  const sections = activeTab === 'terms' ? TERMS_SECTIONS : RISK_SECTIONS;

  return (
    <div style={s.page}>
      {/* Header */}
      <header style={s.header}>
        <div style={s.headerInner}>
          <button onClick={() => navigate('/')} style={s.logo}>
            HOPE<span style={{ color: '#3b82f6' }}>FX</span>
          </button>
          <nav style={s.nav}>
            <button onClick={() => navigate('/login')} style={s.navLink}>Sign In</button>
            <button onClick={() => navigate('/register')} style={s.navBtn}>Get Started</button>
          </nav>
        </div>
      </header>

      {/* Content */}
      <main style={s.main}>
        <div style={s.container}>
          {/* Tab switcher */}
          <div style={s.tabs}>
            <button
              style={{ ...s.tab, ...(activeTab === 'terms' ? s.tabActive : {}) }}
              onClick={() => handleTabChange('terms')}
            >
              Terms of Service
            </button>
            <button
              style={{ ...s.tab, ...(activeTab === 'risk' ? s.tabActive : {}) }}
              onClick={() => handleTabChange('risk')}
            >
              Risk Disclosure
            </button>
          </div>

          {/* Page title */}
          <div style={s.titleBlock}>
            <h1 style={s.title}>
              {activeTab === 'terms' ? 'Terms of Service' : 'Risk Disclosure'}
            </h1>
            <p style={s.subtitle}>
              {activeTab === 'terms'
                ? 'Please read these terms carefully before using the HOPEFX platform.'
                : 'Trading involves substantial risk. Please read this disclosure carefully.'}
            </p>
          </div>

          {/* Sections */}
          <div style={s.sections}>
            {sections.map((sec) => (
              <section
                key={sec.id}
                id={sec.id}
                style={{
                  ...s.section,
                  ...('highlight' in sec && sec.highlight ? s.sectionHighlight : {}),
                }}
              >
                <h2 style={s.sectionTitle}>{sec.title}</h2>
                <div style={s.sectionBody}>
                  {sec.body.split('\n\n').map((para, i) => (
                    <p key={i} style={s.para}>{para}</p>
                  ))}
                </div>
              </section>
            ))}
          </div>

          {/* Footer note */}
          <div style={s.footerNote}>
            <p style={s.footerText}>
              Questions? Contact us at{' '}
              <a href="mailto:legal@hopefx.ai" style={s.footerLink}>legal@hopefx.ai</a>
            </p>
            <div style={s.footerLinks}>
              <button onClick={() => handleTabChange('terms')} style={s.footerNavLink}>
                Terms of Service
              </button>
              <span style={{ color: '#334155' }}>·</span>
              <button onClick={() => handleTabChange('risk')} style={s.footerNavLink}>
                Risk Disclosure
              </button>
              <span style={{ color: '#334155' }}>·</span>
              <button onClick={() => navigate('/')} style={s.footerNavLink}>
                Back to Home
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

// ── Styles ────────────────────────────────────────────────────────────────────

const s: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: '#0f172a',
    color: '#e2e8f0',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  header: {
    borderBottom: '1px solid #1e293b',
    background: 'rgba(15,23,42,0.95)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    backdropFilter: 'blur(8px)',
  },
  headerInner: {
    maxWidth: 900,
    margin: '0 auto',
    padding: '0 24px',
    height: 60,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    fontSize: 22,
    fontWeight: 800,
    color: '#f8fafc',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    letterSpacing: -0.5,
  },
  nav: { display: 'flex', alignItems: 'center', gap: 12 },
  navLink: {
    background: 'none',
    border: 'none',
    color: '#94a3b8',
    fontSize: 14,
    cursor: 'pointer',
    padding: '6px 12px',
    borderRadius: 6,
    transition: 'color 0.2s',
  },
  navBtn: {
    background: '#3b82f6',
    border: 'none',
    color: '#fff',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    padding: '7px 16px',
    borderRadius: 8,
  },
  main: { padding: '48px 24px 80px' },
  container: { maxWidth: 900, margin: '0 auto' },
  tabs: {
    display: 'flex',
    gap: 4,
    background: '#1e293b',
    borderRadius: 10,
    padding: 4,
    marginBottom: 40,
    width: 'fit-content',
  },
  tab: {
    background: 'none',
    border: 'none',
    color: '#64748b',
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    padding: '8px 20px',
    borderRadius: 7,
    transition: 'all 0.2s',
  },
  tabActive: {
    background: '#0f172a',
    color: '#f8fafc',
    fontWeight: 600,
    boxShadow: '0 1px 4px rgba(0,0,0,0.3)',
  },
  titleBlock: { marginBottom: 40 },
  title: {
    fontSize: 32,
    fontWeight: 800,
    color: '#f8fafc',
    margin: '0 0 8px',
    letterSpacing: -0.5,
  },
  subtitle: { fontSize: 15, color: '#64748b', margin: 0 },
  sections: { display: 'flex', flexDirection: 'column', gap: 24 },
  section: {
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 12,
    padding: '28px 32px',
  },
  sectionHighlight: {
    background: 'rgba(239,68,68,0.08)',
    border: '1px solid rgba(239,68,68,0.3)',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: 700,
    color: '#f8fafc',
    margin: '0 0 16px',
  },
  sectionBody: { display: 'flex', flexDirection: 'column', gap: 12 },
  para: {
    fontSize: 14,
    lineHeight: 1.7,
    color: '#94a3b8',
    margin: 0,
    whiteSpace: 'pre-line',
  },
  footerNote: {
    marginTop: 48,
    paddingTop: 24,
    borderTop: '1px solid #1e293b',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
  },
  footerText: { fontSize: 13, color: '#475569', margin: 0 },
  footerLink: { color: '#3b82f6', textDecoration: 'none' },
  footerLinks: { display: 'flex', gap: 12, alignItems: 'center' },
  footerNavLink: {
    background: 'none',
    border: 'none',
    color: '#475569',
    fontSize: 13,
    cursor: 'pointer',
    padding: 0,
    transition: 'color 0.2s',
  },
};

export default TermsAndRiskDisclosure;
