# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
# All modifications must be shared under the same license.
# No commercial use without explicit permission.
"""
scripts/api_documentation_generator.py
======================================
Generate ``docs/API_ENDPOINTS.md`` from the routers the application actually
registers.

Why this exists
---------------
This file used to be a stub — five comment lines and ``# ... code
implementation ...`` — while ``docs/API_ENDPOINTS.md`` sat in the repo as if it
had been generated by something. It had not been regenerated in a long time:
148 of its 440 rows named paths with no route behind them (S-33). The failure
modes were all mechanical, which is exactly what a generator prevents:

  * a prefix built from the *module* name rather than the router's real one —
    ``/api/two-factor/setup`` for ``/api/2fa/setup``;
  * that same guess prepended to routes that already carried an absolute path,
    giving ``/api/advanced-trading/api/indicators``;
  * routes that had since moved, been renamed, or been deleted.

Usage
-----
    python scripts/api_documentation_generator.py            # rewrite the doc
    python scripts/api_documentation_generator.py --check    # CI: diff only

``--check`` exits 1 when the committed file differs from what the routers say,
which is what ``tests/unit/test_api_endpoint_doc_is_generated.py`` asserts.

Scope
-----
Routes are collected from ``register_routers`` under **default** feature flags,
so a flag-gated router that ships off is absent from the table. The
``/api/v1/*`` alias layer is skipped: it mirrors every path above it and would
double the table without adding an endpoint.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Final

_REPO_ROOT = Path(__file__).resolve().parents[1]
_OUTPUT = _REPO_ROOT / "docs" / "API_ENDPOINTS.md"

_HEADER = """# HOPEFX AI Trading API

**Version:** 1.0.0

Production REST API for the HOPEFX AI Trading platform.

Generated from the registered routers by
`scripts/api_documentation_generator.py` — edit that script, not this file.
Run it after adding or moving an endpoint; `--check` fails when this file and
the routers disagree.

The **Auth** column is a static read, not a live probe. `JWT` means the route
is gated by one of the three mechanisms this codebase uses: a `fastapi.security`
scheme in its dependency tree, a dependency that parses the `Authorization`
header itself (the self-healer, antivirus and `auth/` routers all do), or a
guard called inside the handler body. A route that accepts an optional token
and then decides for itself still shows `JWT`.

`None` means none of the three was found. Some of those are deliberate — health
probes, login and registration, public market data, and the payment and
TradingView webhooks, which are authenticated by HMAC signature instead — so
read a surprising `None` as a question, not a verdict.

Routes are listed under **default** feature flags. Two groups are omitted: the
`/api/v1/*` alias layer, which mirrors every path below, and routes marked
`include_in_schema=False` — compat aliases such as `POST /api/trading/order`
(the documented one is `/api/trading/orders`) and the server-rendered pages.
They are excluded from the OpenAPI schema for the same reason.

## Endpoints

| Method | Path | Auth | Summary | Tags |
|--------|------|------|---------|------|
"""

_METHOD_ORDER = {"GET": 0, "POST": 1, "PUT": 2, "PATCH": 3, "DELETE": 4}


def _build_app():
    """Register every router on a bare app, as the server does at startup.

    Every ``FEATURE_*`` override is removed for the duration so the output
    depends only on the flag *defaults*. Without that the rendered table would
    differ between a developer's shell and CI, and `--check` would fail for
    reasons that have nothing to do with the routers.
    """
    os.environ.setdefault("SECURITY_JWT_SECRET", "api-doc-generator-placeholder-secret-32c")
    os.environ.setdefault("APP_ENV", "test")

    from fastapi import FastAPI

    from config.feature_flags import FeatureFlags
    from core.router_registry import register_routers

    overrides = {k: v for k, v in os.environ.items() if k.startswith("FEATURE_")}
    for key in overrides:
        del os.environ[key]
    try:
        app = FastAPI()
        register_routers(app, FeatureFlags())
        return app
    finally:
        os.environ.update(overrides)


# Auth helpers whose *call* marks a route as gated. Deliberately shaped as
# suffix patterns rather than a fixed list of names: this repo has at least
# eight private variants — `_require_admin`, `_require_superadmin`,
# `_heal_require_admin`, `_av_require_auth`, `_get_current_user_id`, … — and
# an unlisted one makes the column understate an endpoint's protection, which
# is the failure the column exists to prevent (S-31).
_AUTH_CALL = re.compile(
    r"\b("
    r"\w*decode_access_token"
    r"|\w*decode_token"
    r"|\w*verify_token"
    r"|\w*get_current_user"
    r"|\w*require_(?:auth|admin|superadmin|role|plan|user)"
    r"|_assert_self_or_operator"
    r")\s*\("
)


def _source_of(callable_obj) -> str:
    """Best-effort source text; builtins and C callables simply have none."""
    import inspect

    try:
        return inspect.getsource(callable_obj)
    except (OSError, TypeError):
        return ""


def _declares_auth(dependant, endpoint=None, _depth: int = 0) -> bool:
    """True when the route is gated, by declaration or by an in-handler check.

    Three signals, because this codebase gates routes in three ways:

    1. a `fastapi.security` scheme anywhere in the dependency tree — the
       `Depends(get_current_user)` / `require_role` / `require_plan` path;
    2. a dependency function that parses the `Authorization` header itself and
       raises — `security/self_healer.py::_heal_require_admin`,
       `security/antivirus.py::_av_require_auth`,
       `auth/router.py::_get_current_user_id`. These declare no scheme, so
       signal 1 alone reported the entire self-healer, antivirus and 2FA
       surface as unauthenticated;
    3. the handler body calling a guard directly — `_require_admin(request)` in
       `api/portfolio_allocator.py` and the antivirus router. FastAPI records
       nothing about those at all.

    Signals 2 and 3 are a static source match, so this can over-report if a
    handler merely mentions a guard without depending on its result. That
    direction is the safe one: a route wrongly shown as gated invites a second
    look, while one wrongly shown as open invites removing a gate that was
    doing its job.

    Depth is capped as a cheap guard against a pathological dependency graph.
    """
    from fastapi.security.base import SecurityBase

    if _depth > 10:
        return False
    if endpoint is not None and _AUTH_CALL.search(_source_of(endpoint)):
        return True
    for dep in dependant.dependencies:
        if isinstance(dep.call, SecurityBase):
            return True
        if dep.call is not None and _AUTH_CALL.search(_source_of(dep.call)):
            return True
        if _declares_auth(dep, None, _depth + 1):
            return True
    return False


#: A summary that would break the table or bury the row is not a summary.
_SUMMARY_MAX_CHARS: Final = 110


def _summary_for(route: object) -> str:
    """What this endpoint does, in one line, from whatever the code already says.

    The column was rendered empty for every one of 1,127 routes because only
    ``route.summary`` was read, and only 337 routes set it explicitly. Another
    809 carry an endpoint docstring, so 849 — three quarters — could say what
    they do and said nothing.

    Order is deliberate: an explicit ``summary=`` is a decision somebody made
    about how this endpoint should be described, and a docstring is what was
    written for the next programmer. The decision wins where both exist.

    A row with neither stays EMPTY rather than being filled with the function
    name dressed up as prose. An invented summary is worse than a blank one: a
    blank cell reads as "nobody wrote this down", and `create_user_v2` rendered
    as "Create user v2" reads as documentation.
    """
    explicit = (getattr(route, "summary", None) or "").strip()
    if explicit:
        return _one_line(explicit)

    endpoint = getattr(route, "endpoint", None)
    doc = (getattr(endpoint, "__doc__", None) or "").strip()
    if not doc:
        return ""
    return _one_line(doc.split("\n", 1)[0])


def _one_line(text: str) -> str:
    """One table-safe line: no pipes, no newlines, bounded length."""
    flat = " ".join(text.replace("|", "\\|").split())
    if len(flat) <= _SUMMARY_MAX_CHARS:
        return flat
    return flat[: _SUMMARY_MAX_CHARS - 1].rstrip() + "\u2026"


def _rows() -> list[tuple[str, str, str, str, str]]:
    """(method, path, auth, summary, tags) for every documented route."""
    from core.router_registry import iter_api_routes

    collected: dict[tuple[str, str], tuple[str, str, str, str, str]] = {}
    for route in iter_api_routes(_build_app().routes):
        if route.path.startswith("/api/v1/"):
            continue
        if not route.include_in_schema:
            continue
        auth = "JWT" if _declares_auth(route.dependant, route.endpoint) else "None"
        summary = _summary_for(route)
        tags = ", ".join(str(t) for t in (route.tags or []))
        for method in route.methods:
            if method in ("HEAD", "OPTIONS"):
                continue
            collected[(route.path, method)] = (method, route.path, auth, summary, tags)

    return sorted(
        collected.values(),
        key=lambda row: (row[1], _METHOD_ORDER.get(row[0], 9)),
    )


def render() -> str:
    lines = [_HEADER]
    for method, path, auth, summary, tags in _rows():
        lines.append(f"| `{method}` | `{path}` | {auth} | {summary} | {tags} |\n")
    return "".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed doc differs from the routers (no write)",
    )
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = _OUTPUT.read_text(encoding="utf-8") if _OUTPUT.exists() else ""
        if current != rendered:
            print(f"{_OUTPUT.relative_to(_REPO_ROOT)} is out of date — run: python {Path(__file__).name}")
            return 1
        print(f"{_OUTPUT.relative_to(_REPO_ROOT)} is up to date.")
        return 0

    _OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {_OUTPUT.relative_to(_REPO_ROOT)} ({len(_rows())} endpoints).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
