#!/usr/bin/env python3
# HOPEFX-AI-TRADING
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
"""
scripts/bootstrap_dev.py
========================
One-shot dev bootstrap: generates .env (if missing) and seeds the admin user.

Run once before starting the server:
    python scripts/bootstrap_dev.py

Or let app.py call it automatically when APP_ENV=development and .env is absent.

What it does
------------
1. Generates a .env file with secure random secrets (SECURITY_JWT_SECRET,
   CONFIG_ENCRYPTION_KEY) and SQLite DATABASE_URL so the app starts without
   any manual configuration.
2. Creates the SQLite database schema (tables).
3. Seeds an admin user (admin@hopefx.io / HopeFX-Admin-2025!) so you can
   log in immediately at /login.

Safe to run multiple times — skips steps that are already done.
"""

from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

ENV_PATH = ROOT / ".env"
DB_PATH = ROOT / "hopefx.db"

# ── Default dev credentials (printed to console on first run) ─────────────────
DEFAULT_ADMIN_EMAIL = "admin@hopefx.io"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_PASSWORD = "HopeFX-Admin-2025!"


def _generate_env() -> bool:
    """Write .env with generated secrets. Returns True if file was created."""
    if ENV_PATH.exists():
        return False

    jwt_secret = secrets.token_urlsafe(48)
    enc_key = secrets.token_urlsafe(48)
    config_salt = secrets.token_hex(16)

    content = f"""\
# Auto-generated by scripts/bootstrap_dev.py — DO NOT COMMIT
# Regenerate: python scripts/bootstrap_dev.py

APP_ENV=development
API_HOST=0.0.0.0
API_PORT=8000

# ── Secrets (auto-generated) ──────────────────────────────────────────────────
SECURITY_JWT_SECRET={jwt_secret}
CONFIG_ENCRYPTION_KEY={enc_key}
CONFIG_SALT={config_salt}

# ── Database (SQLite for dev) ─────────────────────────────────────────────────
DATABASE_URL=sqlite:///{DB_PATH}

# ── Redis (optional in dev — app degrades gracefully without it) ──────────────
REDIS_URL=redis://localhost:6379/0

# ── Broker (paper trading — no real credentials needed) ──────────────────────
BROKER_TYPE=paper

# ── Sentry (disabled in dev) ──────────────────────────────────────────────────
# SENTRY_DSN=
"""
    ENV_PATH.write_text(content, encoding="utf-8")
    return True


def _seed_admin() -> None:
    """Create DB schema and seed admin user if not present."""
    # Set minimal env so imports work
    os.environ.setdefault("APP_ENV", "development")
    os.environ.setdefault("DATABASE_URL", f"sqlite:///{DB_PATH}")

    # Load the generated .env so SECURITY_JWT_SECRET is available
    try:
        from dotenv import load_dotenv

        load_dotenv(ENV_PATH, override=False)
    except ImportError:
        # Manually load key=value pairs
        for line in ENV_PATH.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip())

    # Suppress startup validator during seeding
    os.environ.setdefault("SECURITY_JWT_SECRET", secrets.token_urlsafe(48))

    from database.models import Base
    from database.user_models import User, UserRole, UserStatus
    from auth.service import hash_password
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    import uuid

    db_url = os.environ["DATABASE_URL"]
    connect_args = {"check_same_thread": False} if db_url.startswith("sqlite") else {}
    engine = create_engine(db_url, connect_args=connect_args)
    Base.metadata.create_all(engine)

    Session = sessionmaker(bind=engine)
    session = Session()
    try:
        existing = session.query(User).filter_by(email=DEFAULT_ADMIN_EMAIL).first()
        if existing:
            return  # already seeded

        user = User(
            id=str(uuid.uuid4()),
            email=DEFAULT_ADMIN_EMAIL,
            username=DEFAULT_ADMIN_USERNAME,
            hashed_password=hash_password(DEFAULT_ADMIN_PASSWORD),
            role=UserRole.ADMIN.value,
            status=UserStatus.ACTIVE.value,
            is_email_verified=True,
        )
        session.add(user)
        session.commit()
    finally:
        session.close()


def bootstrap(verbose: bool = True) -> None:
    created = _generate_env()

    if created and verbose:
        print("\n" + "─" * 58)
        print("  HOPEFX Dev Bootstrap")
        print("─" * 58)
        print(f"  ✅  Generated .env  →  {ENV_PATH}")

    try:
        _seed_admin()
        if verbose:
            if created:
                print("  ✅  Admin user seeded")
                print(f"      Email    : {DEFAULT_ADMIN_EMAIL}")
                print(f"      Username : {DEFAULT_ADMIN_USERNAME}")
                print(f"      Password : {DEFAULT_ADMIN_PASSWORD}")
                print("─" * 58)
                print("  Start the server:  python app.py")
                print("  Login at:          http://localhost:8000/login")
                print("─" * 58 + "\n")
    except Exception as exc:
        if verbose:
            print(f"  ⚠️  Admin seed skipped: {exc}")


if __name__ == "__main__":
    bootstrap(verbose=True)
