#!/usr/bin/env python3
# Copyright (c) 2025-2026
# HOPEFX-AI-TRADING
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
"""
scripts/bootstrap_dev.py
========================
One-shot dev bootstrap: generates .env with ALL secrets from .env.example
and seeds the three default users (superadmin / admin / trader).

Run once before starting the server:
    python scripts/bootstrap_dev.py

Or let app.py call it automatically when APP_ENV=development and .env is absent.

What it does (idempotent — safe to re-run)
------------------------------------------
1. Generates .env with cryptographically-random values for every secret,
   token, password, and key found in .env.example.
2. Creates the SQLite database schema.
3. Seeds three users:
     superadmin@hopefx.io  ->  role=superadmin  ->  /superadmin
     admin@hopefx.io       ->  role=admin        ->  /admin
     trader@hopefx.io      ->  role=trader        ->  /dashboard
"""

from __future__ import annotations

import os
import platform
import secrets
import sys
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

ENV_PATH = ROOT / ".env"
DB_PATH = ROOT / "hopefx.db"

_DB_URL_PATH = DB_PATH.as_posix() if platform.system() == "Windows" else str(DB_PATH)

# ── Seed user config ──────────────────────────────────────────────────────────
DEFAULT_SUPERADMIN_EMAIL = "superadmin@hopefx.io"
DEFAULT_SUPERADMIN_USERNAME = "superadmin"
_SUPERADMIN_PASSWORD_KEY = "BOOTSTRAP_SUPERADMIN_PASSWORD"  # nosec B105

DEFAULT_ADMIN_EMAIL = "admin@hopefx.io"
DEFAULT_ADMIN_USERNAME = "admin"
_ADMIN_PASSWORD_KEY = "BOOTSTRAP_ADMIN_PASSWORD"  # nosec B105

DEFAULT_TRADER_EMAIL = "trader@hopefx.io"
DEFAULT_TRADER_USERNAME = "trader"
_TRADER_PASSWORD_KEY = "BOOTSTRAP_TRADER_PASSWORD"  # nosec B105


# ── Secret generators ─────────────────────────────────────────────────────────
def _hex(n: int = 32) -> str:
    return secrets.token_hex(n)


def _urlsafe(n: int = 32) -> str:
    return secrets.token_urlsafe(n)


def _password(n: int = 16) -> str:
    return secrets.token_urlsafe(n)


def _generate_env() -> bool:
    """
    Write .env with generated secrets for every CHANGE_ME / blank secret
    found in .env.example.  Returns True if the file was created.
    """
    if ENV_PATH.exists():
        return False

    superadmin_pw = _password(16)
    admin_pw = _password(16)
    trader_pw = _password(16)

    content = f"""\
# Auto-generated by scripts/bootstrap_dev.py -- DO NOT COMMIT
# Regenerate: delete this file and run:  python scripts/bootstrap_dev.py

# -- Application ---------------------------------------------------------------
APP_ENV=development
APP_BASE_URL=http://localhost:8000
HOPEFX_DOMAIN=localhost

API_HOST=0.0.0.0
API_PORT=8000

# -- Security ------------------------------------------------------------------
SECURITY_JWT_SECRET={_hex(32)}
CONFIG_ENCRYPTION_KEY={_urlsafe(36)}
HOPEFX_KILL_SWITCH_TOKEN={_hex(32)}
CONFIG_SALT={_hex(16)}
SECRET_KEY={_hex(32)}
JWT_SECRET={_hex(32)}
JWT_SECRET_KEY={_hex(32)}
LICENSE_SECRET={_hex(32)}
HOPEFX_ENCRYPTION_KEY={_urlsafe(32)}
HOPEFX_MASTER_KEY={_urlsafe(32)}
WHITELABEL_KEY_HASH_SECRET={_hex(32)}
AUTH_TOKEN={_urlsafe(24)}
API_KEY={_urlsafe(24)}

ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7
AUTH_RATE_LIMIT_REQUESTS=10
AUTH_RATE_LIMIT_WINDOW_SECONDS=60

# -- Bootstrap credentials (generated once -- never commit this file) ----------
# superadmin: full platform control -- logs in at /superadmin
{_SUPERADMIN_PASSWORD_KEY}={superadmin_pw}
# admin: operational admin -- logs in at /admin
{_ADMIN_PASSWORD_KEY}={admin_pw}
# trader: order placement and position management -- logs in at /dashboard
{_TRADER_PASSWORD_KEY}={trader_pw}

# -- Database (SQLite for dev) -------------------------------------------------
DATABASE_URL=sqlite:///{_DB_URL_PATH}
POSTGRES_USER=hopefx
POSTGRES_PASSWORD={_password(20)}
POSTGRES_DB=hopefx
DB_HOST=localhost
DB_PASSWORD={_password(20)}

# -- Redis (optional in dev -- app degrades gracefully without it) -------------
REDIS_URL=redis://localhost:6379/0
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD={_password(20)}
IS_FORCE_TLS=false
REDIS_FORCE_TLS=false
REDIS_TLS_SKIP_VERIFY=false
REDIS_TLS_CA_CERT=
REDIS_TLS_CLIENT_CERT=
REDIS_TLS_CLIENT_KEY=

# -- CORS ----------------------------------------------------------------------
ALLOWED_ORIGINS=http://localhost:5173,http://localhost:8000

# -- Broker (paper trading -- no real credentials needed) ---------------------
BROKER_TYPE=paper
REQUIRE_EMAIL_VERIFICATION=false

# -- Risk management defaults -------------------------------------------------
RISK_MAX_POSITION_SIZE_PCT=0.02
RISK_MAX_DRAWDOWN_PCT=0.10
RISK_MAX_DAILY_LOSS_PCT=0.05
INITIAL_BALANCE=100000

# -- Signal engine ------------------------------------------------------------
SIGNAL_ENGINE_AUTO_TRADE=false
ML_MIN_TRADE_PROB=0.58

# -- News blackout window (minutes around high-impact events) -----------------
NEWS_BLACKOUT_BEFORE_MIN=5
NEWS_BLACKOUT_AFTER_MIN=5

# -- FIX protocol (leave blank for paper trading) -----------------------------
FIX_CONFIG_FILE=fix.cfg
FIX_SENDER_COMP_ID=
FIX_TARGET_COMP_ID=

# -- OANDA --------------------------------------------------------------------
OANDA_API_KEY=
OANDA_ACCOUNT_ID=
OANDA_ENVIRONMENT=practice
OANDA_ACCESS_TOKEN=
OANDA_API_SECRET=
OANDA_API_TOKEN=
OANDA_MAX_RETRIES=3
OANDA_PAPER_FILL_COUNT=0
OANDA_PAPER_STAMP_PATH=data/oanda_paper_stamp.json
OANDA_PRACTICE=true
OANDA_REGION=us
OANDA_RETRY_BACKOFF_S=2.0
OANDA_TIMEOUT_S=10
OANDA_ENV=practice
OANDA_INSTRUMENTS=XAU_USD,EUR_USD,GBP_USD,USD_JPY
BROKER_OANDA_TOKEN=

# -- MT5 ----------------------------------------------------------------------
MT5_LOGIN=
MT5_PASSWORD=
MT5_SERVER=
MT5_PATH=
MT5_SIGNAL_DIR=data/mt5_signals

# -- cTrader ------------------------------------------------------------------
CTRADER_CLIENT_ID=
CTRADER_CLIENT_SECRET=
CTRADER_ACCOUNT_ID=

# -- Bybit --------------------------------------------------------------------
BYBIT_API_KEY={_urlsafe(20)}
BYBIT_API_SECRET={_urlsafe(32)}
BYBIT_SANDBOX=true
BYBIT_DEFAULT_TYPE=linear

# -- IBKR ---------------------------------------------------------------------
IBKR_FIX_PASSWORD={_password(16)}

# -- CME FIX ------------------------------------------------------------------
CME_ENABLED=false
CME_FIX_HOST=127.0.0.1
CME_FIX_PORT=9876
CME_FIX_SENDER_ID=HOPEFX
CME_FIX_TARGET_ID=CME
CME_FIX_USERNAME=
CME_FIX_PASSWORD=
CME_FIX_CONFIG_FILE=fix.cfg
CME_ACCOUNT=
CME_IBKR_FALLBACK=true
CME_PAPER_FALLBACK=true
CME_DEFAULT_CONTRACTS=1
CME_LATENCY_WARN_MS=50
FIX_PASSWORD={_password(16)}

# -- Market data APIs (leave blank -- app uses paper/fallback without them) ---
FINNHUB_API_KEY=
TWELVE_API_KEY=
POLYGON_API_KEY=
ALPHA_VANTAGE_KEY=
ALPHA_VANTAGE_API_KEY=
FMP_API_KEY=
FRED_API_KEY=
FRED_CACHE_PATH=data/fred_cache/
NEWSDATA_IO_KEY=
NEWSAPI_ORG_KEY=
NEWSAPI_AI_KEY=
REFINITIV_API_KEY=
REFINITIV_API_SECRET=
# World Monitor — open-source geopolitical map dashboard (https://worldmonitor.app)
# GitHub: https://github.com/koala73/worldmonitor
#
# World Monitor public REST API — no key required for web access.
# Reference: https://worldmonitor.app/docs/api-reference
# Set WORLDMONITOR_API_URL only when running a self-hosted instance.
WORLDMONITOR_API_URL=
EXCHANGE_RATE_API_KEY=
FIXER_API_KEY=

# -- Metals / Commodity APIs --------------------------------------------------
GOLDAPI_IO_KEY=
METALS_DEV_KEY=
METALS_API_KEY=
METALPRICEAPI_KEY=
COMMODITY_PRICE_API_KEY=

# -- Geopolitical / Threat Intel ----------------------------------------------
FLASHPOINT_API_KEY=
FLASHPOINT_API_URL=https://api.flashpoint.io/v1/iocs

# -- AI / LLM -----------------------------------------------------------------
OPENAI_API_KEY=
OPENAI_MODEL=o4-mini
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-sonnet-4-5

# -- Email --------------------------------------------------------------------
SENDGRID_API_KEY=
SENDGRID_WEBHOOK_PUBLIC_KEY=
SENDGRID_WEBHOOK_VERIFY=false
EMAIL_FROM=noreply@hopefx.io
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_TLS=true
SMTP_FROM=noreply@hopefx.ai
SMTP_TO=
SMTP_USERNAME=
SMTP_USE_TLS=true

# -- Payments -----------------------------------------------------------------
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PUBLISHABLE_KEY=
STRIPE_PRICE_PROFESSIONAL=price_{_urlsafe(12)}
STRIPE_PRICE_ELITE_MONTHLY=price_{_urlsafe(12)}
STRIPE_PRICE_ELITE_ANNUAL=price_{_urlsafe(12)}
STRIPE_PRICE_ENTERPRISE=price_{_urlsafe(12)}
STRIPE_PRICE_ENTERPRISE_ANNUAL=price_{_urlsafe(12)}
STRIPE_PRICE_ENTERPRISE_MONTHLY=price_{_urlsafe(12)}
STRIPE_PRICE_PROFESSIONAL_ANNUAL=price_{_urlsafe(12)}
STRIPE_PRICE_PROFESSIONAL_MONTHLY=price_{_urlsafe(12)}
STRIPE_PRICE_STARTER_ANNUAL=price_{_urlsafe(12)}
STRIPE_PRICE_STARTER_MONTHLY=price_{_urlsafe(12)}
CRYPTO_WEBHOOK_SECRET={_hex(32)}
CRYPTO_WEBHOOK_VERIFY=true
FLUTTERWAVE_SECRET_KEY=
FLUTTERWAVE_PUBLIC_KEY=
FLUTTERWAVE_WEBHOOK_HASH=
PAYSTACK_SECRET_KEY=

# -- Monitoring / Observability -----------------------------------------------
SENTRY_DSN=
SENTRY_ENVIRONMENT=development
SENTRY_RELEASE=
SENTRY_TRACES_SAMPLE_RATE=0.1
SENTRY_PROFILES_SAMPLE_RATE=0.1
GRAFANA_ADMIN_PASSWORD={_password(16)}

# -- Alerting -----------------------------------------------------------------
ALERTMANAGER_TELEGRAM_BOT_TOKEN=
ALERTMANAGER_TELEGRAM_CHAT_ID=0
ALERTMANAGER_SMTP_FROM=alerts@hopefx.io
ALERTMANAGER_SMTP_TO=
ALERTMANAGER_SMTP_HOST=localhost:587
ALERTMANAGER_SMTP_USERNAME=
ALERTMANAGER_SMTP_PASSWORD=
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
TELEGRAM_ALLOWED_IDS=

# -- Prop Firm APIs -----------------------------------------------------------
FTMO_API_KEY=
FTMO_API_SECRET=
FTMO_SECRET_KEY=
MYFOREXFUNDS_API_KEY=
TOPSTEP_API_KEY=

# -- Crypto custody -----------------------------------------------------------
BINANCE_API_KEY=
BINANCE_SECRET=
BITGO_ACCESS_TOKEN=
FIREBLOCKS_API_KEY=
FIREBLOCKS_API_SECRET=
BLOCKCYPHER_TOKEN=
BITCOIN_WIF_PRIVATE_KEY=

# -- KYC / Compliance ---------------------------------------------------------
ONFIDO_API_TOKEN=
ONFIDO_WEBHOOK_TOKEN=
SUMSUB_APP_TOKEN=
SUMSUB_SECRET_KEY=
SUMSUB_WEBHOOK_SECRET=
DTCC_GTR_API_KEY=
ESMA_API_KEY=

# -- Webhooks -----------------------------------------------------------------
TRADINGVIEW_WEBHOOK_SECRET={_hex(32)}

# -- Cloud / Infrastructure ---------------------------------------------------
VAULT_TOKEN=
AZURE_CLIENT_SECRET=
GITHUB_TOKEN=
FIREBASE_SERVER_KEY=
CAT_API_KEY=

# -- Lineage / Audit ----------------------------------------------------------
LINEAGE_DB_URL=

# -- Frontend (Vite) ----------------------------------------------------------
VITE_API_URL=
VITE_WS_URL=
VITE_NUCLEAR_WS_URL=

# -- Kill switch --------------------------------------------------------------
HOPEFX_KILL_SWITCH=0
"""

    ENV_PATH.write_text(content, encoding="utf-8")
    try:
        ENV_PATH.chmod(0o600)
    except (NotImplementedError, OSError) as exc:
        # chmod is not supported on Windows (NotImplementedError) and may fail
        # on some network filesystems (OSError). The file is still written; the
        # permission restriction is best-effort on non-POSIX systems.
        logger.debug(".env chmod(0o600) skipped: %s", exc)
    return True


def _load_env() -> None:
    """Load .env into os.environ (idempotent)."""
    os.environ.setdefault("APP_ENV", "development")
    os.environ.setdefault("DATABASE_URL", f"sqlite:///{_DB_URL_PATH}")
    try:
        from dotenv import load_dotenv

        load_dotenv(ENV_PATH, override=False)
    except ImportError:
        for _line in ENV_PATH.read_text().splitlines():
            line = _line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip())
    os.environ.setdefault("SECURITY_JWT_SECRET", secrets.token_urlsafe(48))


def _make_engine():
    from sqlalchemy import create_engine

    db_url = os.environ.get("DATABASE_URL", f"sqlite:///{DB_PATH}")
    connect_args = {"check_same_thread": False} if db_url.startswith("sqlite") else {}
    return create_engine(db_url, connect_args=connect_args)


def _seed_user(email: str, username: str, password: str, role_value: str) -> None:
    """Upsert a single user. Creates tables if needed."""
    import uuid
    from sqlalchemy.orm import sessionmaker
    from auth.service import hash_password
    from database.models import Base
    from database.user_models import User, UserStatus

    engine = _make_engine()
    Base.metadata.create_all(engine, checkfirst=True)
    Session = sessionmaker(bind=engine)
    session = Session()
    try:
        existing = session.query(User).filter_by(email=email).first()
        if existing:
            changed = False
            if existing.role != role_value:
                existing.role = role_value
                changed = True
            # Resync password in case .env was regenerated with a new value
            from auth.service import verify_password as _vp
            if not _vp(password, existing.hashed_password):
                existing.hashed_password = hash_password(password)
                existing.status = "active"
                existing.is_email_verified = True
                changed = True
            if changed:
                session.commit()
            return
        user = User(
            id=str(uuid.uuid4()),
            email=email,
            username=username,
            hashed_password=hash_password(password),
            role=role_value,
            status=UserStatus.ACTIVE.value,
            is_email_verified=True,
        )
        session.add(user)
        session.commit()
    finally:
        session.close()


def _seed_superadmin() -> str:
    _load_env()
    from database.user_models import UserRole

    password = os.environ.get(_SUPERADMIN_PASSWORD_KEY, "").strip()
    if not password:
        raise RuntimeError(f"{_SUPERADMIN_PASSWORD_KEY} not set in .env")
    _seed_user(DEFAULT_SUPERADMIN_EMAIL, DEFAULT_SUPERADMIN_USERNAME, password, UserRole.SUPERADMIN.value)
    return password


def _seed_admin() -> str:
    _load_env()
    from database.user_models import UserRole

    password = os.environ.get(_ADMIN_PASSWORD_KEY, "").strip()
    if not password:
        raise RuntimeError(f"{_ADMIN_PASSWORD_KEY} not set in .env")
    _seed_user(DEFAULT_ADMIN_EMAIL, DEFAULT_ADMIN_USERNAME, password, UserRole.ADMIN.value)
    return password


def _seed_trader() -> str:
    _load_env()
    from database.user_models import UserRole

    password = os.environ.get(_TRADER_PASSWORD_KEY, "").strip()
    if not password:
        raise RuntimeError(f"{_TRADER_PASSWORD_KEY} not set in .env")
    _seed_user(DEFAULT_TRADER_EMAIL, DEFAULT_TRADER_USERNAME, password, UserRole.TRADER.value)
    return password


def build_frontend(verbose: bool = True) -> bool:
    """Build the React frontend into static/ if not already built.

    Idempotent — skips the build when static/index.html already exists.
    Returns True if the build ran (or was already present), False on failure.
    """
    import shutil
    import subprocess

    static_index = ROOT / "static" / "index.html"
    frontend_dir = ROOT / "frontend"

    if static_index.exists():
        if verbose:
            logger.info("  Frontend already built  ->  static/")
        return True

    if not (frontend_dir / "package.json").exists():
        if verbose:
            logger.warning("  frontend/package.json not found — skipping frontend build")
        return False

    npm = shutil.which("npm")
    if not npm:
        if verbose:
            logger.warning("  npm not found — skipping frontend build (install Node.js 20+)")
        return False

    if verbose:
        logger.info("  Building frontend (npm install && npm run build)...")

    try:
        # Install deps only if node_modules is absent or package-lock changed
        node_modules = frontend_dir / "node_modules"
        if not node_modules.exists():
            subprocess.run(
                [npm, "install", "--silent"],
                cwd=str(frontend_dir),
                check=True,
                timeout=300,
            )

        subprocess.run(
            [npm, "run", "build"],
            cwd=str(frontend_dir),
            check=True,
            timeout=300,
        )

        if verbose:
            logger.info("  Frontend built  ->  static/")
        return True

    except subprocess.CalledProcessError as exc:
        if verbose:
            logger.warning("  Frontend build failed (non-fatal): %s", exc)
        return False
    except subprocess.TimeoutExpired:
        if verbose:
            logger.warning("  Frontend build timed out after 5 minutes")
        return False


def bootstrap(verbose: bool = True) -> None:
    created = _generate_env()

    if verbose:
        logger.info("\n" + "-" * 62)
        logger.info("  HOPEFX Dev Bootstrap")
        logger.info("-" * 62)
        if created:
            logger.info(f"  Generated .env  ->  {ENV_PATH}")
        else:
            logger.info(f"  .env already exists  ->  {ENV_PATH}")

    for seed_fn, label, email, _username, redirect in [
        (_seed_superadmin, "Superadmin", DEFAULT_SUPERADMIN_EMAIL, DEFAULT_SUPERADMIN_USERNAME, "/superadmin"),
        (_seed_admin, "Admin", DEFAULT_ADMIN_EMAIL, DEFAULT_ADMIN_USERNAME, "/admin"),
        (_seed_trader, "Trader", DEFAULT_TRADER_EMAIL, DEFAULT_TRADER_USERNAME, "/dashboard"),
    ]:
        try:
            seed_fn()
            if verbose:
                logger.info(f"  {label} seeded  ({email}  ->  {redirect})")
        except Exception as exc:  # pylint: disable=broad-exception-caught
            if verbose:
                logger.warning(f"  {label} seed skipped: {exc}")

    build_frontend(verbose=verbose)

    if verbose:
        logger.info("-" * 62)
        logger.info("  Start the server:  python app.py")
        logger.info("  Login at:          http://localhost:8000/login")
        logger.info("-" * 62 + "\n")


if __name__ == "__main__":
    bootstrap(verbose=True)
