#!/usr/bin/env python3
# Copyright (c) 2025-2026
# HOPEFX-AI-TRADING
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
"""
scripts/bootstrap_dev.py
========================
One-shot dev bootstrap: generates .env (if missing) and seeds the admin user.

Run once before starting the server:
    python scripts/bootstrap_dev.py

Or let app.py call it automatically when APP_ENV=development and .env is absent.

What it does
------------
1. Generates a .env file with secure random secrets (SECURITY_JWT_SECRET,
   CONFIG_ENCRYPTION_KEY) and SQLite DATABASE_URL so the app starts without
   any manual configuration.
2. Creates the SQLite database schema (tables).
3. Seeds an admin user (admin@hopefx.io / HopeFX-Admin-2025!) so you can
   log in immediately at /login.

Safe to run multiple times — skips steps that are already done.
"""

from __future__ import annotations

import os
import platform
import secrets
import sys
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

ENV_PATH = ROOT / ".env"
DB_PATH = ROOT / "hopefx.db"

# SQLite URL must use forward slashes on all platforms.
# On Windows, Path gives backslashes — convert explicitly.
_DB_URL_PATH = DB_PATH.as_posix() if platform.system() == "Windows" else str(DB_PATH)

# ── Default dev credentials ───────────────────────────────────────────────────
# superadmin — full platform control (ML, billing, infrastructure, kill switch)
DEFAULT_SUPERADMIN_EMAIL    = "superadmin@hopefx.io"
DEFAULT_SUPERADMIN_USERNAME = "superadmin"
_SUPERADMIN_PASSWORD_KEY    = "BOOTSTRAP_SUPERADMIN_PASSWORD"  # nosec B105

# admin — operational admin (user management, reports, settings)
DEFAULT_ADMIN_EMAIL    = "admin@hopefx.io"
DEFAULT_ADMIN_USERNAME = "admin"
_ADMIN_PASSWORD_KEY    = "BOOTSTRAP_ADMIN_PASSWORD"  # nosec B105

# trader — order placement and position management
DEFAULT_TRADER_EMAIL    = "trader@hopefx.io"
DEFAULT_TRADER_USERNAME = "trader"
_TRADER_PASSWORD_KEY    = "BOOTSTRAP_TRADER_PASSWORD"  # nosec B105


def _generate_env() -> bool:
    """Write .env with generated secrets. Returns True if file was created."""
    if ENV_PATH.exists():
        return False

    jwt_secret        = secrets.token_urlsafe(48)
    enc_key           = secrets.token_urlsafe(48)
    config_salt       = secrets.token_hex(16)
    superadmin_password = secrets.token_urlsafe(16)
    admin_password    = secrets.token_urlsafe(16)
    trader_password   = secrets.token_urlsafe(16)

    content = f"""\
# Auto-generated by scripts/bootstrap_dev.py — DO NOT COMMIT
# Regenerate: python scripts/bootstrap_dev.py

APP_ENV=development
API_HOST=0.0.0.0
API_PORT=8000

# ── Secrets (auto-generated) ──────────────────────────────────────────────────
SECURITY_JWT_SECRET={jwt_secret}
CONFIG_ENCRYPTION_KEY={enc_key}
CONFIG_SALT={config_salt}

# ── Bootstrap credentials (generated once — never commit this file) ───────────
# superadmin: full platform control — logs in at /superadmin
{_SUPERADMIN_PASSWORD_KEY}={superadmin_password}
# admin: operational admin — logs in at /admin
{_ADMIN_PASSWORD_KEY}={admin_password}
# trader: order placement and position management
{_TRADER_PASSWORD_KEY}={trader_password}

# ── Database (SQLite for dev) ─────────────────────────────────────────────────
DATABASE_URL=sqlite:///{_DB_URL_PATH}

# ── Redis (optional in dev — app degrades gracefully without it) ──────────────
# Without Redis: token revocation (logout) uses in-memory fallback.
# Revoked tokens are forgotten on server restart — acceptable for dev.
# For production/VPS: install Redis and set REDIS_URL to your Redis instance.
#   Windows: https://github.com/microsoftarchive/redis/releases
#   Linux:   sudo apt install redis-server && sudo systemctl enable redis
REDIS_URL=redis://localhost:6379/0

# ── Broker (paper trading — no real credentials needed) ──────────────────────
BROKER_TYPE=paper

# ── Auth (dev: skip email verification so users can log in immediately) ───────
REQUIRE_EMAIL_VERIFICATION=false

# ── Sentry (disabled in dev) ──────────────────────────────────────────────────
# SENTRY_DSN=
"""
    # Write .env — use plain open() for cross-platform compatibility.
    # On Unix, restrict permissions after writing. On Windows, os.chmod
    # is a no-op for most permission bits so we skip it silently.
    ENV_PATH.write_text(content, encoding="utf-8")
    try:
        ENV_PATH.chmod(0o600)
    except (NotImplementedError, OSError):
        pass  # Windows — file permissions not supported, skip silently
    return True


def _load_env() -> None:
    """Load .env into os.environ (idempotent). Sets fallback secrets for seeding."""
    os.environ.setdefault("APP_ENV", "development")
    os.environ.setdefault("DATABASE_URL", f"sqlite:///{_DB_URL_PATH}")
    try:
        from dotenv import load_dotenv

        load_dotenv(ENV_PATH, override=False)
    except ImportError:
        for _line in ENV_PATH.read_text().splitlines():
            line = _line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip())
    # Ensure JWT secret is set so auth.service imports don't fail during seeding
    os.environ.setdefault("SECURITY_JWT_SECRET", secrets.token_urlsafe(48))


def _make_engine():
    from sqlalchemy import create_engine

    db_url = os.environ.get("DATABASE_URL", f"sqlite:///{DB_PATH}")
    connect_args = {"check_same_thread": False} if db_url.startswith("sqlite") else {}
    return create_engine(db_url, connect_args=connect_args)


def _seed_user(
    email: str,
    username: str,
    password: str,
    role_value: str,
) -> None:
    """Upsert a single user with the given role. Creates tables if needed."""
    import uuid
    from sqlalchemy.orm import sessionmaker
    from auth.service import hash_password
    from database.models import Base
    from database.user_models import User, UserStatus

    engine = _make_engine()
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    try:
        existing = session.query(User).filter_by(email=email).first()
        if existing:
            if existing.role != role_value:
                existing.role = role_value
                session.commit()
            return
        user = User(
            id=str(uuid.uuid4()),
            email=email,
            username=username,
            hashed_password=hash_password(password),
            role=role_value,
            status=UserStatus.ACTIVE.value,
            is_email_verified=True,
        )
        session.add(user)
        session.commit()
    finally:
        session.close()


def _seed_superadmin() -> str:
    """Seed the superadmin account. Returns the password (from .env)."""
    _load_env()
    from database.user_models import UserRole

    password = os.environ.get(_SUPERADMIN_PASSWORD_KEY, "").strip()
    if not password:
        raise RuntimeError(
            f"{_SUPERADMIN_PASSWORD_KEY} not found in environment. "
            "Run bootstrap_dev.py to regenerate .env."
        )
    _seed_user(
        DEFAULT_SUPERADMIN_EMAIL,
        DEFAULT_SUPERADMIN_USERNAME,
        password,
        UserRole.SUPERADMIN.value,
    )
    return password


def _seed_admin() -> str:
    """Seed the admin account. Returns the password (from .env)."""
    _load_env()
    from database.user_models import UserRole

    password = os.environ.get(_ADMIN_PASSWORD_KEY, "").strip()
    if not password:
        raise RuntimeError(
            f"{_ADMIN_PASSWORD_KEY} not found in environment. "
            "Run bootstrap_dev.py to regenerate .env."
        )
    _seed_user(
        DEFAULT_ADMIN_EMAIL,
        DEFAULT_ADMIN_USERNAME,
        password,
        UserRole.ADMIN.value,
    )
    return password


def _seed_trader() -> str:
    """Seed a dev trader account for testing trader-gated endpoints. Returns the password."""
    _load_env()
    from database.user_models import UserRole

    password = os.environ.get(_TRADER_PASSWORD_KEY, "").strip()
    if not password:
        raise RuntimeError(
            f"{_TRADER_PASSWORD_KEY} not found in environment. "
            "Run bootstrap_dev.py to regenerate .env."
        )
    _seed_user(
        DEFAULT_TRADER_EMAIL,
        DEFAULT_TRADER_USERNAME,
        password,
        UserRole.TRADER.value,
    )
    return password


def bootstrap(verbose: bool = True) -> None:
    created = _generate_env()

    if verbose:
        logger.info("\n" + "─" * 62)
        logger.info("  HOPEFX Dev Bootstrap")
        logger.info("─" * 62)
        if created:
            logger.info(f"  ✅  Generated .env  →  {ENV_PATH}")
        else:
            logger.info(f"  ℹ️   .env already exists  →  {ENV_PATH}")

    # ── Seed superadmin ───────────────────────────────────────────────────────
    try:
        _seed_superadmin()
        if verbose:
            logger.info("  ✅  Superadmin seeded")
            logger.info(f"      Email    : {DEFAULT_SUPERADMIN_EMAIL}")
            logger.info(f"      Username : {DEFAULT_SUPERADMIN_USERNAME}")
            logger.info("      Role     : superadmin  →  redirects to /superadmin after login")
            logger.info("      Password : see %s (%s)", ENV_PATH, _SUPERADMIN_PASSWORD_KEY)
    except Exception as exc:  # pylint: disable=broad-exception-caught
        if verbose:
            logger.warning(f"  ⚠️  Superadmin seed skipped: {exc}")

    # ── Seed admin ────────────────────────────────────────────────────────────
    try:
        _seed_admin()
        if verbose:
            logger.info("  ✅  Admin seeded")
            logger.info(f"      Email    : {DEFAULT_ADMIN_EMAIL}")
            logger.info(f"      Username : {DEFAULT_ADMIN_USERNAME}")
            logger.info("      Role     : admin  →  redirects to /admin after login")
            logger.info("      Password : see %s (%s)", ENV_PATH, _ADMIN_PASSWORD_KEY)
    except Exception as exc:  # pylint: disable=broad-exception-caught
        if verbose:
            logger.warning(f"  ⚠️  Admin seed skipped: {exc}")

    # ── Seed trader ───────────────────────────────────────────────────────────
    try:
        _seed_trader()
        if verbose:
            logger.info("  ✅  Trader seeded")
            logger.info(f"      Email    : {DEFAULT_TRADER_EMAIL}")
            logger.info(f"      Username : {DEFAULT_TRADER_USERNAME}")
            logger.info("      Role     : trader  →  redirects to /dashboard after login")
            logger.info("      Password : see %s (%s)", ENV_PATH, _TRADER_PASSWORD_KEY)
    except Exception as exc:  # pylint: disable=broad-exception-caught
        if verbose:
            logger.warning(f"  ⚠️  Trader seed skipped: {exc}")

    if verbose:
        logger.info("─" * 62)
        logger.info("  Start the server:  python app.py")
        logger.info("  Login at:          http://localhost:8000/login")
        logger.info("─" * 62 + "\n")


if __name__ == "__main__":
    bootstrap(verbose=True)
