#!/usr/bin/env python3
# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
"""
scripts/platform_doctor.py
==========================
One-shot **platform health diagnostic**. Scans the whole app — backend imports,
router registration, dependencies, services (Redis/DB), ML model artifacts,
the frontend build, config/secrets, and data-feed API keys — and writes a single
human-readable report so you know *exactly* what to tackle.

It changes nothing. Every check is fail-safe (wrapped) so the report is always
produced even if parts of the app are broken.

Usage (Windows / macOS / Linux)::

    python scripts/platform_doctor.py
    python scripts/platform_doctor.py --output C:\\Users\\Mac\\Desktop\\hopefx_report.md

The report is written to ``diagnostics/HOPEFX_HEALTH_REPORT.md`` by default and
the absolute path is printed at the end.
"""

from __future__ import annotations

import argparse
import importlib
import importlib.util
import io
import os
import platform
import re
import socket
import sys
from contextlib import redirect_stderr, redirect_stdout
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UTC = timezone.utc

# Severity ordering for the summary + prioritised action list.
FAIL, WARN, OK, INFO = "FAIL", "WARN", "OK", "INFO"
_RANK = {FAIL: 0, WARN: 1, OK: 2, INFO: 3}
_ICON = {FAIL: "🔴", WARN: "🟡", OK: "🟢", INFO: "ℹ️"}


class Report:
    """Collects findings and renders the markdown report."""

    def __init__(self) -> None:
        self.findings: list[dict] = []

    def add(self, area: str, status: str, title: str, detail: str = "", fix: str = "") -> None:
        self.findings.append(
            {"area": area, "status": status, "title": title, "detail": detail, "fix": fix}
        )

    # ── rendering ────────────────────────────────────────────────────────────
    def _counts(self) -> dict[str, int]:
        c = {FAIL: 0, WARN: 0, OK: 0, INFO: 0}
        for f in self.findings:
            c[f["status"]] = c.get(f["status"], 0) + 1
        return c

    def render(self) -> str:
        c = self._counts()
        verdict = (
            "🔴 ACTION REQUIRED" if c[FAIL]
            else "🟡 RUNNING WITH WARNINGS" if c[WARN]
            else "🟢 HEALTHY"
        )
        lines: list[str] = []
        lines.append("# HOPEFX — Platform Health Report")
        lines.append("")
        lines.append(f"- **Generated:** {datetime.now(UTC).isoformat()}")
        lines.append(f"- **Verdict:** {verdict}")
        lines.append(
            f"- **Tally:** 🔴 {c[FAIL]} failures · 🟡 {c[WARN]} warnings · "
            f"🟢 {c[OK]} ok · ℹ️ {c[INFO]} info"
        )
        lines.append("")
        lines.append(
            "> This report is read-only diagnostics. Nothing was changed. "
            "Work the **Priority actions** top-down."
        )
        lines.append("")

        # ── Priority actions (FAIL then WARN, with fixes) ─────────────────────
        actionable = [f for f in self.findings if f["status"] in (FAIL, WARN)]
        actionable.sort(key=lambda f: _RANK[f["status"]])
        lines.append("## Priority actions")
        lines.append("")
        if not actionable:
            lines.append("Nothing to do — no failures or warnings detected. 🎉")
        else:
            for i, f in enumerate(actionable, 1):
                lines.append(f"{i}. {_ICON[f['status']]} **[{f['area']}] {f['title']}**")
                if f["detail"]:
                    lines.append(f"   - What: {f['detail']}")
                if f["fix"]:
                    lines.append(f"   - Fix: {f['fix']}")
        lines.append("")

        # ── Full results grouped by area ──────────────────────────────────────
        lines.append("## Full results by area")
        lines.append("")
        areas: list[str] = []
        for f in self.findings:
            if f["area"] not in areas:
                areas.append(f["area"])
        for area in areas:
            lines.append(f"### {area}")
            lines.append("")
            for f in (x for x in self.findings if x["area"] == area):
                row = f"- {_ICON[f['status']]} **{f['title']}**"
                if f["detail"]:
                    row += f" — {f['detail']}"
                lines.append(row)
                if f["fix"] and f["status"] in (FAIL, WARN):
                    lines.append(f"  - _Fix:_ {f['fix']}")
            lines.append("")
        lines.append("---")
        lines.append("_Generated by scripts/platform_doctor.py — re-run any time._")
        return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────────────
# Individual checks. Each is wrapped so one failure never aborts the report.
# ──────────────────────────────────────────────────────────────────────────────
def _safe(fn, rep: Report, area: str) -> None:
    try:
        fn(rep)
    except Exception as exc:
        rep.add(area, WARN, f"{area} check raised an error", f"{type(exc).__name__}: {exc}")


def check_environment(rep: Report) -> None:
    area = "Environment"
    rep.add(area, INFO, "OS", f"{platform.system()} {platform.release()} ({platform.machine()})")
    rep.add(area, INFO, "Python", sys.version.split()[0])
    in_venv = sys.prefix != getattr(sys, "base_prefix", sys.prefix)
    rep.add(area, OK if in_venv else WARN, "Virtual environment",
            "active" if in_venv else "NOT active — deps may be installed globally",
            fix="" if in_venv else "Activate venv: Windows `venv\\Scripts\\activate`")
    pyver = sys.version_info
    if pyver[:2] != (3, 10):
        rep.add(area, INFO, "Python version note",
                f"Running {pyver.major}.{pyver.minor}; production target is 3.10 "
                "(model pickles are built on 3.10).")


def check_env_file(rep: Report) -> None:
    area = "Config & secrets"
    env_path = ROOT / ".env"
    if not env_path.exists():
        rep.add(area, FAIL, ".env missing",
                "No .env file — the app falls back to defaults and many features are off.",
                fix="Run: python scripts/bootstrap_dev.py")
        return
    rep.add(area, OK, ".env present", str(env_path))
    try:
        text = env_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return
    kv = {}
    for raw in text.splitlines():
        line = raw.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            kv[k.strip()] = v.strip()

    # Core config that changes behaviour
    core = {
        "DATABASE_URL": "Persistent storage (else SQLite/in-memory).",
        "REDIS_URL": "Cross-process cache/event bus (else in-memory fallback).",
        "ALLOWED_ORIGINS": "CORS + WebSocket origin allow-list.",
        "APP_ENV": "development vs production behaviour.",
    }
    for k, why in core.items():
        present = bool(kv.get(k))
        rep.add(area, OK if present else WARN, f"{k}",
                "set" if present else f"missing — {why}")

    # Data-feed / news API keys — missing ones explain 403 / timeout log noise.
    feeds = ["FINNHUB_API_KEY", "TWELVE_API_KEY", "POLYGON_API_KEY", "ALPHA_VANTAGE_API_KEY",
             "FMP_API_KEY", "NEWSAPI_KEY", "GOLDAPI_KEY"]
    missing = [k for k in feeds if not kv.get(k)]
    if missing:
        rep.add(area, WARN, "Data-feed API keys missing",
                f"{', '.join(missing)} — these providers will 403/timeout and the app "
                "rotates to free sources (yfinance). Expected if you haven't subscribed.",
                fix="Add the keys to .env, or ignore if you rely on the free fallback.")
    else:
        rep.add(area, OK, "Data-feed API keys", "all common provider keys present")


def check_dependencies(rep: Report) -> None:
    area = "Dependencies"
    # Each entry: module_name -> (description, pip_install_command, is_core)
    # is_core=True → FAIL when missing; is_core=False → WARN when missing.
    _deps: list[tuple[str, str, str, bool]] = [
        (
            "fakeredis",
            "In-process Redis substitute — silences 'Redis unavailable' noise locally.",
            "pip install fakeredis>=2.20.0",
            False,
        ),
        (
            "vaderSentiment",
            "Richer news sentiment (else keyword-only scoring).",
            "pip install vaderSentiment>=3.3.2",
            False,
        ),
        (
            "talib",
            "Native TA indicators (else pure-Python fallback).",
            # TA-Lib requires the C library first:
            #   Ubuntu/Debian: sudo apt-get install libta-lib-dev
            #   macOS:         brew install ta-lib
            # Then: pip install ta-lib>=0.4.28
            "Install C lib first (apt-get install libta-lib-dev  OR  brew install ta-lib), "
            "then: pip install ta-lib>=0.4.28",
            False,
        ),
        (
            "shap",
            "Full ML explainability (else feature_importances_ fallback).",
            "pip install shap>=0.44.0",
            False,
        ),
        ("redis", "Redis client (core).", "pip install redis>=5.0.0", True),
        ("fastapi", "API framework (core).", "pip install -r requirements.txt", True),
        ("xgboost", "Active model backend (core for ML).", "pip install -r requirements.txt", True),
    ]
    for mod, why, fix_cmd, is_core in _deps:
        installed = importlib.util.find_spec(mod) is not None
        sev = OK if installed else (FAIL if is_core else WARN)
        rep.add(
            area,
            sev,
            mod,
            "installed" if installed else f"NOT installed — {why}",
            fix="" if installed else fix_cmd,
        )


def check_backend_import(rep: Report) -> None:
    area = "Backend"
    # Capture router-registration warnings emitted at import time.
    buf_out, buf_err = io.StringIO(), io.StringIO()
    app = None
    try:
        with redirect_stdout(buf_out), redirect_stderr(buf_err):
            mod = importlib.import_module("app")
            app = getattr(mod, "app", None)
    except Exception as exc:
        rep.add(area, FAIL, "Backend failed to import",
                f"{type(exc).__name__}: {exc}",
                fix="This blocks the whole API. Fix the import error above first.")
        return

    if app is None:
        rep.add(area, FAIL, "FastAPI app object not found", "app.py imported but has no `app`.")
        return

    try:
        routes = [r for r in app.routes if hasattr(r, "path")]
        rep.add(area, OK, "Backend imports", f"FastAPI app built with {len(routes)} routes")
        # Surface any router that failed to register (logged as WARNING during import).
        logtext = buf_err.getvalue() + buf_out.getvalue()
        failed = re.findall(r"([\w .]+ router not registered[^\n]*)", logtext)
        if failed:
            for line in failed[:20]:
                rep.add(area, WARN, "Router not registered", line.strip())
        # Confirm the superadmin surface is mounted (the page you've been hitting).
        sa = [r for r in routes if str(getattr(r, "path", "")).startswith("/api/superadmin")]
        rep.add(area, OK if sa else FAIL, "SuperAdmin API",
                f"{len(sa)} /api/superadmin routes mounted" if sa
                else "no /api/superadmin routes — superadmin pages will have no backend",
                fix="" if sa else "Check core/router_registry.py SuperAdmin registration.")
    except Exception as exc:
        rep.add(area, WARN, "Route introspection failed", f"{type(exc).__name__}: {exc}")


def check_services(rep: Report) -> None:
    area = "Services"
    # Redis reachability (short timeout) — purely informational; app has fallbacks.
    url = os.getenv("REDIS_URL", "")
    host, port = "localhost", 6379
    m = re.search(r"://(?:[^@]*@)?([^:/]+):(\d+)", url) if url else None
    if m:
        host, port = m.group(1), int(m.group(2))
    try:
        with socket.create_connection((host, port), timeout=1.5):
            rep.add(area, OK, "Redis", f"reachable at {host}:{port}")
    except Exception:
        rep.add(area, WARN, "Redis not reachable",
                f"{host}:{port} refused/timeout — app uses in-memory/ring-buffer fallback "
                "(fine for single-process dev; required for multi-process prod).",
                fix="Start Redis, or `pip install fakeredis` to silence the noise locally.")


def check_ml_models(rep: Report) -> None:
    area = "ML models"
    import json

    md = ROOT / "ml" / "saved_models"
    reg = md / "registry.json"
    if not reg.exists():
        rep.add(area, FAIL, "registry.json missing", str(reg))
        return
    try:
        data = json.loads(reg.read_text())
    except Exception as exc:
        rep.add(area, FAIL, "registry.json invalid", f"{type(exc).__name__}: {exc}")
        return
    active = data.get("active_version")
    rep.add(area, OK if active else WARN, "Active model",
            f"{active}" if active else "no active_version set in registry")
    # Confirm the active artifact actually exists on disk.
    versions = data.get("versions", {})
    v = versions.get(active, {}) if active else {}
    artifact = v.get("path") or v.get("artifact") or v.get("file")
    if artifact:
        ap = (md / Path(artifact).name)
        exists = ap.exists() or (md / artifact).exists()
        rep.add(area, OK if exists else FAIL, "Active model artifact",
                f"{artifact} {'present' if exists else 'MISSING on disk'}",
                fix="" if exists else "Retrain or restore the model file; CI checksum-verifies it.")


def check_frontend(rep: Report) -> None:
    area = "Frontend"
    static_index = ROOT / "static" / "index.html"
    if not static_index.exists():
        rep.add(area, FAIL, "Frontend not built",
                "static/index.html missing — the server has no UI to serve (blank page).",
                fix="Run: cd frontend && npm ci && npm run build  (or just `start.bat`).")
        return
    rep.add(area, OK, "Frontend built", "static/index.html present")

    # STALE-BUILD detection — the #1 cause of blank/old pages after pulling code.
    build_commit_file = ROOT / "static" / ".build-commit"
    head = ""
    try:
        head = (ROOT / ".git" / "HEAD").read_text().strip()
        if head.startswith("ref:"):
            ref = head.split(" ", 1)[1].strip()
            head = (ROOT / ".git" / ref).read_text().strip()[:40]
    except Exception:
        head = ""
    if build_commit_file.exists() and head:
        built = build_commit_file.read_text(encoding="utf-8", errors="ignore").strip()[:40]
        if built and built != head:
            rep.add(area, WARN, "Frontend build is STALE",
                    f"built from {built[:8]} but HEAD is {head[:8]} — the served UI is older "
                    "than your code. This is the usual cause of blank/old pages.",
                    fix="Rebuild: delete static/ then run start.bat (rebuilds), and hard-refresh "
                        "the browser (Ctrl+Shift+R).")
        else:
            rep.add(area, OK, "Frontend build is current", f"matches HEAD {head[:8]}")
    else:
        rep.add(area, INFO, "Frontend build provenance unknown",
                "no static/.build-commit stamp — can't tell if the build matches HEAD.")

    # node_modules (needed to rebuild)
    nm = ROOT / "frontend" / "node_modules"
    rep.add(area, OK if nm.exists() else INFO, "frontend/node_modules",
            "present" if nm.exists() else "absent — run `npm ci` before building")


def check_frontend_pages(rep: Report) -> None:
    area = "Frontend pages (routes)"
    app_tsx = ROOT / "frontend" / "src" / "App.tsx"
    if not app_tsx.exists():
        rep.add(area, INFO, "App.tsx not found", "skipping page inventory")
        return
    text = app_tsx.read_text(encoding="utf-8", errors="ignore")
    routes = re.findall(r'<Route\s+path="([^"]+)"', text)
    if routes:
        rep.add(area, INFO, "Declared routes",
                f"{len(routes)} client routes, e.g. " + ", ".join(routes[:12]) + (" …" if len(routes) > 12 else ""))
        for guard, label in (("superAdminOnly", "superadmin-only"), ("adminOnly", "admin-only")):
            if guard in text:
                rep.add(area, OK, f"{label} guard wired", f"{guard}(...) present in App.tsx")


# ──────────────────────────────────────────────────────────────────────────────
# Runtime-log analysis — classify the server's console/log output so the report
# shows live state (real bugs vs environmental noise vs shutdown noise) too.
# (regex, category, explanation). Order matters: shutdown + environmental are
# matched first so they don't masquerade as "real" code errors.
# ──────────────────────────────────────────────────────────────────────────────
_LOG_RULES = [
    (re.compile(r"KeyboardInterrupt|CancelledError|anyio\.WouldBlock|raise_signal\(captured_signal\)|Application shutdown"),
     "shutdown", "Server shutdown/teardown noise (Ctrl+C cancelling in-flight work) — not a bug."),
    (re.compile(r"Redis unavailable|Sync Redis connection failed|Redis connect failed|"
                r"(?:connecting to|connection to).{0,40}6379|fakeredis not installed|"
                r"using ring buffer|in-memory fallback|circuit OPEN"),
     "redis", "Redis not running — app uses in-memory/ring-buffer fallback."),
    (re.compile(r"empty DataFrame returned|not a Coinbase product"),
     "feed", "Data source returned nothing (off-hours future / unsupported symbol) — expected."),
    (re.compile(r"403, message='Forbidden'|HTTP 429|Too Many Requests|permanent error \(403|"
                r"Connection timeout to host|FMP fetch_articles error|HTTP error attempt"),
     "feed_api", "External data/news API auth/rate-limit/timeout."),
    (re.compile(r"vaderSentiment not installed|geopolitical sources unavailable|stale cached events|"
                r"ClamAV.{0,40}not reachable"),
     "optional", "Optional capability degraded gracefully (missing dep / external service)."),
    (re.compile(r"no signal for regime|Pipeline: 0 ticks|only 0 bars|Strategy decision timeout|"
                r"stale \(\d+ s\) — rotating source|GoldFeedManager:.*circuit OPEN"),
     "warmup", "Cold-start / market-closed: no bars / no signal yet — expected until data warms up."),
    (re.compile(r"object has no attribute|takes no arguments|unexpected keyword argument|@ -\d+ ms|"
                r"\bTypeError\b|\bKeyError\b|\bAttributeError\b|\bValueError\b|\bIndexError\b|"
                r"\bNameError\b|\bImportError\b|\bModuleNotFoundError\b|\bUnboundLocalError\b"),
     "real", "Possible real code error — investigate."),
]


def _normalize_log_line(line: str) -> str:
    s = re.sub(r"^\d{4}-\d{2}-\d{2}[ T][\d:,\.]+", "", line).strip()
    s = re.sub(r"0x[0-9a-fA-F]+", "0x…", s)
    s = re.sub(r"\d+", "N", s)
    return s[:140]


def _resolve_log(explicit: str | None) -> Path | None:
    if explicit:
        p = Path(explicit)
        return p if p.exists() and p.is_file() else None
    candidates: list[Path] = []
    for pat in ("logs/*.log", "*.log", "logs/*.txt", "server.log"):
        candidates += [c for c in ROOT.glob(pat) if c.is_file()]
    if not candidates:
        return None
    return max(candidates, key=lambda c: c.stat().st_mtime)


def check_runtime_log(rep: Report, log_path: str | None) -> None:
    area = "Runtime log"
    path = _resolve_log(log_path)
    if not path:
        rep.add(area, INFO, "No runtime log found",
                "Pass --log <path>, or capture the server console to a file and re-run.",
                fix="On Windows: python app.py > logs\\server.log 2>&1   (then re-run the doctor)")
        return
    rep.add(area, INFO, "Analyzing log", str(path))
    try:
        with open(path, encoding="utf-8", errors="ignore") as f:
            lines = f.readlines()[-200_000:]  # cap very large logs
    except Exception as exc:
        rep.add(area, WARN, "Could not read log", f"{type(exc).__name__}: {exc}")
        return

    cats: dict[str, int] = {}
    real_samples: dict[str, int] = {}
    api_samples: dict[str, int] = {}
    for ln in lines:
        for rx, cat, _why in _LOG_RULES:
            if rx.search(ln):
                cats[cat] = cats.get(cat, 0) + 1
                if cat == "real":
                    k = _normalize_log_line(ln)
                    real_samples[k] = real_samples.get(k, 0) + 1
                elif cat == "feed_api":
                    k = _normalize_log_line(ln)
                    api_samples[k] = api_samples.get(k, 0) + 1
                break  # first matching rule wins

    rep.add(area, INFO, "Lines scanned", f"{len(lines):,}")

    env_parts = [f"{k}={cats[k]}" for k in ("shutdown", "redis", "feed", "warmup", "optional") if cats.get(k)]
    if env_parts:
        rep.add(area, INFO, "Environmental / expected lines",
                ", ".join(env_parts) + " — graceful fallbacks & shutdown noise, not code bugs.")

    if cats.get("feed_api"):
        rep.add(area, WARN, f"External API failures ({cats['feed_api']})",
                "; ".join(list(api_samples)[:5]),
                fix="Add provider API keys to .env, or ignore (the free yfinance fallback is used).")

    if cats.get("real"):
        top = sorted(real_samples.items(), key=lambda x: -x[1])[:8]
        rep.add(area, WARN, f"Possible code errors in log ({cats['real']})",
                " | ".join(f'"{k}" (x{v})' for k, v in top),
                fix="If a line matches an already-fixed issue (e.g. \"object has no attribute 'get'\", "
                    "\"@ -<n> ms\"), your running process is on OLD code — redeploy from main. "
                    "Otherwise investigate the specific message.")
    else:
        rep.add(area, OK, "No real code errors in log", "only environmental / shutdown noise detected")


def main() -> int:
    parser = argparse.ArgumentParser(description="HOPEFX platform health diagnostic")
    parser.add_argument("--output", "-o", default=str(ROOT / "diagnostics" / "HOPEFX_HEALTH_REPORT.md"),
                        help="Path to write the markdown report")
    parser.add_argument("--log", "-l", default=None,
                        help="Path to a server log file to analyze (auto-detects logs/*.log if omitted)")
    args = parser.parse_args()

    # Ensure the app package is importable.
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))

    rep = Report()
    _safe(check_environment, rep, "Environment")
    _safe(check_env_file, rep, "Config & secrets")
    _safe(check_dependencies, rep, "Dependencies")
    _safe(check_services, rep, "Services")
    _safe(check_ml_models, rep, "ML models")
    _safe(check_frontend, rep, "Frontend")
    _safe(check_frontend_pages, rep, "Frontend pages (routes)")
    # Backend import last — heaviest, most likely to be slow.
    _safe(check_backend_import, rep, "Backend")
    _safe(lambda r: check_runtime_log(r, args.log), rep, "Runtime log")

    md = rep.render()
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")

    c = rep._counts()
    print(md)
    print("\n" + "=" * 70)
    print(f"Report written to: {out.resolve()}")
    print(f"Summary: {c[FAIL]} failures, {c[WARN]} warnings, {c[OK]} ok, {c[INFO]} info")
    # Exit non-zero only on hard failures, so it can gate CI if desired.
    return 1 if c[FAIL] else 0


if __name__ == "__main__":
    raise SystemExit(main())
