# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
# All modifications must be shared under the same license.
# No commercial use without explicit permission.
"""
events/typed_events.py
========================
Typed Pydantic event schema system for the HOPEFX event bus.

Replaces untyped dict payloads with validated, type-safe event envelopes.
All subscribers receive a concrete typed payload — no dict key errors possible.

Usage
-----
    from events.typed_events import EventEnvelope, PriceTickEvent, publish

    tick = PriceTickEvent(symbol="XAUUSD", bid=1985.50, ask=1985.70, volume=1200)
    envelope = EventEnvelope.wrap(source="oanda_poller", payload=tick)
    await publish(envelope)

    # Subscriber
    async def on_tick(env: EventEnvelope[PriceTickEvent]):
        price = env.payload.bid   # fully typed, IDE-autocomplete works
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import uuid
from collections import defaultdict
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any, Generic, TypeVar

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)


# ─────────────────────────────────────────────────────────────────────────────
# Generic envelope
# ─────────────────────────────────────────────────────────────────────────────


class EventEnvelope(BaseModel, Generic[T]):
    """
    Generic typed event envelope.

    Every event flowing through the bus is wrapped in this envelope so that
    routing, logging, and replay infrastructure is uniform regardless of
    payload type.

    Fields
    ------
    event_id  : UUID4 string — unique per event instance
    timestamp : UTC datetime of event creation
    source    : Component that produced the event (e.g. 'oanda_poller')
    event_type: Discriminator string derived from payload class name
    payload   : The typed payload (PriceTickEvent, SignalEvent, etc.)
    model_version: Optional model version tag (for ML signal tracking)
    """

    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    source: str
    event_type: str
    payload: T
    model_version: str | None = None

    @classmethod
    def wrap(
        cls,
        source: str,
        payload: T,
        model_version: str | None = None,
    ) -> EventEnvelope[T]:
        """Convenience constructor — derives event_type from payload class."""
        return cls(
            source=source,
            event_type=type(payload).__name__,
            payload=payload,
            model_version=model_version,
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "event_id": self.event_id,
            "timestamp": self.timestamp.isoformat(),
            "source": self.source,
            "event_type": self.event_type,
            "payload": self.payload.model_dump(),
            "model_version": self.model_version,
        }


# ─────────────────────────────────────────────────────────────────────────────
# Typed payload definitions
# ─────────────────────────────────────────────────────────────────────────────


class PriceTickEvent(BaseModel):
    """Live price tick from a broker feed."""

    symbol: str
    bid: float
    ask: float
    mid: float | None = None
    volume: float | None = None
    spread_pips: float | None = None

    def model_post_init(self, context: Any) -> None:
        if self.mid is None:
            object.__setattr__(self, "mid", (self.bid + self.ask) / 2)


class SignalEvent(BaseModel):
    """Trading signal generated by the ML/signal engine."""

    symbol: str
    action: str  # 'BUY' | 'SELL' | 'HOLD'
    confidence: float  # 0.0 – 1.0
    probability: float  # ML model probability
    entry_price: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    strategy_name: str = "default"
    model_version: str | None = None  # which model produced this signal
    regime: str | None = None  # detected market regime


class OrderFilledEvent(BaseModel):
    """Broker confirmation that an order was filled."""

    order_id: str
    symbol: str
    side: str  # 'buy' | 'sell'
    quantity: float
    fill_price: float
    commission: float = 0.0
    slippage_pips: float | None = None
    broker: str = "unknown"
    account_id: str | None = None


class RiskHaltEvent(BaseModel):
    """Risk manager has halted trading."""

    reason: str
    halt_until: datetime | None = None  # None = manual resume only
    triggered_by: str = "risk_manager"  # component that triggered
    drawdown_pct: float | None = None
    daily_loss_pct: float | None = None
    cvar_breach: bool = False


class PositionDriftEvent(BaseModel):
    """Broker positions diverge from DB positions beyond tolerance."""

    symbol: str
    db_quantity: float
    broker_quantity: float
    quantity_diff: float
    db_value: float
    broker_value: float
    value_diff: float


class RegimeChangeEvent(BaseModel):
    """Market regime transition detected."""

    symbol: str
    previous_regime: str
    new_regime: str
    confidence: float
    volatility: float


class CircuitBreakerEvent(BaseModel):
    """Circuit breaker state change on a broker connection."""

    broker: str
    state: str  # 'open' | 'half_open' | 'closed'
    failure_count: int
    last_error: str | None = None


# ─────────────────────────────────────────────────────────────────────────────
# Typed event bus
# ─────────────────────────────────────────────────────────────────────────────

# Map event_type string → list of async/sync callbacks
_subscribers: dict[str, list[Callable]] = defaultdict(list)


def subscribe(event_type: type[BaseModel], callback: Callable) -> None:
    """
    Register a callback for a specific typed event.

    The callback receives EventEnvelope[event_type] as its sole argument.
    Both sync and async callbacks are supported.

    Example
    -------
        async def handle_tick(env: EventEnvelope[PriceTickEvent]):
            print(env.payload.bid)

        subscribe(PriceTickEvent, handle_tick)
    """
    key = event_type.__name__
    _subscribers[key].append(callback)
    logger.debug("Subscribed %s to %s", getattr(callback, "__name__", repr(callback)), key)


def unsubscribe(event_type: type[BaseModel], callback: Callable) -> None:
    key = event_type.__name__
    with contextlib.suppress(ValueError):
        _subscribers[key].remove(callback)


async def publish(envelope: EventEnvelope) -> None:
    """
    Publish a typed event envelope to all registered subscribers.

    Subscribers are called concurrently via asyncio.gather so a slow
    subscriber does not block others.  Exceptions in individual subscribers
    are caught and logged — they never propagate to the publisher.
    """
    key = envelope.event_type
    handlers = list(_subscribers.get(key, []))

    if not handlers:
        return

    async def _call(cb: Callable) -> None:
        try:
            if asyncio.iscoroutinefunction(cb):
                await cb(envelope)
            else:
                cb(envelope)
        except Exception as exc:
            logger.error(
                "Event subscriber %s raised for %s: %s",
                getattr(cb, "__name__", repr(cb)),
                key,
                exc,
            )

    await asyncio.gather(*[_call(h) for h in handlers])


def publish_sync(envelope: EventEnvelope) -> None:
    """
    Fire-and-forget publish from synchronous code.
    Schedules the publish coroutine on the running event loop if one exists,
    otherwise runs it in a new loop (test / CLI contexts).
    """
    try:
        loop = asyncio.get_running_loop()
        _t = loop.create_task(publish(envelope))
        _t.add_done_callback(lambda _: None)
    except RuntimeError:
        asyncio.run(publish(envelope))
