"""F104 (TODO item 12) — a job named "gate" that cannot fail is not a gate.

`tests.yml`'s `coverage-gate` job had four steps: checkout, download artifact,
extract percentage, post a PR comment. No `exit 1` anywhere. It rendered a
**FAIL** badge into a pull-request comment and exited 0, so a reviewer scanning
the checklist saw a green gate above a comment saying the gate had failed.

Two defects, both of the shape this audit exists to remove:

* `except Exception: print('0.0')` turned a missing or corrupt `coverage.xml`
  into the *number* 0.0 — a value nobody measured, presented as a measurement,
  on a control surface. "I could not measure" is not "you scored zero".
* `(line_rate + branch_rate) / 2` is not the figure the threshold checks.
  coverage.py reports covered over valid across lines **and** branches together;
  averaging two rates computed over different denominators gives a different
  number. Measured on a real report: 83.55% from the mean against 85.25% from
  coverage.py — biased low, and compared against the same 70.

These read the workflow, because the property is about what CI is configured to
do. Behaviour of the two scripts was verified by extracting and running them
against a real coverage.xml, a corrupt one, and a missing one.
"""

from __future__ import annotations

import pathlib
import re

import pytest
import yaml

_TESTS_YML = pathlib.Path(".github/workflows/tests.yml")


@pytest.fixture(scope="module")
def coverage_gate_job() -> dict:
    workflow = yaml.safe_load(_TESTS_YML.read_text(encoding="utf-8"))
    job = workflow["jobs"].get("coverage-gate")
    assert job is not None, "the coverage-gate job is gone"
    return job


def _steps(job: dict) -> dict[str, dict]:
    return {step["name"]: step for step in job["steps"] if step.get("name")}


# ── the name and the exit code agree ──────────────────────────────────────────


def test_the_job_still_calls_itself_a_gate(coverage_gate_job: dict) -> None:
    assert "gate" in coverage_gate_job["name"].lower()


def test_the_gate_has_a_step_that_can_fail(coverage_gate_job: dict) -> None:
    """The finding itself: four steps and no `exit 1` in any of them."""
    steps = _steps(coverage_gate_job)
    assert "Enforce the coverage gate" in steps, (
        "the job is named a gate and has no enforcing step; either it fails on a "
        "real threshold or it should not claim to be a gate"
    )
    run = steps["Enforce the coverage gate"]["run"]
    assert "sys.exit(1)" in run, "the enforcing step cannot fail the build"
    assert re.search(r"gate\s*=\s*70", run), "the enforcing step does not check the 70% threshold"


def test_the_gate_runs_after_the_comment_is_posted(coverage_gate_job: dict) -> None:
    """A red check with no number leaves the author nothing to act on."""
    order = [step["name"] for step in coverage_gate_job["steps"] if step.get("name")]
    assert order.index("Post coverage comment on PR") < order.index("Enforce the coverage gate")

    comment = _steps(coverage_gate_job)["Post coverage comment on PR"]
    assert "always()" in comment.get("if", ""), (
        "the comment is skipped when the gate fails, which is exactly when it is needed"
    )


# ── the number is not fabricated, and is the right number ────────────────────


def test_an_unreadable_report_is_not_reported_as_zero(coverage_gate_job: dict) -> None:
    """0.0 from a failed parse is a fabricated measurement on a control surface."""
    run = _steps(coverage_gate_job)["Extract coverage percentage"]["run"]
    assert "print('0.0')" not in run and 'print("0.0")' not in run, (
        "a missing or corrupt coverage.xml still renders as 0.0% and passes"
    )
    assert "SystemExit(1)" in run or "sys.exit(1)" in run, (
        "the extraction step does not fail when it cannot read the report"
    )


def test_the_percentage_matches_what_coverage_py_reports(coverage_gate_job: dict) -> None:
    """The mean of two rates over different denominators is a different figure."""
    run = _steps(coverage_gate_job)["Extract coverage percentage"]["run"]
    assert "lines-covered" in run and "branches-covered" in run, (
        "the step does not read the covered/valid counters, so it cannot reproduce coverage.py's total"
    )
    assert "(line_rate + branch_rate) / 2" not in run, (
        "the step still averages two rates computed over different denominators; "
        "measured, that reads 83.55% where coverage.py reports 85.25%"
    )


def test_the_formula_reproduces_coverage_pys_total() -> None:
    """The arithmetic, checked directly rather than trusted from the YAML.

    Numbers from a real report generated by `pytest --cov`, which printed
    85.25%: 91 of 106 lines and 13 of 16 branches.
    """
    lines_covered, lines_valid = 91, 106
    branches_covered, branches_valid = 13, 16

    weighted = (lines_covered + branches_covered) / (lines_valid + branches_valid) * 100
    mean_of_rates = (lines_covered / lines_valid + branches_covered / branches_valid) / 2 * 100

    assert round(weighted, 2) == 85.25
    assert round(mean_of_rates, 2) == 83.55
    assert weighted != mean_of_rates
