# HOPEFX-AI-TRADING
# Copyright (c) 2025-2026
# Licensed under GNU Affero General Public License v3.0 (AGPL-3.0)
"""
tests/unit/test_drift_guard_has_a_writer.py
===========================================
The deployed warning is true, and the reason is worse than a missing file.

    ⚠ Feature-drift monitoring is not running — model drift would go undetected

``drift_guard_active()`` returns False because ``ml/saved_models/feature_stats.json``
does not exist. It does not exist because **nothing writes it**:

* ``ml/inference_engine.py`` reads it (the drift guard).
* ``ml/drift_monitor.py`` reads it (``DriftMonitor.from_feature_stats``).
* ``api/ml.py`` reads it (the model card).
* ``.github/workflows/retrain.yml`` and ``quarterly_retrain.yml`` name it as a
  build output to upload and commit.
* ``InferenceEngine._load_train_stats``'s docstring says "Generated by the
  training pipeline (train_advanced.py) after fitting."

``ml/train_advanced.py`` contains no reference to it. Four readers, two
workflows, one docstring — and zero writers. The guard has never run in any
deployment, because its input is produced by nothing.

The workflows hid it: the commit step is

    git add ... ml/saved_models/feature_stats.json ... || true

and ``|| true`` swallows "pathspec did not match any files" every single run.

This is the same defect shape as ``ml:model:status``, the audit trail, and the
feed singleton — the writer and the reader use different paths — taken to its
limit, where there is no writer at all.

**The second half matters more than the first.** Merely creating the file would
have made things worse. ``_check_feature_drift`` skips any live feature absent
from the stats::

    for i, feat_name in enumerate(col_names):
        if feat_name not in train_stats:
            continue

If the stats and the live feature vector share no names — different schema,
older artifact, a renamed feature block — every iteration ``continue``s,
``max_z`` stays 0.0 and ``_drift_detected`` is False. A clean bill of health
from measuring nothing, while ``_drift_stats_available`` is True so
``drift_guard_active()`` reports the guard as running. That is exactly the
S4-05 mistake the function's own comment warns about, reproduced one level
down, and it only becomes reachable once the file exists.

So coverage is now part of "active": a stats file that describes features the
model does not produce leaves the guard off, and says so.
"""

from __future__ import annotations

import json
import pathlib
import re

import numpy as np
import pandas as pd
import pytest

pytestmark = pytest.mark.unit

_ROOT = pathlib.Path(__file__).resolve().parents[2]


def _engine():
    from ml.inference_engine import InferenceEngine

    return InferenceEngine()


def _stats(names: list[str], mean: float = 0.0, std: float = 1.0) -> dict:
    return {n: {"mean": mean, "std": std} for n in names}


def _row(names: list[str], value: float = 0.0) -> pd.DataFrame:
    return pd.DataFrame({n: [value] for n in names})


# ── The missing writer ───────────────────────────────────────────────────────


def test_the_trainer_writes_the_stats_the_drift_guard_reads():
    """Four readers, two workflows and a docstring pointed at a file that no
    line of code produced."""
    src = (_ROOT / "ml" / "train_advanced.py").read_text(encoding="utf-8")
    assert "feature_stats.json" in src, (
        "ml/train_advanced.py does not write feature_stats.json — the drift guard's "
        "only input has no producer, so drift_guard_active() is False everywhere"
    )


def test_the_stats_writer_is_reachable_from_the_training_entry_point():
    """Defining the writer is not enough; main() has to call it."""
    import ml.train_advanced as ta

    assert hasattr(ta, "write_feature_stats"), "no write_feature_stats() in train_advanced"

    import inspect

    main_src = inspect.getsource(ta.main)
    assert "write_feature_stats" in main_src, (
        "write_feature_stats() is defined but main() never calls it — the artifact still never appears"
    )


def test_write_feature_stats_produces_the_shape_the_guard_expects(tmp_path):
    """The guard reads {"feature": {"mean": float, "std": float}}. Anything else
    is a file that exists and still does not work."""
    from ml.train_advanced import write_feature_stats

    X = pd.DataFrame({"rsi_14": [30.0, 50.0, 70.0], "atr_14": [1.0, 2.0, 3.0]})
    out = tmp_path / "feature_stats.json"
    write_feature_stats(X, out)

    data = json.loads(out.read_text())
    assert set(data) >= {"rsi_14", "atr_14"}
    assert data["rsi_14"]["mean"] == pytest.approx(50.0)
    # Population std (ddof=0) — the drift guard compares a window mean against
    # the training distribution, not a sample estimate of it.
    assert data["rsi_14"]["std"] == pytest.approx(np.std([30.0, 50.0, 70.0]))
    for entry in data.values():
        assert isinstance(entry["mean"], float)
        assert isinstance(entry["std"], float)


def test_written_stats_are_loadable_by_the_guard(tmp_path, monkeypatch):
    """End to end: what the trainer writes is what the engine can read."""
    import ml.inference_engine as ie
    from ml.train_advanced import write_feature_stats

    X = pd.DataFrame({"a": [1.0, 2.0, 3.0], "b": [10.0, 20.0, 30.0]})
    write_feature_stats(X, tmp_path / "feature_stats.json")

    monkeypatch.setattr(ie, "_SAVED", tmp_path)
    eng = _engine()
    loaded = eng._load_train_stats()

    assert loaded is not None, "the engine could not read the file the trainer wrote"
    assert set(loaded) >= {"a", "b"}


def test_non_finite_columns_are_omitted_not_written_as_nan(tmp_path):
    """A NaN mean makes every z-score NaN, and `NaN > threshold` is False — the
    guard would run and never fire."""
    from ml.train_advanced import write_feature_stats

    X = pd.DataFrame({"ok": [1.0, 2.0], "broken": [np.nan, np.nan]})
    out = tmp_path / "s.json"
    write_feature_stats(X, out)

    data = json.loads(out.read_text())
    assert "ok" in data
    assert "broken" not in data, "a feature with no finite values was written as NaN stats"


def test_a_zero_variance_feature_gets_a_usable_std(tmp_path):
    """std=0 divides by max(std, 1e-9), turning any deviation into z≈1e9 and
    flagging drift on a constant feature forever."""
    from ml.train_advanced import write_feature_stats

    X = pd.DataFrame({"constant": [5.0, 5.0, 5.0]})
    out = tmp_path / "s.json"
    write_feature_stats(X, out)

    data = json.loads(out.read_text())
    assert "constant" not in data, (
        "a zero-variance feature was written; it can only ever produce z=0 or z=1e9, never a meaningful drift signal"
    )


# ── Turning the guard on without waiting for a retrain ───────────────────────


class _Scaler:
    def __init__(self, names, means, variances):
        self.feature_names_in_ = np.array(names)
        self.mean_ = np.array(means, dtype=float)
        self.var_ = np.array(variances, dtype=float)
        # sklearn's _handle_zeros_in_scale: a zero scale becomes 1.0.
        self.scale_ = np.where(self.var_ > 0, np.sqrt(self.var_), 1.0)


def test_stats_are_derived_from_variance_not_from_scale():
    """The trap this script exists for. sklearn forces `scale_` to 1.0 on a
    zero-variance column, so copying `scale_` would write std=1.0 for a
    constant feature and the guard would measure real deviation against a
    fabricated spread."""
    from scripts.derive_feature_stats import derive_from_scaler

    stats, dropped = derive_from_scaler(_Scaler(["real", "constant"], [5.0, 3.0], [4.0, 0.0]))

    assert stats["real"]["std"] == pytest.approx(2.0)
    assert "constant" in dropped
    assert "constant" not in stats, "a zero-variance feature was written with the forced scale_=1.0"


def test_derived_stats_match_the_scaler_means():
    from scripts.derive_feature_stats import derive_from_scaler

    stats, _ = derive_from_scaler(_Scaler(["a", "b"], [1.5, -2.5], [9.0, 0.25]))
    assert stats["a"] == {"mean": pytest.approx(1.5), "std": pytest.approx(3.0)}
    assert stats["b"] == {"mean": pytest.approx(-2.5), "std": pytest.approx(0.5)}


def test_an_unfitted_scaler_is_refused_not_guessed():
    from scripts.derive_feature_stats import derive_from_scaler

    class _Bare:
        mean_ = np.array([1.0])
        var_ = np.array([1.0])
        # no feature_names_in_ — fitted on a bare array, names unrecoverable

    with pytest.raises(ValueError, match="feature_names_in_"):
        derive_from_scaler(_Bare())


def test_an_existing_stats_file_is_not_overwritten_by_default(tmp_path, monkeypatch):
    """A file from a real training run has better provenance than one derived
    from the scaler. Clobbering it silently would downgrade the artifact."""
    import joblib

    from scripts.derive_feature_stats import main as derive_main

    scaler_path = tmp_path / "scaler.pkl"
    joblib.dump(_Scaler(["a"], [1.0], [4.0]), scaler_path)
    out = tmp_path / "feature_stats.json"
    out.write_text('{"from_training": {"mean": 0.0, "std": 1.0}}')

    assert derive_main(["--scaler", str(scaler_path), "--output", str(out), "--apply"]) == 3
    assert "from_training" in json.loads(out.read_text()), "the existing artifact was overwritten"

    assert derive_main(["--scaler", str(scaler_path), "--output", str(out), "--apply", "--force"]) == 0
    assert "a" in json.loads(out.read_text())


def test_a_dry_run_writes_nothing(tmp_path):
    import joblib

    from scripts.derive_feature_stats import main as derive_main

    scaler_path = tmp_path / "scaler.pkl"
    joblib.dump(_Scaler(["a"], [1.0], [4.0]), scaler_path)
    out = tmp_path / "feature_stats.json"

    assert derive_main(["--scaler", str(scaler_path), "--output", str(out)]) == 1
    assert not out.exists()


# ── The shipped artifact ─────────────────────────────────────────────────────


def test_the_shipped_stats_file_exists_and_is_well_formed():
    """The deployed warning said drift monitoring was not running. It was
    right, and this is the artifact that answers it."""
    path = _ROOT / "ml" / "saved_models" / "feature_stats.json"
    assert path.exists(), "feature_stats.json is missing again — the drift guard is off"

    data = json.loads(path.read_text())
    assert len(data) > 50, f"only {len(data)} features — too few to monitor a 200+ feature model"
    for name, entry in data.items():
        assert set(entry) == {"mean", "std"}, f"{name}: unexpected keys {set(entry)}"
        assert np.isfinite(entry["mean"]), f"{name}: non-finite mean"
        assert entry["std"] > 0, f"{name}: std={entry['std']} can only yield z=0 or z=1e9"


def test_the_shipped_stats_agree_with_the_shipped_scaler():
    """Pins provenance. If someone regenerates one and not the other, the
    numbers stop describing the model the predictor normalises against."""
    import joblib

    from scripts.derive_feature_stats import derive_from_scaler

    scaler = joblib.load(_ROOT / "ml" / "saved_models" / "feature_scaler.pkl")
    expected, _ = derive_from_scaler(scaler)
    actual = json.loads((_ROOT / "ml" / "saved_models" / "feature_stats.json").read_text())

    if set(actual) != set(expected):
        pytest.skip("feature_stats.json has been regenerated by a training run — provenance moved on")

    for name, entry in expected.items():
        assert actual[name]["mean"] == pytest.approx(entry["mean"])
        assert actual[name]["std"] == pytest.approx(entry["std"])


# ── Coverage is part of "active" ─────────────────────────────────────────────


def test_stats_that_match_no_live_feature_leave_the_guard_off():
    """The dangerous case. Before the fix this reported a clean result from
    measuring nothing, and claimed the guard was running while it did."""
    import ml.inference_engine as ie

    eng = _engine()
    eng._train_stats = _stats(["old_feature_a", "old_feature_b"])

    for _ in range(ie._DRIFT_WINDOW + 1):
        eng._check_feature_drift(_row(["new_feature_x", "new_feature_y"]))

    assert eng.drift_guard_active() is False, (
        "the stats file describes features the model does not produce, so nothing is "
        "being compared — reporting the guard as active is the S4-05 mistake one level down"
    )


def test_partial_coverage_below_the_floor_leaves_the_guard_off():
    """One matching feature out of forty is not drift monitoring."""
    import ml.inference_engine as ie

    live = [f"f{i}" for i in range(40)]
    eng = _engine()
    eng._train_stats = _stats(["f0"])

    for _ in range(ie._DRIFT_WINDOW + 1):
        eng._check_feature_drift(_row(live))

    assert eng.drift_guard_active() is False


def test_full_coverage_turns_the_guard_on():
    """Control: the guard must actually switch on, or the tests above pass for
    the wrong reason."""
    import ml.inference_engine as ie

    live = [f"f{i}" for i in range(10)]
    eng = _engine()
    eng._train_stats = _stats(live)

    for _ in range(ie._DRIFT_WINDOW + 1):
        eng._check_feature_drift(_row(live))

    assert eng.drift_guard_active() is True


def test_coverage_is_reported_not_just_used():
    """An operator seeing "not running" needs to know whether the file is
    missing or the schema moved — the two have different fixes."""
    import ml.inference_engine as ie

    live = [f"f{i}" for i in range(10)]
    eng = _engine()
    eng._train_stats = _stats(live[:2])

    for _ in range(ie._DRIFT_WINDOW + 1):
        eng._check_feature_drift(_row(live))

    status = eng.drift_status()
    assert status["active"] is False
    assert status["reason"] == "insufficient_coverage"
    assert status["covered"] == 2
    assert status["total"] == 10


def test_a_missing_file_and_a_stale_schema_report_different_reasons(tmp_path, monkeypatch):
    """Point _SAVED at an empty directory so the file is genuinely absent.

    Setting `_train_stats = None` is not enough: `_load_train_stats` re-reads
    from disk whenever the cache is None, so with a real feature_stats.json in
    the tree this would report `insufficient_coverage` — the *other* reason —
    and pass or fail for reasons unrelated to what it is testing.
    """
    import ml.inference_engine as ie

    monkeypatch.setattr(ie, "_SAVED", tmp_path)
    eng = _engine()
    eng._train_stats = None
    eng._check_feature_drift(_row(["a", "b"]))

    status = eng.drift_status()
    assert status["active"] is False
    assert status["reason"] == "no_training_stats"


def test_real_drift_is_still_detected_with_coverage():
    """The whole point. A feature far from its training mean must fire."""
    import ml.inference_engine as ie

    live = [f"f{i}" for i in range(5)]
    eng = _engine()
    eng._train_stats = _stats(live, mean=0.0, std=1.0)

    detected = False
    for _ in range(ie._DRIFT_WINDOW + 1):
        # 100 sigma from the training mean.
        detected = eng._check_feature_drift(_row(live, value=100.0))

    assert detected is True, "coverage tracking suppressed a real drift detection"
    assert eng.drift_guard_active() is True


# ── What the user is told ────────────────────────────────────────────────────


class _Engine:
    """Minimal stand-in for InferenceEngine, matching tests/unit/test_chart_analysis.py."""

    def __init__(self, status: dict):
        self._status = status

    def predict(self, df, symbol="XAUUSD"):
        return {
            "direction": "long",
            "confidence": 0.7,
            "probability": 0.8,
            "model_version": "v1",
            "bars_used": 200,
            "fallback": False,
        }

    def is_safe_to_trade(self):
        return True

    def drift_guard_active(self):
        return bool(self._status["active"])

    def drift_status(self):
        return self._status


def _bars(n: int = 200):
    return pd.DataFrame(
        {
            "open": np.linspace(2000, 2100, n),
            "high": np.linspace(2001, 2101, n),
            "low": np.linspace(1999, 2099, n),
            "close": np.linspace(2000, 2100, n),
            "volume": np.full(n, 1000.0),
        }
    )


def _warning(status: dict) -> str:
    from analysis.chart_analysis import run_model

    verdict = run_model(_bars(), "XAUUSD", _Engine(status))
    matches = [w for w in verdict.warnings if "drift" in w.lower()]
    assert matches, f"no drift warning raised for {status}"
    return matches[0]


def test_a_missing_artifact_names_the_artifact():
    """The operator's fix is 'retrain to produce the file'. Say which file."""
    text = _warning({"active": False, "reason": "no_training_stats", "covered": 0, "total": 40})
    assert "feature_stats.json" in text


def test_a_stale_schema_says_so_and_gives_the_numbers():
    """A different failure with a different fix — the file is there, the model
    moved out from under it. Saying only 'not running' sends the operator to
    look for a file that exists."""
    text = _warning({"active": False, "reason": "insufficient_coverage", "covered": 3, "total": 40})
    assert "3 of 40" in text
    assert "stale" in text.lower()


def test_an_active_guard_raises_no_warning():
    from analysis.chart_analysis import run_model

    verdict = run_model(_bars(), "XAUUSD", _Engine({"active": True, "reason": "ok", "covered": 40, "total": 40}))
    assert not [w for w in verdict.warnings if "drift" in w.lower()]


def test_an_engine_without_drift_status_still_warns():
    """Back-compat: the warning must not disappear because the richer accessor
    is missing on an older engine.

    Deliberately NOT a subclass of `_Engine` — inheriting `drift_status` would
    leave `hasattr` True and this test would pass without ever exercising the
    fallback branch it exists to cover.
    """
    from analysis.chart_analysis import run_model

    class _Old:
        def predict(self, df, symbol="XAUUSD"):
            return {
                "direction": "long",
                "confidence": 0.7,
                "probability": 0.8,
                "model_version": "v1",
                "bars_used": 200,
                "fallback": False,
            }

        def is_safe_to_trade(self):
            return True

        def drift_guard_active(self):
            return False

    old = _Old()
    assert not hasattr(old, "drift_status"), "the fallback branch is not being exercised"

    verdict = run_model(_bars(), "XAUUSD", old)
    warnings = [w for w in verdict.warnings if "drift" in w.lower()]
    assert warnings, "the warning vanished on an engine without drift_status()"
    # No reason available, so no invented detail.
    assert "stale" not in warnings[0].lower()


# ── The analyzer that flagged the guard as the leak ──────────────────────────


def test_isfinite_counts_as_a_nan_guard():
    """`security/code_analyzer.py` accepted `isnan(` but not `isfinite(`, and
    reported HIGH-severity nan_leak on code whose very next line was an
    isfinite check. isfinite is strictly stronger — it excludes ±inf too — so
    accepting it where isnan is accepted cannot weaken the detector."""
    from security.code_analyzer import _NAN_GUARD_RE

    assert _NAN_GUARD_RE.search("if not np.isfinite(var):")
    assert _NAN_GUARD_RE.search("if not math.isfinite(x):")
    # The weaker guard must still be accepted.
    assert _NAN_GUARD_RE.search("if np.isnan(x):")
    # And an unrelated line must still not count as a guard.
    assert not _NAN_GUARD_RE.search("result = np.sqrt(var)")


def test_the_repo_still_has_no_high_severity_findings():
    """Pins that the derivation script is clean under the project's own scanner
    rather than suppressed by a comment."""
    from security.code_analyzer import scan_codebase

    high = [i for i in scan_codebase() if i.severity in ("critical", "high")]
    assert high == [], "\n".join(f"  {i.severity} | {i.category} | {i.file}:{i.line}" for i in high)


# ── The workflow that hid it ─────────────────────────────────────────────────


@pytest.mark.parametrize("workflow", ["retrain.yml", "quarterly_retrain.yml"])
def test_the_retrain_workflow_does_not_swallow_a_missing_artifact(workflow):
    """`git add <path> || true` reported success for a file that was never
    produced, every run, for the life of the workflow."""
    text = (_ROOT / ".github" / "workflows" / workflow).read_text(encoding="utf-8")

    # Find the `git add` continuation block and check it is not `|| true`.
    for match in re.finditer(r"git add\s+\\\n(?:.*\\\n)*.*", text):
        block = match.group(0)
        if "feature_stats.json" not in block:
            continue
        assert "|| true" not in block, (
            f"{workflow}: `git add ... || true` hides a missing feature_stats.json — "
            "the artifact the drift guard depends on can vanish without failing the run"
        )
