// HOPEFX-AI-TRADING — AGPL-3.0
import React, { useEffect, useState } from 'react';
import {
  View, Text, StyleSheet, ScrollView, RefreshControl,
  TouchableOpacity,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useTradingStore } from '../store/tradingStore';
import { useRefreshOnFocus } from '../hooks/useRefreshOnFocus';
import { Card } from '../components/Card';
import { SignalBadge } from '../components/SignalBadge';
import { COLORS, SPACING, RADIUS } from '../utils/theme';
import { formatRelativeTime, confidenceLabel } from '../utils/formatters';
import { Signal, TradingStackParamList } from '../types';

type Nav = NativeStackNavigationProp<TradingStackParamList>;

const SYMBOLS = ['XAUUSD', 'EURUSD', 'GBPUSD', 'USDJPY', 'BTCUSD'];

export function SignalsScreen() {
  const navigation = useNavigation<Nav>();
  const { signals, fetchSignals, isLoading } = useTradingStore();
  const [selectedSymbol, setSelectedSymbol] = useState<string | null>(null);

  const load = () => fetchSignals(selectedSymbol ?? undefined);

  useEffect(() => { load(); }, [selectedSymbol]);
  useRefreshOnFocus(load);

  const filtered = selectedSymbol
    ? signals.filter((s) => s.symbol === selectedSymbol)
    : signals;

  return (
    <SafeAreaView style={styles.safe}>
      {/* Symbol filter */}
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        style={styles.filterBar}
        contentContainerStyle={styles.filterContent}
      >
        <TouchableOpacity
          style={[styles.chip, !selectedSymbol && styles.chipActive]}
          onPress={() => setSelectedSymbol(null)}
        >
          <Text style={[styles.chipText, !selectedSymbol && styles.chipTextActive]}>All</Text>
        </TouchableOpacity>
        {SYMBOLS.map((sym) => (
          <TouchableOpacity
            key={sym}
            style={[styles.chip, selectedSymbol === sym && styles.chipActive]}
            onPress={() => setSelectedSymbol(sym)}
          >
            <Text style={[styles.chipText, selectedSymbol === sym && styles.chipTextActive]}>
              {sym}
            </Text>
          </TouchableOpacity>
        ))}
      </ScrollView>

      <ScrollView
        contentContainerStyle={styles.content}
        refreshControl={<RefreshControl refreshing={isLoading} onRefresh={load} tintColor={COLORS.accent} />}
      >
        <Text style={styles.pageTitle}>AI Signals</Text>
        <Text style={styles.subtitle}>
          Generated by the HopeFX ML engine · {(signals[0]?.ml_probability ?? 0 * 100).toFixed(0)}% model accuracy
        </Text>

        {filtered.length === 0 ? (
          <Text style={styles.emptyText}>No signals available. Pull to refresh.</Text>
        ) : (
          filtered.map((signal) => (
            <SignalCard
              key={signal.id}
              signal={signal}
              onTrade={() => navigation.navigate('PlaceOrder', {
                symbol: signal.symbol,
                side: signal.direction === 'long' ? 'buy' : 'sell',
              })}
            />
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

function SignalCard({ signal, onTrade }: { signal: Signal; onTrade: () => void }) {
  const isExpired = new Date(signal.expires_at) < new Date();

  return (
    <Card style={[styles.signalCard, isExpired && styles.expired]}>
      <View style={styles.signalHeader}>
        <View>
          <Text style={styles.signalSymbol}>{signal.symbol}</Text>
          <Text style={styles.signalTime}>{formatRelativeTime(signal.generated_at)}</Text>
        </View>
        <SignalBadge direction={signal.direction} confidence={signal.confidence} />
      </View>

      <View style={styles.signalGrid}>
        {[
          ['Entry', signal.entry_price.toFixed(2)],
          ['Stop Loss', signal.stop_loss.toFixed(2)],
          ['Take Profit', signal.take_profit.toFixed(2)],
          ['R:R', signal.risk_reward.toFixed(1)],
          ['Confidence', confidenceLabel(signal.confidence)],
          ['Regime', signal.regime],
        ].map(([label, value]) => (
          <View key={label} style={styles.gridItem}>
            <Text style={styles.gridLabel}>{label}</Text>
            <Text style={styles.gridValue}>{value}</Text>
          </View>
        ))}
      </View>

      {/* ML probability bar */}
      <View style={styles.probRow}>
        <Text style={styles.probLabel}>ML Probability</Text>
        <View style={styles.probBar}>
          <View style={[styles.probFill, { width: `${signal.ml_probability * 100}%` as any }]} />
        </View>
        <Text style={styles.probValue}>{(signal.ml_probability * 100).toFixed(1)}%</Text>
      </View>

      {!isExpired && signal.direction !== 'neutral' && (
        <TouchableOpacity
          style={[styles.tradeBtn, { backgroundColor: signal.direction === 'long' ? COLORS.buy : COLORS.sell }]}
          onPress={onTrade}
        >
          <Text style={styles.tradeBtnText}>
            Trade This Signal — {signal.direction === 'long' ? 'BUY' : 'SELL'} {signal.symbol}
          </Text>
        </TouchableOpacity>
      )}

      {isExpired && <Text style={styles.expiredText}>Signal expired</Text>}
    </Card>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  filterBar: { maxHeight: 52, backgroundColor: COLORS.surface, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  filterContent: { paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, gap: SPACING.sm },
  chip: { paddingHorizontal: SPACING.md, paddingVertical: 6, borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.border },
  chipActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
  chipText: { color: COLORS.textMuted, fontSize: 13, fontWeight: '600' },
  chipTextActive: { color: COLORS.white },
  content: { padding: SPACING.md, gap: SPACING.md, paddingBottom: SPACING.xl },
  pageTitle: { color: COLORS.text, fontSize: 24, fontWeight: '800' },
  subtitle: { color: COLORS.textMuted, fontSize: 13, lineHeight: 18 },
  emptyText: { color: COLORS.textMuted, textAlign: 'center', paddingVertical: SPACING.xl },
  signalCard: { gap: SPACING.md },
  expired: { opacity: 0.5 },
  signalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  signalSymbol: { color: COLORS.text, fontSize: 18, fontWeight: '700' },
  signalTime: { color: COLORS.textMuted, fontSize: 12, marginTop: 2 },
  signalGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm },
  gridItem: { width: '30%' },
  gridLabel: { color: COLORS.textMuted, fontSize: 11 },
  gridValue: { color: COLORS.text, fontSize: 13, fontWeight: '600', marginTop: 2 },
  probRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm },
  probLabel: { color: COLORS.textMuted, fontSize: 12, width: 100 },
  probBar: { flex: 1, height: 6, backgroundColor: COLORS.border, borderRadius: RADIUS.full, overflow: 'hidden' },
  probFill: { height: '100%', backgroundColor: COLORS.accent, borderRadius: RADIUS.full },
  probValue: { color: COLORS.accent, fontSize: 12, fontWeight: '700', width: 40, textAlign: 'right' },
  tradeBtn: { borderRadius: RADIUS.md, padding: SPACING.sm, alignItems: 'center' },
  tradeBtnText: { color: COLORS.white, fontWeight: '700', fontSize: 13 },
  expiredText: { color: COLORS.textMuted, fontSize: 12, textAlign: 'center' },
});
